

------------------------------------------------------------------------------------
-- Agroprom Krot
------------------------------------------------------------------------------------
function sell_krot_flash(first_speaker, second_speaker)
	first_speaker:transfer_item(first_speaker:object("krot_flash"), second_speaker)
    second_speaker:transfer_money(2000, first_speaker)
end

function sell_krot_flash_to_friend(first_speaker, second_speaker)
	first_speaker:transfer_item(first_speaker:object("krot_flash"), second_speaker)
    second_speaker:transfer_money(1000, first_speaker)
end

function krot_give_flash(first_speaker, second_speaker)
	first_speaker:transfer_item(first_speaker:object("krot_flash"), second_speaker)
end

function give_krot_reward (first_speaker, second_speaker)
		dialogs.relocate_money(second_speaker, 3000, "in")
end

------------------------------------------------------------------------------------
-- Talks about Ratcatcher
------------------------------------------------------------------------------------

function has_30_money(first_speaker, second_speaker)
	return first_speaker:money() >= 30
end


function not_has_30_money(first_speaker, second_speaker)
	return first_speaker:money() < 30
end


function give_30_money_to_stalker_for_info_about_ratcatcher(first_speaker, second_speaker)
	first_speaker:transfer_money(30, second_speaker)
end

function loc_info()
	level_tasks.add_location_by_sid(story_ids.agr_ratcatcher, "crlc_mdl", "agr_swamp_hint")
	level_tasks.add_location_by_sid(story_ids.agr_factory_location, "crlc_big", "agr_factory_hint")
	level_tasks.add_location_by_sid(story_ids.agr_nii_location, "crlc_big", "agr_nii_hint")
	db.actor:give_info_portion("l03_agroprom_level_info")
end

-- Krot info
function is_krot_info()
	if has_alife_info("krot_info_about_nii") and
		has_alife_info("krot_info_about_factory")
	then
		return false
	end
	return true 
end

-- Ratcatcher info
function is_ratcatcher_info()
	if has_alife_info("agroprom_military_case") and
		not has_alife_info("agroprom_military_case_have")
	then
		return true
	end
	return false 
end

function is_not_ratcatcher_info()
	return not is_ratcatcher_info()
end
