-- AGROPROM

function proceed()
end

--' final update, убираем рудиментные метки и инфы
function process_info_portion(info_id)
	if info_id == "agr_krot_secret_info" and not has_alife_info("agr_find_gunslinger_cache_start") then
		db.actor:give_info_portion("agr_find_gunslinger_cache_start")
		db.actor:give_info_portion("agr_krot_task_complete")
		db.actor:give_info_portion("agr_factory_spawn_spetsnaz")
	end
	
	return false
end

----------------------------------------------------------------------------------------------

function have_quest_case_02(task, objective)
	return db.actor:object("quest_case_02") ~= nil
end

function have_krots_flash(task, objective)
    if db.actor:object("krot_flash") ~= nil then
       db.actor:give_info_portion ("agr_krot_task_complete")
       return true
    end   
	return false
end

function agr_trader_documents()
	if level.name() == "l03_agroprom" then
		news_manager.send_tip( db.actor, "tips_agr_trader_documents", nil, "trader", nil )
	end
end

function have_gunslingers_flash(task, objective)
    if db.actor:object("gunslinger_flash") ~= nil then
    	db.actor:give_info_portion ("agr_find_gunslinger_cache_final")
        return true
    end
    return false   
end

function ghost_tips ()
	news_manager.send_tip(db.actor, "ghost_tips", nil, "prizrak", nil)
	db.actor:give_info_portion ("agr_gunslinger_flash_have")
	-- nv140820 this adds "Find out what happened to Ghost" task
	db.actor:give_info_portion ("agr_find_ghost_start")
end

function agr_actor_enemy ()
    if level_object_by_sid (302) ~= nil then
		local actor = db.actor
		local npc = level_object_by_sid (302)
		local t = db.storage[npc:id()].death
		return npc:relation(actor) == game_object.enemy or (t ~= nil and t.killer == actor:id())
	end
    return false
end
