--Взнос Долгу для прохода на территорию
function has_dolg_deposite(actor, npc)
	return actor:money() >= 1000
end

function give_dolg_deposite(actor, npc)	
	dialogs.relocate_money(npc, 1000, "out")
end

--Бармен в комнате
function give_agroprom_documents(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "quest_case_02", "out")
end

function give_agroprom_reward(first_speaker, second_speaker)
	dialogs.relocate_money(second_speaker, 5000, "in")
end

function give_extra_task(actor, npc)
	if barman_darklab_documents_given(actor,npc) or
	   barman_x16_given(actor,npc) or
	   has_alife_info("bar_deactivate_radar_start")
	then
		return true
	end
	return false
end
function dont_give_extra_task(actor, npc)
	return not give_extra_task(actor, npc)
end

function barman_dont_has_room_job(actor,npc)
	return not barman_has_room_job(actor,npc)
end
function barman_has_room_job(actor,npc)	
	if barman_need_darklab_documents(actor,npc)
	then
		return true
	end
	return false
end

function barman_need_complete_job(actor,npc)
	if barman_darklab_documents_given(actor,npc) and 
	   have_darklab_documents(actor,npc)
	then
		return true
	end
	return false
end

function barman_dont_has_job(actor,npc)
	return not barman_has_job(actor,npc)
end

function barman_has_job(actor,npc)
	if has_alife_info("bar_darklab_document_done") and
	   barman_need_kill_veterans(actor,npc) and has_alife_info("bar_rescue_research_start")
	then
		return true
	end
	return false
end



-- ********************************************************
--			БАРМЕН В КОМНАТЕ
-- ********************************************************
-- Документы с дарклаба
function barman_need_darklab_documents(actor,npc)
	if not has_alife_info("bar_darklab_document_start")
	then
		return true
	end
	return false
end

function barman_darklab_documents_given(actor,npc)
	if has_alife_info("bar_darklab_document_start") and
	   not has_alife_info("bar_darklab_document_done") 
	then
		return true
	end
	return false
end

function have_darklab_documents(first_speaker, second_speaker)
  	return first_speaker:object("dar_document4") ~= nil
end

function hasnt_darklab_documents(first_speaker, second_speaker)
    return first_speaker:object("dar_document4") == nil
end

function give_darklab_documents(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "dar_document4", "out")
end
function give_darklab_reward(first_speaker, second_speaker)
	dialogs.relocate_money(second_speaker, 10000, "in")
end

-- Документы с Янтаря
function barman_x16_given(actor,npc)
	if has_alife_info("bar_x16_documents_start") and
	   not has_alife_info("bar_x16_documents_done")
	then
		return true
	end
	return false
end

-- Документы из янтаря
function have_x16_documents(first_speaker, second_speaker)
  	return first_speaker:object("lab_x16_documents") ~= nil
end
function give_x16_documents(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "lab_x16_documents", "out")
end
function give_x16_reward(first_speaker, second_speaker)
	dialogs.relocate_money(second_speaker, 15000, "in")
end

-- Выдача задания на отключение радара
function barman_need_radar(actor,npc)
	if has_alife_info("bar_deactivate_radar_start")	then
		return true
	end
	return false
end

-- ********************************************************
--			БАРМЕН ЗА ПРИЛАВКОМ
-- ********************************************************
--Долг архивные документы
function have_dolg_arhive_document(first_speaker, second_speaker)
  	return first_speaker:object("dolg_arhive_documents") ~= nil
end

function give_dolg_arhive_document(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "dolg_arhive_documents", "out")
end
-- Флешка ученных с ростка
function actor_have_research(first_speaker, second_speaker)
  	return first_speaker:object("bar_ecolog_flash") ~= nil
end
function actor_transfer_research(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "bar_ecolog_flash", "out")
	if has_alife_info("bar_rescue_research_reward") then
        dialogs.relocate_money(second_speaker, 5000, "in")
    end
end


-- ********************************************************
--			Лидер Долга
-- ********************************************************
--Свобода РГ-6
function have_rg6(first_speaker, second_speaker)
  	return first_speaker:object("wpn_rg-6") ~= nil
end

function dont_have_rg6(first_speaker, second_speaker)
  	return first_speaker:object("wpn_rg-6") == nil or not has_alife_info("mil_svoboda_rg6_gain")
end


function give_rg6(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "wpn_rg-6", "out")
end

function enter_to_dolg(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "dolg_scientific_outfit", "in")
end

--Фамильное ружье охотника
function have_hunters_toz(first_speaker, second_speaker)
  	return amk_utils.inventory_search("hunters_toz", 1)
end
function give_hunters_toz(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "hunters_toz", "out")
end
function have_hunter_reward(first_speaker, second_speaker)
	dialogs.relocate_money(second_speaker, 4000, "in")
end


-- Оплата информации осведомителю.
function has_money_for_informer_1(actor, npc)
	return actor:money() >= 4000
end

function give_money_for_informer_1(actor, npc)
	dialogs.relocate_money(npc, 4000, "out")
end

function has_money_for_informer_2(actor, npc)
	return actor:money() >= 4000
end

function give_money_for_informer_2(actor, npc)	
	dialogs.relocate_money(npc, 4000, "out")
end

function has_money_for_informer_3(actor, npc)
	return actor:money() >= 2000
end

function give_money_for_informer_3(actor, npc)	
	dialogs.relocate_money(npc, 2000, "out")
end

function barman_give_outfit(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "stalker_outfit", "in")
end


function professor_for_resque(npc, actor)
	-- nv140420
	if not has_alife_info("bar_ecolog_research_normal") then
		dialogs.relocate_item_section(npc, "bar_ecolog_flash", "in")
		db.actor:give_info_portion("bar_ecolog_research_normal")
	end
end

-- Ecolog info
function is_ecolog_info()
	if has_alife_info("bar_ecolog_crush_professor_info_about_where") and 
		has_alife_info("bar_ecolog_crush_professor_info_about_zone") and
		has_alife_info("bar_ecolog_crush_professor_info_about_merc")
	then
		if has_alife_info("bar_x16_documents_start") then
			if not has_alife_info("bar_ecolog_crush_professor_info_about_lab") then
				return true
			end
		end
		return false
	end
	return true 
end

-- ********************************************************
--			ARENA
-- ********************************************************

function arena_give_reward(actor, npc)
	local m = 0
	if has_alife_info("bar_arena_fight_1_reward") then
		dialogs.relocate_money(npc, 500, "in")
		dialogs.relocate_item_section(npc, "ammo_9x18_pmm", "in")
		dialogs.relocate_item_section(npc, "mutant_boar_leg", "in")
	elseif has_alife_info("bar_arena_fight_2_reward") then
		dialogs.relocate_money(npc, 700, "in")
		dialogs.relocate_item_section(npc, "ammo_5.45x39_fmj", "in")
		dialogs.relocate_item_section(npc, "ammo_9x19_fmj", "in")
		dialogs.relocate_item_section(npc, "energy_drink", "in")
	elseif has_alife_info("bar_arena_fight_3_reward") then
		dialogs.relocate_money(npc, 2500, "in")
		dialogs.relocate_item_section(npc, "ammo_12x76_zhekan", "in")
		dialogs.relocate_item_section(npc, "ammo_12x76_dart", "in")
		dialogs.relocate_item_section(npc, "mutant_psevdodog_tail", "in")
		dialogs.relocate_item_section(npc, "medkit", "in")
		dialogs.relocate_item_section(npc, "wpn_addon_silencer", "in")
	elseif has_alife_info("bar_arena_fight_4_reward") then
		dialogs.relocate_money(npc, 3400, "in")
		dialogs.relocate_item_section(npc, "ammo_12x70_buck", "in")
		dialogs.relocate_item_section(npc, "ammo_5.45x39_ap", "in")
		dialogs.relocate_item_section(npc, "vodka", "in")
		dialogs.relocate_item_section(npc, "conserva", "in")
	elseif has_alife_info("bar_arena_fight_5_reward") then
		dialogs.relocate_money(npc, 4800, "in")
		dialogs.relocate_item_section(npc, "ammo_9x39_sp5", "in")
		dialogs.relocate_item_section(npc, "antirad", "in")
		dialogs.relocate_item_section(npc, "medkit_army", "in")
	elseif has_alife_info("bar_arena_fight_6_reward") then
		dialogs.relocate_money(npc, 6100, "in")
		dialogs.relocate_item_section(npc, "af_vyvert", "in")
		dialogs.relocate_item_section(npc, "ammo_11.43x23_fmj", "in")
		dialogs.relocate_item_section(npc, "ammo_5.56x45_ss190", "in")
	elseif has_alife_info("bar_arena_fight_7_reward") then
		dialogs.relocate_money(npc, 7600, "in") 
		dialogs.relocate_item_section(npc, "af_fireball", "in")
		dialogs.relocate_item_section(npc, "ammo_9x19_pbp", "in")
		dialogs.relocate_item_section(npc, "ammo_7.62x54_7h14", "in")
		dialogs.relocate_item_section(npc, "ammo_vog-25", "in")
		dialogs.relocate_item_section(npc, "wpn_knife", "in")
	elseif has_alife_info("bar_arena_fight_8_reward") then
		dialogs.relocate_money(npc, 10000, "in")
		dialogs.relocate_item_section(npc, "vodka", "in")
		dialogs.relocate_item_section(npc, "vodka", "in")
		dialogs.relocate_item_section(npc, "vodka", "in")
		dialogs.relocate_item_section(npc, "ammo_5.56x45_ss190", "in")
		dialogs.relocate_item_section(npc, "ammo_5.56x45_ap", "in")
		dialogs.relocate_item_section(npc, "wpn_sig_m1", "in")
	end
	db.actor:give_info_portion("bar_arena_reset")	
	xr_zones.purge_arena_items("bar_arena")
end


function actor_has_1000(actor,npc)
	return actor:money() > 1000
end
function give_money_1000(actor, npc)	
	dialogs.relocate_money(npc, 1000, "out")
end
function actor_has_2000(actor,npc)
	return actor:money() > 2000
end
function give_money_2000(actor, npc)	
	dialogs.relocate_money(npc, 2000, "out")
end
function actor_has_3000(actor,npc)
	return actor:money() > 3000
end
function give_money_3000(actor, npc)	
	dialogs.relocate_money(npc, 3000, "out")
end
function actor_has_5000(actor,npc)
	return actor:money() > 5000
end
function give_money_5000(actor, npc)	
	dialogs.relocate_money(npc, 5000, "out")
end

-- new arena

function arena_has_reward ()
	return has_alife_info("bar_arena_fight_1_reward") or has_alife_info("bar_arena_fight_2_reward") or has_alife_info("bar_arena_fight_3_reward") or has_alife_info("bar_arena_fight_4_reward") or has_alife_info("bar_arena_fight_5_reward") 
		or has_alife_info("bar_arena_fight_6_reward") or has_alife_info("bar_arena_fight_7_reward") or has_alife_info("bar_arena_fight_8_reward")
end

function arena_hasnt_reward ()
	return not
		( 
			has_alife_info("bar_arena_fight_1_reward") or has_alife_info("bar_arena_fight_2_reward") or has_alife_info("bar_arena_fight_3_reward") or has_alife_info("bar_arena_fight_4_reward") or has_alife_info("bar_arena_fight_5_reward") 
			or has_alife_info("bar_arena_fight_6_reward") or has_alife_info("bar_arena_fight_7_reward") or has_alife_info("bar_arena_fight_8_reward")
		)
end

function arena_rank_check_true ()
	if has_alife_info("bar_arena_fight_6_done") or has_alife_info("bar_arena_fight_3_done") then
		if has_alife_info("bar_arena_fight_3_done") and (db.actor:character_rank() >= 300) and not(has_alife_info("bar_arena_fight_6_done")) then
			return true
		end
	elseif has_alife_info("bar_arena_fight_6_done") and (db.actor:character_rank() >= 600) then
		return true 	
	else 
		return false
	end
end

function arena_rank_check_false ()
	return not arena_rank_check_true ()
end

--' final update, делаем нормальные метки
function locate_bar_bar(actor,npc)
	level_tasks.add_location_by_sid(story_ids.bar_bar_locator, "bar_location", "bar_bar_locator")
end

function locate_bar_arena(actor,npc)
	level_tasks.add_location_by_sid(story_ids.bar_arena_locator, "arni_location", "bar_arena_locator")
end

function locate_bar_dolg(actor,npc)
	level_tasks.add_location_by_sid(story_ids.bar_dolg_locator, "base_location", "bar_voronin_name")
end

function del_bar_bar(actor,npc)
	level_tasks.remove_location_by_sid(story_ids.bar_bar_locator, "bar_location", "bar_bar_locator")
end

function del_bar_arena(actor,npc)
	level_tasks.remove_location_by_sid(story_ids.bar_arena_locator, "arni_location", "bar_arena_locator")
end

function del_bar_dolg(actor,npc)
	level_tasks.remove_location_by_sid(story_ids.bar_dolg_locator, "base_location", "bar_voronin_name")
end

function loc_info()
	db.actor:give_info_portion("l05_bar_level_info")
end

-- Dolg info
function is_dolg_info()
	if has_alife_info("dolg_info_about_bar") and
		has_alife_info("dolg_info_about_arena") and
		has_alife_info("dolg_info_about_dolg")
	then
		return false
	end
	return true 
end

-- Barman info
function is_barman_info()
	if has_alife_info("barman_info_about_self") and
		has_alife_info("barman_info_about_ghost") and
		has_alife_info("barman_info_about_fang") and
		has_alife_info("barman_info_about_sci") and
		has_alife_info("barman_info_about_monolit")
	then
		return false
	end
	return true 
end
