--[[
 File: bind_crow.script
 Description: Вороний биндер.
 Author: Peacemaker
 Date: 25.12.07
---------------------------------------------------]]
crow_storage = {}--' воронья стая.

--' Standart function for object binding
function bind(obj)
--'    local new_binder = crow_binder(obj)
--'	obj:bind_object(new_binder)
	obj:bind_object(crow_binder(obj))
end

-------------------------------------------------------------------------------------------------
--' Class "crow_binder"
-------------------------------------------------------------------------------------------------
class "crow_binder" (object_binder)
--' Class constructor
function crow_binder:__init(obj) super(obj)
	self.body_timer = 0
end

--' Class update
function crow_binder:update(delta)
	--' standart update
	object_binder.update(self, delta)
    --' если ворона сдохла и тушка валяется на земле уже 2-е минуты -->
    if not (self.object:alive()) and (self.body_timer<=time_global()-120000) and (self.body_timer~=0) then
	--> удалить её.
	printf("releasing object ["..self.object:name().."]")
--'	dbglog("releasing object ["..self.object:name().."]")
		alife():release(alife():object(self.object:name()), true)
	end
end

--' Reload object
function crow_binder:reload(section)
	object_binder.reload(self, section)
end

--' Reinitialize object
function crow_binder:reinit()
	self.body_timer = 0
	object_binder.reinit(self)
	db.storage[self.object:id()] = {}
	self.st = db.storage[self.object:id()]
end

--' Net spawn
function crow_binder:net_spawn(sobject)
    if not (object_binder.net_spawn(self, sobject)) then
		return false
	end
	db.add_obj(self.object)
    table.insert(bind_crow.crow_storage, self.object)
	self.object:set_callback(callback.death, self.death_callback, self)
	return true
end

--' Net destroy
function crow_binder:net_destroy()
	self.object:set_callback(callback.death, nil)
	db.del_obj(self.object)
	object_binder.net_destroy(self)
end

--' Crow death callback
function crow_binder:death_callback(victim, who)
	self.body_timer = time_global()
--'    for i=1, #bind_crow.crow_storage do
    for i=1, table.getn(bind_crow.crow_storage) do--'
    if (self.object:id()==bind_crow.crow_storage[i]:id()) then
    --' удалить дохлую ворону из стаи.
    table.remove(bind_crow.crow_storage, i)
	break
		end
	end
end

--' Standart function for save
function crow_binder:net_save_relevant()
	return true
end