
function init    (obj)
	xr_motivator.AddToMotivator(obj)
end

function actor_init    (npc)
	npc:bind_object(actor_binder(npc))
end

----------------------------------------------------------------------------------------------------------------------
class "actor_binder" (object_binder)
----------------------------------------------------------------------------------------------------------------------
function actor_binder:__init (obj) super(obj)
	self.am = ogse_signals.get_mgr()
	self.am:call("on_load_before_all")
	self.am:call("on_init", obj)
end

function actor_binder:__finalize()
	ui_loader.init()
	self.am:call("on_finalize")
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_spawn(data)
	self:fix_ui_inventory_info()

	level.show_indicators()
	level.set_snd_volume( 1 )

	db.add_actor(self.object)
	ui_loader.net_spawn(data)
	
	if not db.storage[self.object:id()].pstor then	-- KRodin: из xr_logic почему-то не срабатывает, поэтому создаЄм pstor здесь.
		db.storage[self.object:id()].pstor = {}
	end
	
	amk_testt.table_update_pda()

	level.enable_input() --Ќ≈ ”ƒјЋя“№!

	if actor_stats.add_to_ranking ~= nil then
		actor_stats.add_to_ranking(self.object:id())
	end

	amk.on_game_load()

	if rx_ai then rx_ai.actor_net_spawn() end

-----------------------------------------------------------
	cmd("g_cop_death_anim 0") -- ќтключаем Death Anims, с ними куча багов.
	cmd("unbind use_medkit")
	cmd("unbind use_bandage")
	cmd("unbind contacts")
	
	if isIndoor(level.name()) then  --SSS18
		get_console():execute("ssfx_is_underground 1")
		cmd("r2_tonemap_amount 0.5")
	else
		get_console():execute("ssfx_is_underground 0")
		cmd("r2_tonemap_amount 0.9")
	end
-----------------------------------------------------------
	self.am:call("on_spawn", data)
	
	return true
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_destroy()
	ui_loader.net_destroy()

	if actor_stats.remove_from_ranking ~= nil then
		actor_stats.remove_from_ranking(self.object:id())
	end

	db.del_actor(self.object)

	self.object:set_callback(callback.inventory_info, nil)
	self.object:set_callback(callback.article_info, nil)
	self.object:set_callback(callback.on_item_take, nil)
	self.object:set_callback(callback.on_item_drop, nil)
	self.object:set_callback(callback.trade_sell_buy_item, nil)
	self.object:set_callback(callback.task_state, nil)
	self.object:set_callback(callback.level_border_enter, nil)
	self.object:set_callback(callback.level_border_exit, nil)
	self.object:set_callback(callback.take_item_from_box, nil)
    self.object:set_callback(callback.use_object, nil)
	self.object:set_callback(callback.on_key_press, nil)
	self.object:set_callback(callback.on_key_release, nil)
	self.object:set_callback(callback.on_mouse_wheel, nil)
	self.object:set_callback(callback.on_belt, nil)
	self.object:set_callback(callback.on_ruck, nil)
	self.object:set_callback(callback.on_slot, nil)
	self.object:set_callback(callback.hit, nil)
	self.object:set_callback(callback.death, nil)
    self.object:set_callback(callback.entity_alive_before_hit, nil)
	self.object:set_callback(callback.on_before_use_item, nil)
	self.object:set_callback(callback.level_changer_action, nil)
	self.object:set_callback(callback.on_cell_item_focus, nil)
	self.object:set_callback(callback.on_cell_item_focus_lost, nil)
	self.object:set_callback(callback.on_cell_item_mouse, nil )
	self.object:set_callback(callback.on_footstep, nil)
	self.object:set_callback(callback.on_actor_land, nil)
	self.object:set_callback(callback.on_actor_jump, nil)
	self.object:set_callback(callback.update_artefacts_on_belt, nil)
	
	self.am:call("on_destroy")
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:reinit()
	local npc_id = self.object:id()

	db.storage[npc_id] = { }

	self.st = db.storage[npc_id]
	self.st.pstor = nil

	self.object:set_callback(callback.inventory_info, self.info_callback, self)
	self.object:set_callback(callback.article_info, self.article_callback, self)
	self.object:set_callback(callback.on_item_take, self.on_item_take, self)
	self.object:set_callback(callback.on_item_drop, self.on_item_drop, self)
	self.object:set_callback(callback.trade_sell_buy_item, self.on_trade, self)
	self.object:set_callback(callback.task_state, self.task_callback, self)
	self.object:set_callback(callback.level_border_enter, self.level_border_enter, self)
	self.object:set_callback(callback.level_border_exit, self.level_border_exit, self)
	self.object:set_callback(callback.take_item_from_box, self.take_item_from_box, self)
    self.object:set_callback(callback.use_object, self.use_inventory_item, self)
	self.object:set_callback(callback.hit, self.actor_hit_callback, self)
	self.object:set_callback(callback.death, self.actor_death_callback, self)
	self.object:set_callback(callback.on_key_press, self.on_key, self)
	self.object:set_callback(callback.on_key_release, self.on_key_free, self)
	self.object:set_callback(callback.on_mouse_wheel, self.on_wheel_rotation, self)
	self.object:set_callback(callback.on_belt, self.item_to_belt, self)		-- перемещение предмета на по€с
	self.object:set_callback(callback.on_ruck, self.item_to_backpack, self)	-- перемещение предмета в рюкзак
	self.object:set_callback(callback.on_slot, self.item_to_slot, self)		-- перемещение предмета в слот
	self.object:set_callback(callback.entity_alive_before_hit, self.before_hit_callback, self)
	self.object:set_callback(callback.on_before_use_item, self.before_use, self)
	self.object:set_callback(callback.level_changer_action, self.level_changer_action, self)
	self.object:set_callback(callback.update_artefacts_on_belt, self.update_artefacts_on_belt, self)
	self.object:set_callback(callback.on_cell_item_focus, self.on_cell_item_focus, self)
	self.object:set_callback(callback.on_cell_item_focus_lost, self.on_cell_item_focus_lost, self)
	self.object:set_callback(callback.on_cell_item_mouse, self.on_cell_item_mouse, self)
	self.object:set_callback(callback.on_footstep, self.on_footstep, self)
	self.object:set_callback(callback.on_actor_land, self.on_actor_land, self)
	self.object:set_callback(callback.on_actor_jump, self.on_actor_jump, self)
end

function actor_binder:actor_death_callback(victim, who)
	level.set_snd_volume( 1 )

	self.am:call("on_actor_death", victim, who)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_key(dik, bind)
	ui_loader.on_key(dik, bind)
	self.am:call("on_key_down", dik, bind)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_key_free(dik, bind)
	ui_loader.on_key_free(dik, bind)
	self.am:call("on_key_up", dik, bind)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_cell_item_focus(obj)
	ui_loader.on_cell_item_focus(obj)
	
	self.am:call( "on_cell_item_focus", obj )
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_cell_item_focus_lost(obj)
	ui_loader.on_cell_item_focus_lost(obj)
	
	self.am:call( "on_cell_item_focus_lost", obj )
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_cell_item_mouse( obj, x, y, action )
  self.am:call( "on_cell_item_mouse", obj, x, y, action )
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_wheel_rotation(vol) -- добавленно MonolithUI
	ui_loader.on_wheel_rotation(vol)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:take_item_from_box(box, item)
	if not box or not item then return end
	local sobj = alife():object(item:id())
	if not sobj then return end

	self.am:call("on_take_from_box", box, item)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_border_enter(npc, info_id)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_border_exit(npc, info_id)
end
----------------------------------------------------------------------------------------------------------------------
local info2call = {
	ui_pda                   = "on_pda_open",
	ui_pda_hide              = "on_pda_hide",
	ui_pda_contacts          = "on_pda_contacts_open",
	ui_pda_contacts_hide     = "on_pda_contacts_hide",
	ui_pda_map_local         = "on_pda_map_local",
	ui_pda_map_global        = "on_pda_map_global",
	ui_pda_news              = "on_pda_news_open",
	ui_pda_news_hide         = "on_pda_news_hide",
	ui_pda_jobs_failed       = "on_pda_jobs_failed",
	ui_pda_jobs_accomplished = "on_pda_jobs_accomplished",
	ui_pda_jobs_current      = "on_pda_jobs_current",
	ui_pda_jobs              = "on_pda_jobs_open",
	ui_pda_jobs_hide         = "on_pda_jobs_hide",
	ui_pda_diary             = "on_pda_diary_open",
	ui_pda_diary_hide        = "on_pda_diary_hide",
	ui_pda_encyclopedia      = "on_pda_encyclopedia_open",
	ui_pda_encyclopedia_hide = "on_pda_encyclopedia_hide",
	ui_pda_actor_info        = "on_pda_actor_info",
	ui_pda_ranking           = "on_pda_ranking",
	ui_pda_events            = "on_pda_events",
	ui_inventory             = "on_inventory_open",
	ui_inventory_hide        = "on_inventory_hide",
	ui_talk                  = "on_talk_open",
	ui_talk_hide             = "on_talk_hide",
	ui_trade                 = "on_trade_open",
	ui_trade_hide            = "on_trade_hide",
	ui_car_body              = "on_body_open",
	ui_car_body_hide         = "on_body_hide",
}

function actor_binder:info_callback(npc, info_id)
	level_tasks.proceed()	-- —южет
	level_tasks.process_info_portion(info_id)	-- ќтметки на карте
	ui_loader.on_info(npc,info_id)
	ogsm_debug.del_mark(info_id)
	
	self.am:call("on_info", npc, info_id)
	
	local sc = info2call[info_id]
	if sc then
		self.am:call(sc, npc)
	end
end

function actor_binder:fix_ui_inventory_info()
  for info, _ in pairs( info2call ) do
    if self.object:has_info( info ) then
      log3( "~~[%s]: disable [%s]", script_name(), info )
      self.object:disable_info_portion( info )
    end
  end
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_trade(item, sell_bye, money) 
	trade_manager.onTradeItem(item, sell_bye)

    self.am:call("on_trade", item, sell_bye, money) 
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:article_callback(npc, group, name, article_type)
	if device().precache_frame >1 then return end
	
	ui_loader.encyclopedy_news(group,name)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_item_take (obj)
	if not obj then return end
	
	db.add_inv_item(obj)
	
    level_tasks.proceed()
	if rx_ai then rx_ai.actor_item_take(obj) end
	ui_loader.on_item_take(obj)	
    ogsm_debug.on_take(obj)
    amk_utils.actor_item_take(obj)
    
    self.am:call("on_take", obj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_item_drop (obj)
	if not obj then return end

	db.del_inv_item(obj)

	level_tasks.proceed()
	amk.on_item_drop(obj)
	ui_loader.on_item_drop(obj)
    amk_utils.actor_item_drop(obj)
    
    self.am:call("on_drop", obj, sobj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:before_use(item)
	if not item then return end
	local sobj = alife():object(item:id())
	if not sobj then return end
	
	self.am:call("on_actor_before_use", item, sobj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:use_inventory_item(obj)
	if not obj then return end
	local sobj = alife():object(obj:id())
	if not sobj then return end

    self.am:call("on_use", obj, sobj)
end
----------------------------------------------------------------------------------------------------------------------

function actor_binder:before_hit_callback(hit_data)
  local obj = level.object_by_id( hit_data.who_id )
  if obj then -- если есть виновник хита
    if -- проверяем условия игнорирования урона от дружественного огня
      obj:id() ~= self.object:id()
      and obj:is_stalker()
      and not obj:is_relation_enemy( self.object )
    then
      local enemy = obj:best_enemy()
      if ( not enemy ) or enemy:id() ~= self.object:id() then
        -- подстрелил друг, игнорируем
        hit_data.ignore_hit = true
      end
    end
  end
  if not hit_data.ignore_hit then
    if not self.last_hit_data then
      self.last_hit_data = {}
    end
    dsh.copy_hit_data( hit_data, self.last_hit_data )
	--
	self.am:call("on_actor_before_hit", self.object, hit_data, self)
  end
end
----------------------------------------------------------------------------------------------------------------------

function actor_binder:actor_hit_callback(obj, amount, local_direction, who, bone_index)
	if who and not who:is_actor() and amount > 0 then
		ogse_critical_hit.check_critical(amount, bone_index, who)
	end
end
----------------------------------------------------------------------------------------------------------------------

function actor_binder:task_callback(_task, _objective, _state)
	self.am:call("on_task", _task, _objective, _state)
end
----------------------------------------------------------------------------------------------------------------------
local update_was_never_called = true
function actor_binder:update(delta)   
	--utils2.show_coordinates()

 	if update_was_never_called then
		if not has_alife_info("storyline_actor_start") then
			if not has_alife_info("global_dialogs") then
				self.object:give_info_portion("global_dialogs")
			end

			ogse_sleep_mgr.add_need_for_sleep(5)
			self.am:call("on_storyline_start")
			self.object:give_info_portion("storyline_actor_start")
		end

		self.am:call("on_first_update")
		update_was_never_called = false		
	end	

	if rx_ai then rx_ai.actor_update() end

	-- ќбновление актора
	amk.on_actor_update()
	ui_loader.update()

	self.am:call("on_update", delta)	
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_footstep(obj, power)
	self.am:call("on_footstep", obj, power)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_actor_land(obj)
    self.am:call("actor_on_land", obj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_actor_jump(obj, power)
    self.am:call("actor_on_jump", obj, power)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:item_to_belt(obj)
	if not obj then return end
	local sobj = alife():object(obj:id())
	if not sobj then return end

	self.am:call("on_item_to_belt", obj, sobj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:item_to_backpack(obj)
	if not obj then return end
	local sobj = alife():object(obj:id())
	if not sobj then return end

	self.am:call("on_item_to_ruck", obj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:item_to_slot(obj)
	if not obj then return end
	local sobj = alife():object(obj:id())
	if not sobj then return end

	self.am:call("on_item_to_slot", obj, sobj)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:save(packet)
	xr_logic.pstor_save_all(self.object, packet)

	if rx_ai then rx_ai.actor_save(packet) end
	
	xr_statistic.save(packet)
	self.am:call("on_save", packet)
	self.am:call("on_save_after_all")
end 
----------------------------------------------------------------------------------------------------------------------
function actor_binder:load(reader)
	xr_logic.pstor_load_all(self.object, reader)

	xr_statistic.load(reader)
	
	self.am:call("on_load", reader)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:update_artefacts_on_belt( dt )
  self.am:call( "update_artefacts_on_belt", dt )
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_changer_action( obj, wnd )
	local sobj = obj:get_alife_object()
	local lc = sobj:get_level_changer()
	local lc_name = sobj:name()
	local dest_vertex = lc.dest_game_vertex_id
	local dest_lname = alife():level_name(game_graph():vertex(dest_vertex):level_id())
	local msg_text_wnd = wnd:FindChild("message_box_change_level:message_text")
	local button_yes_wnd = wnd:FindChild("message_box_change_level:button_yes")

	if ogse_surge_mgr.is_surge_started and 
		not (
		lc_name == "exit_to_agr_underground_01" or 
		lc_name == "exit_to_agr_underground_02" or 
		lc_name == "exit_to_labx18_01" or 
		lc_name == "exit_to_brainlab_01" or 
		lc_name == "exit_to_bunker_01" or
		lc_name == "exit_to_sarcofag_01" or 
		lc_name == "exit_to_control_monolith_01"
	) then
		button_yes_wnd:Enable(false)
		msg_text_wnd:GetCUIStatic():SetText(game.translate_string(dest_lname) .. ": ".. game.translate_string("level_changer_blowout"))
	else
		--if not db.actor:has_info("esc_serious_talk") and 
			--(lc_name == "exit_to_garbage_01" or lc_name == "exit_to_escape_01") 
		--then
			--button_yes_wnd:Enable(false)
			--msg_text_wnd:GetCUIStatic():SetText(game.translate_string(dest_lname) .. ": ".. game.translate_string("level_changer_refusal"))
		--else
			button_yes_wnd:Enable(true)
			msg_text_wnd:GetCUIStatic():SetText(game.translate_string(dest_lname) .. ": ".. game.translate_string("level_changer_invitation"))
		--end	
	end
	
	self.am:call( "level_changer_action", obj, wnd )
end
----------------------------------------------------------------------------------------------------------------------
