-----------------------------------------------------------------------------------
-- Monster binding
-----------------------------------------------------------------------------------
function bind(obj)
	local new_binder = generic_object_binder(obj)
	obj:bind_object(new_binder)
end

------------------------------------------------------------------------------------
class "generic_object_binder" (object_binder)
function generic_object_binder:__init(obj) 
	super(obj)
	self.loaded = false
	
	self.am = ogse_signals.get_mgr()
	self.am:call( "on_monster_init", obj, self )
end 
function generic_object_binder:__finalize()
end

function generic_object_binder:reload(section)
	object_binder.reload(self, section)
end

function generic_object_binder:reinit()
	object_binder.reinit(self)

	-- У торговца нет поддержки перемещения
	if self.object:clsid() ~= clsid.script_trader then
		self.object:set_patrol_extrapolate_callback(self.extrapolate_callback, self)
	end

	db.storage[self.object:id()] = { }

	self.st = db.storage[self.object:id()]
end

function generic_object_binder:net_spawn(sobject)
	if not object_binder.net_spawn(self, sobject) then return false end

	db.add_obj(self.object)
	
	self:subscribe_updaters()

	self.object:set_callback(callback.use_object, self.use_callback, self)	

	if not self.object:alive() then
		if rx_ai then rx_ai.corpse_net_spawn(self.object, self.loaded) end

		local s_obj = alife():object(self.object:id())
		if s_obj.offline_dead == 0 then
			s_obj.offline_dead = game.time()+(1*24*60*60*1000)
		elseif s_obj.offline_dead == 1 then
			s_obj.offline_dead = game.time()+(1*24*60*60*1000)
		elseif s_obj.offline_dead > 1 and s_obj.offline_dead <= game.time() then
			if self.object:position():distance_to( db.actor:position() ) > alife():switch_distance() / 2 then --Удаляем только вдалеке от актора
				alife():release(s_obj, true)
			end
		end
		return true
	end

	self.object:set_callback(callback.patrol_path_in_point, 	self.waypoint_callback, 	self)
	self.object:set_callback(callback.hit,						self.hit_callback,			self)
	self.object:set_callback(callback.death,					self.death_callback,		self)
	self.object:set_callback(callback.entity_alive_before_hit, 	self.before_hit_callback, 	self)

	self.object:set_enemy_callback( self.enemy_callback, self )
	xr_gulag.setup_gulag_and_logic_on_spawn( self.object, self.st, sobject, modules.stype_mobile, self.loaded )
	
	self.am:call( "on_monster_spawn", self.object, self )
	return true
end

function generic_object_binder:subscribe_updaters()
  local s_name = "on_monster_update." .. self.object:id()
  if self.object:alive() then
	self.updaters = {
      {
        [ "signal" ] = s_name,
        [ "self"   ] = self,
        [ "fun"    ] = self.update_tip_text,
        [ "queued" ] = true,
      },
	}
  else
  	self.updaters = {}
  end
  for _, s in ipairs( self.updaters ) do
    self.am:subscribe( s )
  end
end

function generic_object_binder:unsubscribe_updaters()
  if not self.updaters then return end

  for k, s in pairs( self.updaters ) do
    self.am:unsubscribe( s )
	self.updaters[k] = nil
  end
  self.updaters = nil
end


function generic_object_binder:update(delta)
	if string.find(self.object:name(), "crow_") or string.find(self.object:section(), "crow") then return false end
	
	object_binder.update(self, delta)

	if self.st.active_section ~= nil then
		xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "update", delta)
	end

	self.am:call( "on_monster_update." .. self.object:id(), self.object, delta )
end

function generic_object_binder:update_tip_text()
	if self.object:is_talk_enabled() then
		self.object:set_tip_text("character_use")
	else
		self.object:set_tip_text("")
	end	
end

function generic_object_binder:use_callback(obj, who)
	if self.object:clsid() == clsid.script_trader then
		if self.object == nil then
	        return
	    end
	    if self.object:alive() then
	        if self.st.active_section then
	            xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "use_callback", obj, who)
	            -- инициализация торговли
	            if who:is_actor() then
	                trade_manager.trade_prepare(obj)
	            end
	        end
	    end
	else				
		self.am:call("on_monster_use", self.object, who)
	end	
end

function generic_object_binder:extrapolate_callback()
	if not (self.object and self.object:get_script()) then return false end
	--
	local cur_pt = self.object:get_current_point_index()
	local patr = self.object:patrol()
	if patr == "" then
		-- Такая ситуация - это норма, просто ванильный движок не вылетал при вызове patrol(""), а новый вылетает, проверено.
		log3("!![%s] Invalid patrol path name [%s] for object [%s]", script_name(), patr, self.object:name())
	elseif patrol(patr):flags(cur_pt):get() == 0 then
		return true
	end
	return false
end

function generic_object_binder:waypoint_callback(obj, action_type, index)
	if self.st.active_section ~= nil then
		xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "waypoint_callback", self.object, action_type, index)
	end
end

function generic_object_binder:death_callback(victim, who)
	self:unsubscribe_updaters()

	self:clear_callbacks()

	-- добавление опыта за убийство
	xr_statistic.addKillCount(who, self.object)

	if self.st and self.st.mob_death then
		xr_logic.issue_event(self.object, self.st.mob_death, "death_callback", self.object, who)
	end

	if self.st and self.st.active_section then
		xr_logic.issue_event(self.object, self.st[self.st.active_scheme], "death_callback", self.object, who)
	end

	smart_terrain.on_death( self.object:id() )

	if rx_ai then rx_ai.monster_death(victim, who) end

	self.am:call( "on_monster_death", self.object, who )
end

function generic_object_binder:before_hit_callback(hit_data)
	if hit_data.weapon_id then
		local wpn = level.object_by_id(hit_data.weapon_id)
		if hit_data.hit_type == hit.fire_wound and wpn and wpn:is_weapon_magazined() then
			-- Увеличим урон от оружия при стрельбе по нпс
			local koef = get_float(wpn:section(), "multiply_hit_from_actor", 1)
			hit_data.power = hit_data.power * koef
		end
	end
	--
	if not self.last_hit_data then
		self.last_hit_data = {}
	end
	dsh.copy_hit_data( hit_data, self.last_hit_data )

	self.am:call("on_monster_before_hit", self.object, hit_data, self)
end

function generic_object_binder:hit_callback(obj, amount, local_direction, who, bone_index)
	if amount == 0 or bone_index == 0 then return end -- Не учитываем выстрелы в воздух. Причину описал в мотиваторе.

	if self.st.hit then
		xr_logic.issue_event(self.object, self.st.hit, "hit_callback", self.object, amount, local_direction, who, bone_index)
	end
end

function generic_object_binder:net_destroy()
	self:clear_callbacks()
	self.object:set_callback(callback.use_object, nil)

	local st = db.storage[self.object:id()]
	if st and st.active_scheme then
		xr_logic.issue_event(self.object, st[st.active_scheme], "net_destroy")
	end
	
	db.del_obj(self.object)
	db.storage[self.object:id()] = nil

	self.am:call( "on_monster_net_destroy", self.object, self )
	self:unsubscribe_updaters()
	self.am:cleanup_signal_subs( "on_monster_update." .. self.object:id() )

	object_binder.net_destroy(self)

	local id   = self.object:id()
	local sobj = alife():object( id )
	if sobj then
		alife():remove_in_restrictions( sobj )
	end
end 

function generic_object_binder:clear_callbacks()
	self.object:set_callback(callback.death,				nil)
	self.object:set_callback(callback.patrol_path_in_point, nil)
	self.object:set_callback(callback.hit,					nil)
	self.object:set_callback(callback.entity_alive_before_hit, nil)
	self.object:set_enemy_callback()
end

function generic_object_binder:reload(section)
	object_binder.reload(self, section)
end

function generic_object_binder:net_save_relevant()
	return true
end

function generic_object_binder:save(packet)
	if string.find(self.object:name(), "crow_") then return false end

	if self.object:clsid() ~= clsid.script_trader then
		xr_logic.pstor_store(self.object, "is_invulnerable", self.object:invulnerable())
	end

	object_binder.save(self, packet)

	xr_logic.save_obj(self.object, packet)
	if self.object:clsid() == clsid.script_trader then
        trade_manager.save(self.object, packet)
    end
end

function generic_object_binder:load(reader)
	if string.find(self.object:name(), "crow_") then return false end

	self.loaded = true

	object_binder.load(self, reader)

	if reader:r_eof() then
		abort("SAVE FILE IS CORRUPT")
	end

	xr_logic.load_obj(self.object, reader)
	if self.object:clsid() ~= clsid.script_trader then
		local is_invulnerable = xr_logic.pstor_retrieve(self.object, "is_invulnerable", false)
		self.object:invulnerable(is_invulnerable)
	else
		trade_manager.load(self.object, reader)
	end
end

--Функция проверяет, может ли объект вступать в бой с предполагаемым противником (enemy_st).
--Если вернёт false - объект не будет вступать в бой.
--Вызывается:
--Одноименным калбеком из движка (для движковой боёвки)
--Из xr_danger
--Из xr_camper.action_patrol:process_danger()
--Из функции check_sound в мотиваторе
local enemy_callback_freq = 1000
function generic_object_binder:enemy_callback( obj, enemy_st )
  local valid, enemy = validate_enemy_object( enemy_st )
  if not valid then return false end

  return true
end
