-------------------------------------------------------------------------
--	created:	2005/02/28
--	created:	28:2:2005   16:08
--	filename: 	x:\gamedata\scripts\dialogs_darkvalley.script
--	file path:	x:\gamedata\scripts
--	file base:	dialogs_darkvalley
--	file ext:	script
--	author:		Andrey Fidrya aka Zmey
--  updated by: Oleg Kreptul (Haron)
--	
--	purpose:	dialog support for Dark Valley
--  070930 - minor change to prevent duplicate loss of money
--           until bug fixed in all.spawn file
-------------------------------------------------------------------------

function val_rob_actor_has_money(actor, npc)
	if has_alife_info("val_rob_buying") then
		return false
	end
	return actor:money() >= 800
end

function val_rob_actor_reloc_money(actor, npc)
	dialogs.relocate_money(npc, 800, "out")
end

function val_escort_reward(npc, actor)
    dialogs.relocate_money(npc, 1300, "in")
    dialogs.relocate_item_section(npc, "wpn_addon_scope", "in")
end

function loc_info()
	db.actor:give_info_portion("l04_darkvalley_level_info")
end

-- Napi info
function is_napi_info()
	if has_alife_info("napi_info_about_bandits") and 
		has_alife_info("napi_info_about_factory") and
		has_alife_info("napi_info_about_farm") and
		has_alife_info("napi_info_about_gates")
	then
		return false
	end
	return true 
end
