-- https://github.com/dsh2dsh/op2ogse/blob/master/gamedata/scripts/dsh/dsh_anomaly_detector.script
-- Модуль обхода аномалий NPC.
-- UPD by Muvbed: 10.08.24

local excluded_npc = {}

local excluded_comms = {
  [ "zombied" ] = true,
}

local excluded_locations = {}

local monster_excluded_locations = {
	["l03u_agr_underground"] = true,
	["l04u_labx18"] = true,
    ["l08u_brainlab"] = true,
    ["l10u_bunker"] = true,
    ["l12u_sarcofag"] = true,
    ["l12u_control_monolith"] = true
}


function attach( sm )
  sm:subscribe({ signal = "on_after_blowout",   	fun = this.on_after_blowout })
  sm:subscribe({ signal = "on_monster_death", 		fun = this.on_death 		})
  sm:subscribe({ signal = "on_monster_net_destroy", fun = this.on_death 		})
  sm:subscribe({ signal = "on_monster_spawn", 		fun = this.on_monster_spawn })
  sm:subscribe({ signal = "on_npc_spawn",       	fun = this.on_npc_spawn     })
  sm:subscribe({ signal = "on_npc_death",       	fun = this.on_death         })
  sm:subscribe({ signal = "on_npc_net_destroy", 	fun = this.on_death         })
end

local mobs = {}

function on_monster_spawn(obj, binder)
	if not obj:alive() then return end
	
    if get_bool(obj:section(), "ogse_anomaly_evader.disable", false)
        or not obj:is_custom_monster()
    then
        return
    end

    local anomaly_detector = obj:get_custom_monster():anomaly_detector()
    if excluded_npc[obj:story_id()]
        or get_bool(obj:section(), "ogse_anomaly_evader.exclude", false)
    then
        anomaly_detector:deactivate(true)
        return
    elseif excluded_locations[level.name()]
        or monster_excluded_locations[level.name()]
    then
        return
    end
    --
	anomaly_detector.Anomaly_Detect_Radius = 30
	--
    anomaly_detector:activate(true)
    
    mobs[obj:id()] = true
end

function on_npc_spawn( obj, binder )
  if not obj:alive() then return end
  
  local anomaly_detector = obj:get_custom_monster():anomaly_detector()
  if ( excluded_npc[ obj:profile_name() ]
      or excluded_npc[ obj:name() ]
      or excluded_npc[ obj:story_id() ]
      or excluded_comms[ obj:character_community() ]
      or excluded_locations[ level.name() ]
    )
  then
    anomaly_detector:deactivate( true )
    return
  end
  --
  anomaly_detector.Anomaly_Detect_Radius = 30
  --
  anomaly_detector:activate( true )
  mobs[ obj:id() ] = true
end


function on_death( obj )
  local binder = obj:binded_object()
  if binder[ script_name()..".anomaly_invisibility" ] then
    set_anomaly_invisibility( obj, false )
    binder[ script_name()..".anomaly_invisibility" ] = nil
  end
  if mobs[ obj:id() ] then
    local anomaly_detector = obj:get_custom_monster():anomaly_detector()
    anomaly_detector:deactivate( true )
    anomaly_detector:remove_all_restrictions()
    mobs[ obj:id() ] = nil
  end
end


function remove_restriction( anomid )
  for id, _ in pairs( mobs ) do
    local obj = level.object_by_id( id )
    if obj then
      local anomaly_detector = obj:get_custom_monster():anomaly_detector()
      anomaly_detector:remove_restriction( anomid )
    end
  end
end


function pre_blow_off()
  for id, _ in pairs( mobs ) do
    local obj = level.object_by_id( id )
    if obj then
      local anomaly_detector = obj:get_custom_monster():anomaly_detector()
      anomaly_detector:deactivate( true )
      anomaly_detector:remove_all_restrictions()
    end
  end
end


function on_after_blowout()
  for id, _ in pairs( mobs ) do
    local obj = level.object_by_id( id )
    if obj then
      local anomaly_detector = obj:get_custom_monster():anomaly_detector()
      anomaly_detector:activate( true )
    end
  end
end


function get_freq() return 1000 end
