-- -*- mode: lua; coding: windows-1251-dos -*-
-- UPD by Muvbed: звуки с/без противогаза и эффекторы плохого самочувствия

function attach(sm)
	sm:subscribe({ signal = "on_update", fun = this.on_update_heart })
end

function on_update_heart()
	ogse_signals.get_mgr():reschedule( 113 )
	
	if not db.actor:alive() then return end
	
	nlc7_actor_heart()
end

local health_effector30 = true
local health_effector10 = true
local power_effector = true
local hunger_effector = true
local sleep_effector4 = true
local sleep_effector5 = true

local delt = 0
local delt_h = 0

function nlc7_actor_heart()
	local npc = db.actor
	
	if not npc then return end
	
	local hb = npc.health
	
	if hb <= 0 or not npc:alive() then return end
	
	if hb < 0.3 then
		if health_effector30 then
			level.add_pp_effector("health_bad.ppe", 7021, true)
			health_effector30 = false
		end
	else
		if not health_effector30 then
			level.remove_pp_effector(7021)
			health_effector30 = true
		end
	end
	
	if hb < 0.1 then
		if health_effector10 then
			level.add_pp_effector("crit.ppe", 7022, true)
			health_effector10 = false
		end
	else
		if not health_effector10 then
			level.remove_pp_effector(7022)
			health_effector10 = true
		end
	end
	
	local r_h = npc.power
	
	if r_h < 0.1 then
		if power_effector then
			level.add_pp_effector("power_bad.ppe", 7023, true)
			power_effector = false
		end
	else
		if not power_effector then
			level.remove_pp_effector(7023)
			power_effector = true
		end
	end
	
	local satiety = npc.satiety
	local thirst = npc.thirst
	
	if satiety <= 0.1 or thirst <= 0.1 then
		if hunger_effector then
			level.add_pp_effector("hunger.ppe", 7024, true)
			hunger_effector = false
		end
	else
		if not hunger_effector then
			level.remove_pp_effector(7024)
			hunger_effector = true
		end
	end
	
	local sleep_level = ogse_sleep_mgr.sleep_level
	
	if sleep_level >= 5 then
		if sleep_effector5 then
			level.add_pp_effector("sleep_crit.ppe", 7301, true)
			sleep_effector5 = false
		end
	else
		if not sleep_effector5 then
			level.remove_pp_effector(7301)
			sleep_effector5 = true
		end
	end
	
	local time_curr = time_global()
	local time_delt = 0
	local step = 1
	
	if hb < 0.5 then
		time_delt = time_curr - delt_h
		
		if time_delt >= math.log(hb * 200) * 200 then
			if hb < 0.1 then
				step = 3
			elseif hb < 0.3 then
				step = 2
			else
				step = 1
			end
			
			local snd_fname = "actor\\nlc7\\heartbeat_" .. step .. "_" .. math.random(4)
			local snd = xr_sound.get_safe_sound_object(snd_fname)
			
			if snd then
				snd.volume = 1.5 - 5 * hb
				snd:play(db.actor, 0, sound_object.s2d)
			end
			
			delt_h = time_curr
		end
	end
	
	if r_h < 0.5 then
		time_delt = time_curr - delt
		
		if time_delt >= r_h * 1500 + 800 then
			if r_h < 0.1 then
				step = 3
			elseif r_h < 0.3  then
				step = 2
			else
				step = 1
			end
			
			local snd_fname = ""
			
			local helmet = db.actor:item_in_slot(10)
			
			if helmet then
				snd_fname = "actor\\nlc7\\with_mask_" .. step .. "_" .. math.random(6)
			else
				snd_fname = "actor\\nlc7\\without_mask_" .. step .. "_" .. math.random(6)
			end

			local snd = xr_sound.get_safe_sound_object(snd_fname)
			
			if snd then
				snd.volume = 1 - 5 * r_h
				snd:play( db.actor, 0, sound_object.s2d )
			end
			
			delt = time_curr
		end
	end
end
