--[[-----------------------------------------------------------------------------------------------
 File			: hotkey.script
 Description 	: гор€чие клавиши
 UPD by Muvbed	: 2024
--]]-----------------------------------------------------------------------------------------------

local get_wnd = level.main_input_receiver
local hud = get_hud()
local binds_actions = {}
local dik_actions = {}
local keys = {
	[1] = 'ESCAPE', [2] = '1', [3] = '2', [4] = '3', [5] = '4', [6] = '5', [7] = '6', [8] = '7',
	[9] = '8', [10] = '9', [11] = '0', [12] = 'MINUS', [13] = 'EQUALS', [14] = 'BACK', [15] = 'TAB', [16] = 'Q',
	[17] = 'W', [18] = 'E', [19] = 'R', [20] = 'T', [21] = 'Y', [22] = 'U', [23] = 'I', [24] = 'O', [25] = 'P',
	[26] = 'LBRACKET', [27] = 'RBRACKET', [28] = 'RETURN', [29] = 'LCONTROL', [30] = 'A', [31] = 'S', [32] = 'D',
	[33] = 'F', [34] = 'G', [35] = 'H', [36] = 'J', [37] = 'K', [38] = 'L', [39] = 'SEMICOLON', [40] = 'APOSTROPHE',
	[41] = 'GRAVE', [42] = 'LSHIFT', [43] = 'BACKSLASH', [44] = 'Z', [45] = 'X', [46] = 'C', [47] = 'V', [48] = 'B',
	[49] = 'N', [50] = 'M', [51] = 'COMMA', [52] = 'PERIOD', [53] = 'SLASH', [54] = 'RSHIFT', [55] = 'MULTIPLY',
	[56] = 'LMENU', [57] = 'SPACE', [58] = 'CAPITAL', [59] = 'F1', [60] = 'F2', [61] = 'F3', [62] = 'F4', [63] = 'F5',
	[64] = 'F6', [65] = 'F7', [66] = 'F8', [67] = 'F9', [68] = 'F10', [69] = 'NUMLOCK', [70] = 'SCROLL', [71] = 'NUMPAD7',
	[72] = 'NUMPAD8', [73] = 'NUMPAD9', [74] = 'SUBTRACT', [75] = 'NUMPAD4', [76] = 'NUMPAD5', [77] = 'NUMPAD6',
	[78] = 'ADD', [79] = 'NUMPAD1', [80] = 'NUMPAD2', [81] = 'NUMPAD3', [82] = 'NUMPAD0', [83] = 'DECIMAL', [87] = 'F11',
	[88] = 'F12', [100] = 'F13', [101] = 'F14', [102] = 'F15', [112] = 'KANA', [121] = 'CONVERT', [123] = 'NOCONVERT',
	[125] = 'YEN', [141] = 'NUMPADEQUALS', [144] = 'CIRCUMFLEX', [145] = 'AT', [146] = 'COLON', [147] = 'UNDERLINE',
	[148] = 'KANJI', [149] = 'STOP', [150] = 'AX', [151] = 'UNLABELED', [156] = 'NUMPADENTER', [157] = 'RCONTROL',
	[179] = 'NUMPADCOMMA', [181] = 'DIVIDE', [183] = 'SYSRQ', [184] = 'RMENU', [197] = 'PAUSE', [199] = 'HOME',
	[200] = 'UP', [201] = 'PRIOR', [203] = 'LEFT', [205] = 'RIGHT', [207] = 'END', [208] = 'DOWN', [209] = 'NEXT',
	[210] = 'INSERT', [211] = 'DELETE', [219] = 'LWIN', [220] = 'RWIN', [221] = 'APPS', [337] = 'MOUSE1', [338] = 'MOUSE2'
}

function bind2key(bind)
	return keys[bind_to_dik(bind)]
end
function dik2key(dik)
	return keys[dik]
end

function on_key(dik, bind)
	if not db.actor:alive() then return end
	if get_wnd() ~= nil then return end

	if binds_actions[bind] then
		binds_actions[bind]()
	elseif dik_actions[dik] then
		dik_actions[dik]()
	end
	
	if dik == amk.load_variable("qsb", 0) and not amk.load_variable("near_campfire", false) then
		hud:AddCustomStatic("game_save_disabled", true)
		dsh.timeout(2000, function()
			if hud:GetCustomStatic("game_save_disabled") ~= nil then
				hud:RemoveCustomStatic("game_save_disabled")
			end
		end)
	end
end

function hud_msg(xml, txt)
	hud:AddCustomStatic(xml, true)
	local wnd = hud:GetCustomStatic(xml):wnd()
	wnd:SetText(txt)
end

----------------------------------------

-- 'Numpad 0' - худ-маска вкл./выкл
binds_actions[key_bindings.kMASK] = function()
	dynamic_hud.on_key()
	return true
end

-- 'Z' - сброс рюкзака
binds_actions[key_bindings.kRUCK] = function()
	smart_ruck.on_key()
	return true
end

----------------------------------------

function disable_save()
	if not amk.load_variable("near_campfire", false) then
		level.block_action(key_bindings.kQUICK_SAVE)
	else
		level.unblock_action(key_bindings.kQUICK_SAVE)
	end
end