------------------------------------
-- Модуль "Сон НПС".
-- Created by Bak (Rulix), Monnoroch.
-- 15.07.09
------------------------------------
class "evaluator_sleep" (property_evaluator)
function check_mili()
    local lvl = "l07_military"
    local result
    if lvl == tostring(level.name()) then
        if db.actor:dont_has_info("mil_patrol_kill_continue") then
            result = false
        else
            result = true
        end
    else
        result = true
    end

    return result
end

-- Затычка на миссию по спасению Крота. Очень глюченная миссия, лучше в это время отключить сон
function check_agro()
    local lvl = "l03_agroprom"
    local result
    if lvl == tostring(level.name()) then
        if
          db.actor:dont_has_info("agr_help_stalkers_assault_dead") 
          and db.actor:dont_has_info("agr_help_stalkers_defence_dead") 
        then
            result = false
        else
            result = true
        end
    else
        result = true
    end
    return result
end

function check_rostok()
    local lvl = "l06_rostok"
    local result
    if lvl == tostring(level.name()) then
        if 
          db.actor:dont_has_info("bar_rescue_research_done") 
          and db.actor:dont_has_info("bar_rescue_research_fail") 
        then
            result = false
        else
            result = true
        end
    else
        result = true
    end
    return result
end

function check_for_actuality(npc) --aster
    local gulags_fail = { "esc_bridge", "esc_bridge_mil", "bar_zastava_2", "bar_zastava", "agr_nii", "agr2_st_nii" }
    local gulags_maybe = { "mil_freedom" }
    local gulag = xr_gulag.get_npc_gulag(npc)
    if state_mgr.get_state(npc) == "sleep" then
        return false
    end
    for i = 1, #gulags_fail do
        if gulag and string.find(tostring(gulag.name), gulags_fail[i]) then
            return false
        end
    end

    for i = 1, #gulags_maybe do
        if gulag and string.find(tostring(gulag.name), gulags_maybe[i]) then
            if math.random() < 0.33 then
                return false
            else
                return true
            end
        end
    end

    return true
end

function evaluator_sleep:__init(npc, name, storage)
    super(nil, name)
    self.st = storage
    self.st.deep = nil
    self.delay = time_global() + math.random(3000, 12000)
    mon_ai.subscribe_for_events(npc, self)
end

function evaluator_sleep:evaluate()
    local npc = self.object
    if self.delay and self.delay > time_global() then
        return self.res
    elseif not self.st.camp then
        self.st.camp = mon_utils.get_camp(npc)
    end
    if xr_conditions.is_day() then
        self.not_sleep = true
    end
    if not self.st.camp then
        self.not_sleep = true
    end
    local stor = db.storage[npc:id()]
    if stor.active_scheme and stor[stor.active_scheme].no_sleep then
        self.not_sleep = true
    end
    if self.not_sleep then
        self.not_sleep = nil
        self.delay = time_global() + math.random(10000, 60000)
        self.res = false
        return self.res
    end
    if not self.st.deep and math.random() < 0.1 then
        self.st.deep = true
    end
    self.delay = time_global() + math.random(5000, 15000)
    self.res = true
    return self.res
end

function evaluator_sleep:hit_callback(amount, dir, who)
    self.res = false
    self.delay = time_global() + math.random(10000, 30000)
end

class "action_sleep" (action_base)
function action_sleep:__init(npc, action_name, storage)
    super(nil, action_name)
    self.st = storage
    self.dist_rnd_sleep = math.random(1, 4)
    self.dist_rnd_sit = math.random(2, 5)
end

function action_sleep:initialize()
    action_base.initialize(self)
    local npc = self.object
    self.torch = npc:object("device_torch")
    if self.st.camp and level.vertex_position(self.st.camp):distance_to(npc:position()) < self.dist_rnd_sleep then
        self.sleep = true
    else
        self.delay = time_global() + 1000
    end
    self.look_pos = npc:position():add(vector():set(math.random() * 6 - 3, 0, math.random() * 6 - 3))
    npc:set_desired_position()
    npc:set_desired_direction()
    npc:set_detail_path_type(move.curve)
    npc:set_path_type(game_object.level_path)
end

function action_sleep:execute()
    action_base.execute(self)
    local npc = self.object
    if not self.st.camp then
        return
    end
    if self.sleep then
        if self.torch then
            self.torch:enable_attachable_item(false)
        end
        if self.st.deep then
			if state_mgr.get_state(npc) ~= "sleep" then
                state_mgr.set_state(npc, "sleep", nil, nil, { look_position = self.look_pos }, { animation = true })
                xr_sound.set_sound(self.object, nil)
			end
        else
        	if state_mgr.get_state(npc) ~= "sleep_sit" then
                state_mgr.set_state(npc, "sleep_sit", nil, nil, { look_position = self.look_pos }, { animation = true })
                xr_sound.set_sound(npc, "sleep")
            end
        end
    else
        local tg = time_global()
        if self.wfa and self.wfa < tg then
            self.sleep = true
        elseif self.delay < tg then
            local dist = level.vertex_position(self.st.camp):distance_to(npc:position())
            local ddist = self.dist_rnd_sit
            if self.st.deep then
                ddist = self.dist_rnd_sleep
            end
            if dist < ddist then
                self.sleep = true
                return
            end
            state_mgr.set_state(npc, "walk")
            npc:set_dest_level_vertex_id(self.st.camp)
            self.delay = tg + 4000
            if dist < 2 and not self.wfa then
                self.wfa = tg + 20000
            end
        end
    end
end

function action_sleep:finalize()
    action_base.finalize(self)
    self.sleep = nil
    self.delay = nil
    self.st.camp = nil
    self.st.deep = nil
    self.wfa = nil
    xr_sound.set_sound(self.object, nil)
end

evid_sleep = mon_ai.evid_mon_base
actid_sleep = evid_sleep

function add_to_binder(npc, ini, scheme, sect, storage)
    if 
      check_agro() 
      and check_rostok() 
      and check_mili() 
      and check_for_actuality(npc) 
      and not ogse.is_quest_npc(npc) 
    then
        local manager = npc:motivation_action_manager()
        local com = npc:character_community()
        local aaa = true
        local st = db.storage[npc:id()]

        if mon_utils.urodi[npc:name()] then
            aaa = nil
        end

        if 
          string.find(com, "zombied")
          or com == "arena_enemy" 
          or com == "trader" 
          or ogse.is_quest_npc(npc)
        then
            manager:add_evaluator(evid_sleep, property_evaluator_const(false))
            printf("sleep[%s]:", npc:character_name())
            return
        end
        manager:add_evaluator(evid_sleep, evaluator_sleep(npc, "eva_sleep", storage))
        local action = action_sleep(npc, "act_sleep", storage)
        action:add_precondition(world_property(stalker_ids.property_alive, true))
        action:add_precondition(world_property(stalker_ids.property_danger, false))
        action:add_precondition(world_property(stalker_ids.property_enemy, false))
        action:add_precondition(world_property(xr_evaluators_id.sidor_wounded_base, false))
        if rx_reload and rx_reload.evid_reload then
            action:add_precondition(world_property(rx_reload.evid_reload, false))
        end

		if ogsm_hideout then
			action:add_precondition(world_property(ogsm_hideout.property_blowout, false))
			action:add_precondition(world_property(ogsm_hideout.property_hideout_lost, false))
			action:add_precondition(world_property(ogsm_hideout.property_inhide, false))
		end

        action:add_precondition(world_property(evid_sleep, true))
        action:add_effect(world_property(evid_sleep, false))
        manager:add_action(actid_sleep, action)
        action = manager:action(xr_actions_id.alife)
        action:add_precondition(world_property(evid_sleep, false))
    else
        local manager = npc:motivation_action_manager()
        local com = npc:character_community()
        local aaa = false
        if mon_utils.urodi[npc:name()] then
            aaa = nil
        end

        if 
          string.find(com, "zombied") 
          or com == "arena_enemy" 
          or com == "trader" 
          or ogse.is_quest_npc(npc)
        then
            manager:add_evaluator(evid_sleep, property_evaluator_const(false))
            printf("sleep[%s]:", npc:character_name())
            return
        end
        manager:add_evaluator(evid_sleep, evaluator_sleep(npc, "eva_sleep", storage))
        local action = action_sleep(npc, "act_sleep", storage)
        action:add_precondition(world_property(stalker_ids.property_alive, false))
        action:add_precondition(world_property(stalker_ids.property_danger, false))
        action:add_precondition(world_property(stalker_ids.property_enemy, false))
        action:add_precondition(world_property(xr_evaluators_id.sidor_wounded_base, false))

        if rx_reload and rx_reload.evid_reload then
            action:add_precondition(world_property(rx_reload.evid_reload, false))
        end

		if ogsm_hideout then
			action:add_precondition(world_property(ogsm_hideout.property_blowout, false))
			action:add_precondition(world_property(ogsm_hideout.property_hideout_lost, false))
			action:add_precondition(world_property(ogsm_hideout.property_inhide, false))
		end

        action:add_precondition(world_property(evid_sleep, false))
        action:add_effect(world_property(evid_sleep, false))
        manager:add_action(actid_sleep, action)
        action = manager:action(xr_actions_id.alife)
        action:add_precondition(world_property(evid_sleep, false))
    end
end

function set_scheme(npc, ini, scheme, sect)
    local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, sect)
end

function disable_scheme(npc, scheme)
    local st = db.storage[npc:id()][scheme]
    if st then
        st.enabled = false
    end
end
