--/ news_main_data.script /--
--/ OGS Evolution - team /--
--/ ver. 2.0 /--
--/ Использовались некоторые наработки АМК /--
--/ Отдельное спасибо DEXXX-у /--

--/ Основная и вспомогательные функции для новостей /--

local random_news = 1
local t_koef_glob = 1 -- глобальный изменяемый коэффициент изменения диапазона времени выдачи сообщений

local prob7 = news_main_new.show_PDA_error
local prob9 = news_main_new.show_news_vibros
local prob10 = news_main_new.show_news_error
local prob11 = news_main_new.vubros_msg_fake

local meter_time = time_global()

local t_koef_blow = 0.2 -- коэффициент изменения диапазона времени выдачи сообщений при начале Выброса

local ft = {}

--Главная функция

function show_news_main()
    if isIndoor(level.name()) or chk_Vibros() then
        return
    end
    local t_duwn = 60000 -- стандартный диапазон времени выдачи сообщений
    local t_up = 180000
    if has_alife_info("pre_blowout") then
        t_duwn = t_duwn * t_koef_glob * t_koef_blow -- диапазон времени выдачи сообщений при начале Выброса
        t_up = t_up * t_koef_glob * t_koef_blow
    end
    local uptime = time_global()
    local meter = meter_time + math.random(t_duwn, t_up)
    if uptime < meter then
        return
    end
    meter_time = time_global()

    if has_alife_info("pre_blowout2") and not has_alife_info("blowout") then
        ft = {
            prob9,
            prob10
        }
    elseif (has_alife_info("pre_blowout") and not has_alife_info("pre_blowout2")) or has_alife_info("blowout") then
        ft = {
            prob7,
            prob10
        }
    elseif ogse_surge_mgr.actor_in_hideout then
        ft = {
            prob7
        }
    elseif not has_alife_info("pre_blowout") and not has_alife_info("pre_blowout2") and not has_alife_info("blowout") then
        ft = {
            prob11
        }
    end
    ft[math.random(table.getn(ft))]()
end

--"Статус соединения:"
local connect_templates = {
    "Связь восстановлена.",
    "Приём сигнала возобновлён.",
    "Подключение к сети...",
    "Подключение к серверу..."
}

local disconnect_templates = {
    "Нет подключения к серверу.",
    "Связь прервана.",
    "Приём невозможен, связь потеряна.",
    "Сигнал отсутствует."
}

--Вспомагательные функции

function on_connect()
    if random_news == 1 then
        if not chk_Vibros() then
            local con_templ = connect_templates[math.random(table.getn(connect_templates))]
            if con_templ ~= nil then
                db.actor:give_game_news(
                    "%c[255,0,255,0]PDA\\n%c[default]" .. con_templ,
                    "ui\\ui_iconsTotal",
                    Frect():set(498, 235, 83, 47),
                    1000,
                    5000
                )
            end
        end
    end
end

function on_connect_vbs()
    if not isIndoor(level.name()) then
        local con_templ = connect_templates[math.random(table.getn(connect_templates))]
        if con_templ ~= nil then
            db.actor:give_game_news(
                "%c[255,0,255,0]PDA\\n%c[default]" .. con_templ,
                "ui\\ui_iconsTotal",
                Frect():set(498, 235, 83, 47),
                1000,
                5000
            )
        end
    end
end

function on_disconnect()
    if random_news == 1 then
        if not chk_Vibros() then
            local discon_templ = disconnect_templates[math.random(table.getn(disconnect_templates))]
            if discon_templ ~= nil then
                db.actor:give_game_news(
                    "%c[255,255,0,0]PDA\\n%c[default]" .. discon_templ,
                    "ui\\ui_iconsTotal",
                    Frect():set(498, 47, 83, 47),
                    1000,
                    5000
                )
            end
        end
    end
end

function on_disconnect_vbs()
    if random_news == 1 then
        if not isIndoor(level.name()) then
            local discon_templ = disconnect_templates[math.random(table.getn(disconnect_templates))]
            if discon_templ ~= nil then
                db.actor:give_game_news(
                    "%c[255,255,0,0]PDA\\n%c[default]" .. discon_templ,
                    "ui\\ui_iconsTotal",
                    Frect():set(498, 235, 83, 47),
                    1000,
                    5000
                )
            end
        end
    end
end

function chk_Vibros()
    return has_alife_info("no_net_signal")
end

function message_filter()
    local level_name = level.name()
    if db.actor ~= nil and level_name ~= nil then
        if not isIndoor(level_name) then
            on_connect()
        else
            on_disconnect()
        end
    end
end

function game_minutes()
    local gtime = level.get_time_days() * 60 * 24 + level.get_time_hours() * 60 + level.get_time_minutes() --время в игровых минутах
    return gtime
end
