-----------------------------------------------------------------------
--- ogse_critical_hit.script                                       
--- Модуль постэффектов критических попаданий
--- KamikaZze (c) OGS Evolution Team                                      
--- version 1.3 (22/05/2014)                                             
-----------------------------------------------------------------------
local hearthbeat = xr_sound.get_safe_sound_object([[affects\heartbeat]])
local breath_cold = xr_sound.get_safe_sound_object([[actor\breath_cold]])
-----------------------------------------------------------------------
function check_critical(amount, bone_index, who)
	if amount > 0.2 and bone_index and bone_index > 0 and db.actor:alive() then
		local str = " "
		if bone_index < 5 then
			str = " попадание в левую ногу "
			level.add_cam_effector("camera_effects\\hit_back_left.anm", 7041, false, "")
		elseif (bone_index >= 5 and bone_index < 9) then
			str = " попадание в правую ногу "
			level.add_cam_effector("camera_effects\\hit_back_right.anm", 7041, false, "")
		elseif (bone_index >= 9 and bone_index < 11) then
			str = " попадание в туловище "
			level.add_cam_effector("camera_effects\\hit_front.anm", 7041, false, "")
		elseif (bone_index >= 11 and bone_index < 18) then	
			str = " попадание в голову "
			if who:is_stalker() then
				if db.actor.health < 0.3 then
					level.add_pp_effector("blink.ppe", 7042, false)
					if not hearthbeat:playing() then
						hearthbeat:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
					end
					if not breath_cold:playing() then
						breath_cold:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
					end						
				else
					level.add_pp_effector("blink.ppe", 7042, false)
				end
				level.add_cam_effector("camera_effects\\head_shot.anm", 7041, false, "")
			else
				level.add_cam_effector("camera_effects\\hit_front.anm", 7041, false, "")
			end
		elseif (bone_index >= 18 and bone_index < 31) then	
			str = " попадание в левую руку "
			level.add_cam_effector("camera_effects\\hit_front_left.anm", 7041, false, "")
		elseif (bone_index >= 31 and bone_index < 40) then	
			str = " попадание в правую руку "
			level.add_cam_effector("camera_effects\\hit_front_right.anm", 7041, false, "")
			local r = -1
			local need_drop = false
			if (bone_index == 33) then
				-- попадание в предплечье
				r = math.random()*100
				need_drop = (r<50)
			end
			if ((bone_index >= 34) and (bone_index <= 38)) then
				-- по кисти или пальцам
				r = math.random()*100
				need_drop = (r<70)
			end
			if need_drop then
				local active_item = db.actor:active_item()
				if active_item and active_item:section()~= "bolt" and active_item:section() ~= "device_pda" then
					db.actor:drop_item(active_item)
				end			
			end
		end
	end
end
