

-----------------------------------------------------------------------
--- ogse_sleep_mgr.script
--- Менеджер сна и бодрствования ГГ
--- Исходная версия: xStream, Ab@dDon & DEXXX 2007-2008
--- Правки и адаптация: KamikaZze, Dusty79 (c) OGS Evolution Team
--- Версия 2: Malandrinus
--- version 2.1.1 (02/2013)
-----------------------------------------------------------------------
function attach(sm)
	sm:subscribe({signal = "on_spawn", fun = this.on_spawn})
	sm:subscribe({signal = "on_use", fun = this.on_item_use})
	sm:subscribe({signal = "on_update", fun = this.on_update, queued = true}) --KRodin: перевел на низкий приоритет
	sm:subscribe({signal = "on_save", fun = this.on_save})
end
--[[
каждый час сна компенсирует количество часов бодрствования, задаваемое параметром
	sleep_compensation_factor (по умолчанию == 3)
индикация недосыпа начинается с накопленного времени бодрствования, задаваемого параметром
	normal_sleep_deprivation (по умолчанию 16 часов)
негативные эффекты увеличиваются со временем недосыпа и достигают максимума при времени
	critical_sleep_deprivation (по умолчанию 36 часов)
]]
-- TODO: прописать в конфиге
local sleep_compensation_factor = 3.0
local normal_sleep_deprivation = 12.0 * 3600.0 	-- 12 часов
local critical_sleep_deprivation = 18.0 * 3600.0	-- 18 часов
local critical_health = 0.2 -- здоровье, ниже кторого спать нельзя, если состояние ухудшается
-- минимальный интервал между проявлениями недосыпа, соответствует максимальному недосыпу
local min_sleep_deprivation_effector_interval = 15.0 * 1000 -- [ms] 
-- максимальный интервал между проявлениями недосыпа, соответствует минимальному недосыпу
local max_sleep_deprivation_effector_interval = 60.0 * 1000 -- [ms]
local sleep_thresholds = {
	{value = 0.00, color = GetARGB(255, 123, 176, 115)}, -- зелёный
	{value = 0.25, color = GetARGB(255, 170, 190, 90)},  -- салатный
	{value = 0.50, color = GetARGB(255, 176, 147, 114)}, -- жёлтый
	{value = 0.75, color = GetARGB(255, 200, 110, 60)},  -- оранжевый
	{value = 0.90, color = GetARGB(255, 200,  42, 46)},  -- красный
}
local sleep_thresholds_number = #sleep_thresholds

local hud_update_interval = 2000 -- период обновления худа и эффектов недосыпа

local sleeping_now = false
function is_sleep_active()
	return sleeping_now
end

--
local awakening_time -- "time" - когда проснулся последний раз
local last_need_for_sleep -- "float" - накопленная необходимость во сне в секундах !!!на момент окончания последнего сна!!!

local function need_for_sleep() -- реальная текущая потребность во сне
	return game.get_game_time():diffSec(awakening_time) + last_need_for_sleep
end
local depr_range = critical_sleep_deprivation - normal_sleep_deprivation -- чтобы не вычислять всякий раз
function sleep_deprivation_factor()
	return (need_for_sleep() - normal_sleep_deprivation) / depr_range
end
sleep_supressed = false -- действуют ли вещества
-- момент окончания действия веществ
local sleep_suppressed_until_time
local sleep_suppression_limit
local function remained_sleep_suppression_time()
	return sleep_suppressed_until_time:diffSec(game.get_game_time())
end

local actor_need_surprise = false -- подляночка

local mattress_id = {}
local mattress_count = 0
local mattress_processed = 0

-- Для накопления сонливости извне (значение в часах)
function add_need_for_sleep(value)
	last_need_for_sleep = value * 3600 + last_need_for_sleep
end


-------------------------------<| Процесс сна |>-------------------------------
local break_sleep_request = false -- флажок запроса на прерывание сна
function begin_sleep(desired_sleep_time)
	break_sleep_request = false -- если кто-то запрашивал прерывание сна во время бодрствования, то сбрасываем это
	--
	db.actor:stop_talk()
	db.actor:hide_weapon()
	--
	sleeping_now = true
	local urgent_awakening = false
	local start_sleep_time = game.get_game_time()
	-- каждый час сна делим на периоды по три минуты (20 отсчётов на час)
	local sleep_counts = math.ceil(desired_sleep_time * 20)
	local dt_ms = math.ceil(desired_sleep_time * 3600 * 1000 / sleep_counts)
	--local actor_binder = db.actor:binded_object()
	local prev_health = db.actor.health
	--local surge_dt = dsh_cop_weather.get_surge_time() * 3600 * 1000
	cmd( "g_god", "on" )
	for i = 1, sleep_counts do
		-- переводим стрелки
		level.advance_game_time(dt_ms)

		-- проверяем останов по разным событиям
		if break_sleep_request then -- кто-то запросил останов сна
			--log1("break_sleep_request")
			urgent_awakening = true
		end

		-- начался выброс
		if has_alife_info("pre_blowout") then 
			ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_1_text"), nil, 0, 3, "note")
			--log1("surge")
			urgent_awakening = true
		end

		-- начинается выброс
		if dsh_cop_weather.get_weather_mgr():is_surge_in_process() then
			ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_3_text"), nil, 0, 3, "note")
			urgent_awakening = true		
		end

		-- проверяем условие останова сна по состоянию здоровья
		local cur_health = db.actor.health
		local dh = cur_health - prev_health
		--log3("cur_health: %d, %f, dh: %f", i, cur_health, dh)
		if cur_health < critical_health and dh < 0 then -- здоровье снизилось до критической величины и продолжает снижаться
			--log1("trouble")
			ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_4_text"), nil, 0, 3, "note")
			urgent_awakening = true
		end
		prev_health = cur_health
		
		if i >= (sleep_counts / 2) or urgent_awakening then
			cmd( "g_god", "off" )
		end
		
		if urgent_awakening then
			break
		end
	end
	db.actor.power = 1
	sleeping_now = false
	break_sleep_request = false
	sleep_suppression_limit = 1

	-- обновили менеджер погоды
	dsh_cop_weather.get_weather_mgr():force_update()

	-- сколько реально спали
	awakening_time = game.get_game_time()
	local real_sleep_time = math.abs(awakening_time:diffSec(start_sleep_time))
	-- пересчитываем потребность во сне
	last_need_for_sleep = last_need_for_sleep - real_sleep_time * sleep_compensation_factor
	if last_need_for_sleep < 0 then last_need_for_sleep = 0 end
	-- здравствуй монстры
	if actor_need_surprise then 
		actor_need_surprise = false
		surprise()
	end
	-- привет кошмары
	if not urgent_awakening then -- если проснулись своим ходом
		-- выбираем и запускаем ролик сна
		local dream = dream.sleep_video_name_callback()
		log1("!!Trying to start dream ["..tostring(dream).."]")
		if dream == "" then dream = "without_dream" end
		game.start_tutorial(dream)
	end
	-- постпроцессы просыпания
	-- привет похмелье
	level.add_pp_effector("total_recall.ppe", 2008, false)
	level.add_pp_effector ("black_unfade.ppe", 7031, false)
	level.add_cam_effector("camera_effects\\item_use_slow.anm", 7032, false, "")

	db.actor:restore_weapon()
	local snd_obj = xr_sound.get_safe_sound_object([[characters_voice\human_01\stalker\states\breath\breath_2]])
	if snd_obj then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 15.0)
	end
	-- привет мир
	update_sleep_effects(true)
	ogse_signals.get_mgr():call("on_sleep_finished")
end

function break_sleep() -- принудительное прерывание сна
	break_sleep_request = true
end

-------------------<| управление худом, связанное со сном |>-------------------
sleep_level = 0 -- уровень сонливости

local function update_sleep_static(warn_lvl)
	local hud = get_hud()
	hud:RemoveCustomStatic("hud_sleep_static")
	--log("update_sleep_static: warn_lvl=%d\n", warn_lvl)
	if warn_lvl > 0 then
		local st = hud:AddCustomStatic("hud_sleep_static", true):wnd()
		st:SetColor(sleep_thresholds[warn_lvl].color)
	end
end
local last_effector_time = 0
local last_aspect_ratio = 0
function update_sleep_effects(force_update)
	local current_aspect_ratio = device().width / device().height
	--log1("sleep suppresion = "..tostring(remained_sleep_suppression_time()))
	local depr_factor = sleep_deprivation_factor()
	-- сперва обновляем уровень недосыпа и индикатор
	local need_update_static = false
	if sleep_level > 0 and depr_factor < sleep_thresholds[sleep_level].value then
		-- надо скорректировать вниз
		local i = sleep_level
		while i > 0 and depr_factor < sleep_thresholds[i].value do
			i = i - 1
		end
		sleep_level = i
		need_update_static = true
	elseif sleep_level < sleep_thresholds_number and depr_factor >= sleep_thresholds[sleep_level + 1].value then
		-- надо скорректировать вверх
		local i = sleep_level
		while i < sleep_thresholds_number and depr_factor >= sleep_thresholds[i+1].value do
			i = i + 1
		end
		sleep_level = i
		need_update_static = true
		if not db.actor:has_info("encyclopedy_tutorial_sleep") then -- если ещё не видели, то выдаём совет по недосыпу
			db.actor:give_info_portion("encyclopedy_tutorial_sleep")
			game.start_tutorial("part_17_sleep")	
		end
	end
	if sleep_supressed and remained_sleep_suppression_time() < 0 then
		-- если закончился эффект веществ
		sleep_supressed = false
		need_update_static = true
	end
	-- при необходимости обновляем индикатор сна
	if force_update or need_update_static or current_aspect_ratio ~= last_aspect_ratio then
		last_aspect_ratio = current_aspect_ratio
		update_sleep_static(sleep_level)
	end
	-- при необходимости вызываем визуальные эффекты недосыпа
	if sleep_level > 0 then
		local depr_factor_clamped = math.min(depr_factor, 1.0)
		local sleep_effector_interval = 
			max_sleep_deprivation_effector_interval - 
			(max_sleep_deprivation_effector_interval - min_sleep_deprivation_effector_interval) * depr_factor_clamped
		local tg = time_global()
		--log1("int="..((last_effector_time + sleep_effector_interval - tg)/1000).." suppr="..remained_sleep_suppression_time())
		if tg > last_effector_time + sleep_effector_interval and remained_sleep_suppression_time() < 0 then
			last_effector_time = tg
			level.add_pp_effector("blur.ppe", 999, false) -- установить эффекты недосыпа
		end
	end
end

-- Update матраса (вешаем колбек, если ещё не повесили)
function mattress_update(obj)
	if mattress_count ~= mattress_processed then
		for kk, vv in pairs(mattress_id) do
			if vv[1] == obj:id() and vv[2] == false then
				vv[2] = true
				obj:set_callback(callback.use_object, this.use_matras)
				obj:set_tip_text("tip_sleep")
				mattress_processed = mattress_processed + 1
			end
		end
	end
end

-- Отлавливаем спавн матрасов
function mattress_spawn(obj)
	local id = obj:id()
	mattress_count = mattress_count + 1
	local m = {id, false}
	table.insert(mattress_id, m)
	
	local sobj = alife():object(id)
	local ini = sobj:spawn_ini()
	if ini and ini:section_exist( "sr_mapspot" ) then
		local location = get_string("sr_mapspot", "location", nil, ini)
		level_tasks.add_location_by_id(id, location, get_string("sr_mapspot", "hint", nil, ini))
	end
end

-- Первый запуск
function start_sleep()
	ogse.save_var("first_run_sleep", true)
end

function on_update()
	if not sleeping_now then  -- если не спит
		ogse_signals.get_mgr():reschedule(hud_update_interval)
		update_sleep_effects()
	end
	
	if not (db.actor and db.actor:alive()) then return end
	if not ogse.load_var("first_run_sleep", false) then start_sleep() end
end

function on_spawn()
	-- событие on_spawn здесь используется для загрузки значений
	awakening_time = ogse.load_var("sleep_mgr__awakening_time", game.get_game_time(), "time")
	last_need_for_sleep = ogse.load_var("sleep_mgr__last_need_for_sleep", 0.0, "float")
	sleep_suppressed_until_time = ogse.load_var("sleep_mgr__sleep_suppressed_until_time", game.get_game_time(), "time")
	sleep_suppression_limit = ogse.load_var("sleep_mgr__sleep_suppression_limit", 1)
	
	-- time2string(time)
	-- log1("!!DEBUG SLEEP_LOAD AWK ["..time2string(awakening_time).."] NEED ["..tostring(last_need_for_sleep).."] SUPP ["..time2string(sleep_suppressed_until_time).."]")
	
	sleep_supressed = remained_sleep_suppression_time() > 0
	update_sleep_effects(true)
end

function on_save()

	-- log1("!!DEBUG SLEEP_SAVE AWK ["..time2string(awakening_time).."] NEED ["..tostring(last_need_for_sleep).."] SUPP ["..time2string(sleep_suppressed_until_time).."]")

	ogse.save_var("sleep_mgr__awakening_time", awakening_time, "time")
	ogse.save_var("sleep_mgr__last_need_for_sleep", last_need_for_sleep, "float")
	ogse.save_var("sleep_mgr__sleep_suppressed_until_time", sleep_suppressed_until_time, "time")
	ogse.save_var("sleep_mgr__sleep_suppression_limit", sleep_suppression_limit)
end

-- Проверки использования вещи, работающей со сном 
function on_item_use(obj)
	--if obj == nil or alife():object(obj:id()) == nil then return end
	local section = obj:section()
	
	if section == "matras" then -- если это матрас
		use_matras() -- пытаемся спать
		return true -- матрас больше никому не надо использовать
	elseif use_stimulant(section) then -- проверяем, не приняли ли мы вещества
		return
	end
end

function use_stimulant(section)
	local additional_awake_time = get_float(section, "sleep_suppression_time")
	local additional_soporific = get_float(section, "sleep_soporific")
	
	if additional_soporific then
		add_need_for_sleep(additional_soporific)
		update_sleep_effects(true)
	end
	if additional_awake_time then -- вещества содержат в секции параметр влияния на сон
		-- штраф за использование
		if sleep_level > 0 then		
			sleep_suppression_limit = sleep_suppression_limit + additional_awake_time
	
			if sleep_suppression_limit > 1 then
				additional_awake_time = additional_awake_time / sleep_suppression_limit
			end
		end
	
		local time_sec = additional_awake_time * 3600
		if remained_sleep_suppression_time() < time_sec then
			sleep_suppressed_until_time = game.CTime(game.get_game_time() + seconds2ctime(time_sec))
			sleep_supressed = true
		end
		update_sleep_effects(true)
		return true
	end
	return false
end

local non_sleep_locations = {
	["l08u_brainlab"] = true,
	["l10u_bunker"] = true,
	["l04u_labx18"] = true,
	["l12u_control_monolith"] = true,
	["l12u_sarcofag"] = true
}

function use_matras()
	local is_enemy_around = false
	local friends_count = 0
	for id in pairs(db.creature) do
		if id ~= nil then
			local obj = level.object_by_id(id)
			if 
			  obj 
			  and obj:is_custom_monster() 
			  and not string.find(obj:section(), "rat_") 
			  and obj:alive() 
			then
				local is_stalker = obj:is_stalker()
				local dist = obj:position():distance_to(db.actor:position())
				local is_enemy_to_actor = obj:relation(db.actor) == game_object.enemy
				if ((is_stalker and is_enemy_to_actor) or obj:is_monster()) and (dist < 20 or obj:see(db.actor)) then
					is_enemy_around = true
					break
				elseif is_stalker and dist < 30 then
					friends_count = friends_count + 1
				end
			end
		end 
	end

	if has_alife_info("pre_blowout") then 
		ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_1_text"), nil, 0, 3, "note")
	elseif is_enemy_around then
		ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_5_text"), nil, 0, 3, "note")
	elseif (level.rain_factor() > 0 and level.rain_hemi() > 0.1 and not isIndoor(level.name())) then	
		ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_7_text"), nil, 0, 3, "note")
	elseif non_sleep_locations[level.name()] then	
		ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_8_text"), nil, 0, 3, "note")
	elseif remained_sleep_suppression_time() > 0 then
		ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_9_text"), nil, 0, 3, "note")
	elseif sleep_level == 0 then
		ogse.send_tip(game.translate_string("ogse_sleep_mgr_warn_12_text"), nil, 0, 3, "note")
	else
		-- закрываем инвентарь
		local wnd = level.main_input_receiver()
		if wnd then
			wnd:GetHolder():start_stop_menu(wnd, true)
		end
		-- открываем диалог сна
		level.start_stop_menu(ui_sleep.sleep(),true)
		-- запоминаем, делать ли подлянку
		actor_need_surprise = (friends_count == 0 and math.random() < 0.8)
	end
end

--Пусть переносятся существующие мутанты на локации, от одного до
--четырех. Будет выбрана случайная позиция на расстоянии от 10 до 25
--метров, не попадающая в укрытие.
function surprise()
  local monsters = {}
  for id, is_npc in pairs( db.creature ) do
    if not is_npc then
      local obj = level.object_by_id( id )
      if
        obj and obj:alive() and obj:relation( db.actor ) == game_object.enemy
        and not string.find( obj:section(), "rat_", 1, true )
      then
        table.insert( monsters, obj )
      end
    end
  end
  local actor_pos = db.actor:position()
  table.sort(
    monsters,
    function( a, b )
      return a:position():distance_to( actor_pos ) < b:position():distance_to( actor_pos )
    end
  )
  local lname = level.name()
  local lvx   = level.vertex_count() - 1
  local lvids = {}
  for new_lv = 1, lvx do
    local pos  = level.vertex_position( new_lv )
    local dist = actor_pos:distance_to( pos )
    if
      dist > 5 and dist < 25
      and not ogse_anomaly.bad_zone( pos )
    then
      table.insert( lvids, new_lv )
    end
  end
  local need_cnt = math.min( #monsters, 4 )
  if #lvids > need_cnt then
    for i = 1, need_cnt do
      local obj  = monsters[ i ]
      local sobj = alife():object( obj:id() )
      if sobj then
        ogse.reset_npc_logic( obj )
        xr_gulag.resetJob( obj )
        smart_terrain.unregister_npc( sobj )
        sobj:brain():can_choose_alife_tasks( false )
        local lv  = lvids[ math.random( #lvids ) ]
        local pos = level.vertex_position( lv )
        obj:set_custom_panic_threshold( 0 )
        obj:set_fov( 360 )
        alife():teleport_object(sobj.id, pos, lv, db.actor:game_vertex_id())
      end
    end
  end
end
