

function init(obj)
	local new_binder = anomaly_binder(obj)
	obj:bind_object(new_binder)
end

---------------------------------------------------------------------------------------------
class "anomaly_binder" (object_binder)
function anomaly_binder:__init(obj) super(obj)
	self.sm = ogse_signals.get_mgr()
end


function anomaly_binder:net_spawn(data)
	if not object_binder.net_spawn( self, data ) then
		return false
	end

	local id = self.object:id()
	local sobj = alife():object( id )
	if not sobj then return true end
	--
	local status = ogse_anomaly.get_anomaly_mode( sobj )
	if status == "anom_off" then
		--log3("~~[%s] Disabling anomaly: [%s]", script_name(), self.object:name())
		dsh.exec_on_update(function()
			self.object:disable_anomaly()
		end)
		return true --думаю, больше тут делать нечего.
	end

	self.sm:call( "on_anomaly_spawn", self.object, self )
	return true
end

function anomaly_binder:net_destroy()
	self.sm:call( "on_anomaly_net_destroy", self.object, self )

	object_binder.net_destroy( self )
end
