--[[----------------------------------------------------------------------
-|ogsr_quick_slots.script
-|Creator I AM DEAD, xrKrodin
-|Update xrKrodin
-|Last Update: Muvbed 12.07.2025 
------------------------------------------------------------------------]]

local slots_wnd_storage = {}
local slot_focus = false
local slots_pos = {
	{ 554, 692, 34.4, 46 },
	{ 604, 692, 34.4, 46 },
	{ 654, 692, 34.4, 46 },
	{ 704, 692, 34.4, 46 }
}
local slots_pos_min = {
	{ 568, 692, 46, 46 },
	{ 635, 692, 46, 46 },
	{ 702, 692, 46, 46 },
	{ 769, 692, 46, 46 }
}

local item_in_slot = {
	function() return ogse.load_var( "item_in_slot_1", "fake_item" ) end,
	function() return ogse.load_var( "item_in_slot_2", "fake_item" ) end,
	function() return ogse.load_var( "item_in_slot_3", "fake_item" ) end,
	function() return ogse.load_var( "item_in_slot_4", "fake_item" ) end
}

function update_hud(force)
	local hud = get_hud()

	if not hud then return end

	for i = 1, 4 do   
		local item_section = item_in_slot[i]()
		
		if item_section ~= "fake_item" then
			if force then
				if hud:GetCustomStatic("quick_slot_"..i) then
					hud:RemoveCustomStatic("quick_slot_"..i)
					hud:AddCustomStatic("quick_slot_"..i, true)		
				end
				if hud:GetCustomStatic("quick_slot_key_"..i) then
					hud:RemoveCustomStatic("quick_slot_key_"..i)
					hud:AddCustomStatic("quick_slot_key_"..i, true)	
				end
			end
			
			local quick_slot_static = hud:GetCustomStatic("quick_slot_"..i) or hud:AddCustomStatic("quick_slot_"..i, true)

			CIconParams( item_section ):set_shader( quick_slot_static:wnd() )
			quick_slot_static:wnd():SetColor( db.actor:object(item_section) and GetARGB(255,255,255,255) or GetARGB(128,255,255,255) )

			local quick_slot_key_static = hud:GetCustomStatic("quick_slot_key_"..i) or hud:AddCustomStatic("quick_slot_key_"..i, true)
			local dik = bind_to_dik(key_bindings["kQUICK_SLOT_"..i])
			local key_name = dik and dik_to_keyname(dik) or false

			quick_slot_key_static:wnd():SetText(key_name and key_name:sub(2) or "")
		else
			hud:RemoveCustomStatic("quick_slot_"..i)
			hud:RemoveCustomStatic("quick_slot_key_"..i)
		end
	end
end

local function remove_from_slot(slot)
	ogse.save_var("item_in_slot_"..slot, "fake_item")
	ogse.save_var("id_in_slot_"..slot, -1)
	update_hud()
	
	if 
		slots_wnd_storage 
		and slots_wnd_storage[slot] 
		and slots_wnd_storage[slot].slot 
	then
		CIconParams( "fake_item" ):set_shader( slots_wnd_storage[slot].slot )
	end
end

class "CUI_InvButton" ( CUIScriptWnd )
function CUI_InvButton:__init( slot_num ) super()
	local id = "slot_"..slot_num
	self.slot = CUIButton()
	self.slot:SetWindowName("CUI_InvButton_slot_"..slot_num)
	self.slot:SetAutoDelete( true )
	CIconParams( item_in_slot[slot_num]() ):set_shader( self.slot )
	
	local AR = res_type.get_AR()

    if AR == 2 then
		self.slot:Init( unpack(slots_pos[slot_num]) )
	elseif AR == 1 then
		self.slot:Init( unpack(slots_pos_min[slot_num]) )
	end

	
	self:Register( self.slot, id )

	self:SetAutoDelete(true)
	self:Show(true)

	self:AddCallback(id, ui_events.STATIC_FOCUS_RECEIVED, function(n) slot_focus = n end, slot_num)
	self:AddCallback(id, ui_events.STATIC_FOCUS_LOST, function() slot_focus = false end)
	self:AddCallback(id, ui_events.BUTTON_CLICKED, function() remove_from_slot(slot_num) end)
end
function CUI_InvButton:__finalize()
	--log1("--delete CUI_InvButton")
end

local function on_drag_drop(obj)
	local section = obj:section()
	local id = obj:id()
	
	local quickslot = get_string( section, "eat_portions_num" )
	local cell_width = tonumber(get_string( section, "inv_grid_width" )) or 0
	local cell_height = tonumber(get_string( section, "inv_grid_height" )) or 0

	if 
		not quickslot 
		or not slot_focus 
		or cell_width ~= 1
		or cell_height ~= 1
	then 
		return 
	end
	
	for i = 4, 1, -1 do
		local id_in_slot = ogse.load_var( "id_in_slot_"..i, -1 )
		
		if id_in_slot == id then
			return
		end
	end

	ogse.save_var("item_in_slot_"..slot_focus, section)
	ogse.save_var("id_in_slot_"..slot_focus, id)
	update_hud()

	CIconParams( section ):set_shader( slots_wnd_storage[slot_focus].slot )

	local snd_obj = xr_sound.get_safe_sound_object([[interface\inv_slot]])
	snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 0.7)
end

function buff_saving_slots(id)
	for i = 4, 1, -1 do
		local item = item_in_slot[i]()

		ogse.save_var("item_in_buff_"..id.."_slot_"..i, item)
	end
end

function restore_saving_slots(ruck_id)	
	local slots_remain = 4
	local slots_step = -1

	dsh.timeout(1, function() 
		db.actor:iterate_inventory(function (_, item)
			local item_section = item:section()
			
			local quickslot = get_string( item_section, "eat_portions_num" )
			local cell_width = tonumber(get_string( item_section, "inv_grid_width" )) or 0
			local cell_height = tonumber(get_string( item_section, "inv_grid_height" )) or 0
			
			if 
				quickslot 
				and cell_width == 1
				and cell_height == 1
			then 
				for i = slots_remain, 1, slots_step do
					local item_in_buff = ogse.load_var( "item_in_buff_"..ruck_id.."_slot_"..i, "fake_item" )
					
					if item_in_buff == item_section then
						local item_id = item:id()
						
						ogse.save_var("item_in_slot_"..i, item_section)
						ogse.save_var("id_in_slot_"..i, item_id)
						update_hud()
						
						slots_remain = slots_remain + slots_step 
					end
				end
			end
		end)
	end)
end

local function on_item_drop(item)
	for i = 4, 1, -1 do
		local current_id = ogse.load_var("id_in_slot_"..i, -1)
		
		if current_id == item:id() then
			remove_from_slot(i)
		end
	end
end

local function eat_qs_item(slot)
	local section_in_slot = item_in_slot[slot]()

	if section_in_slot and dynamic_hud.check_item_abble(section_in_slot) then
		local id_in_slot = ogse.load_var("id_in_slot_"..slot, -1)
		local matched_item = nil
		
		db.actor:iterate_inventory(function (_, item)
			if item:id() == id_in_slot then
				matched_item = item
			end
		end)
		
		if matched_item then
			db.actor:eat(matched_item)
			remove_from_slot(slot)
			
			return true
		end
	end				
end

local function inventory_open()
	local inv_wnd = level.get_inventory_wnd()

	for i = 1, 4 do   
		slots_wnd_storage[i] = CUI_InvButton( i )
		inv_wnd:AttachChild( slots_wnd_storage[i].slot )
	end
end

local function inventory_hide()
	local inv_wnd = level.get_inventory_wnd()

	for i = 1, 4 do   
		inv_wnd:DetachChild( slots_wnd_storage[i].slot )
	end

	slots_wnd_storage = {}
end

local binds_table = {
	[key_bindings.kQUICK_SLOT_1] = function() return eat_qs_item(1) end,
	[key_bindings.kQUICK_SLOT_2] = function() return eat_qs_item(2) end,
	[key_bindings.kQUICK_SLOT_3] = function() return eat_qs_item(3) end,
	[key_bindings.kQUICK_SLOT_4] = function() return eat_qs_item(4) end,
}

local function on_key_down(key, bind)
	if level.main_input_receiver() or not db.actor:alive() or device().precache_frame > 1 then 
		return 
	end

	local fun = binds_table[bind]

	if fun then
		return fun()
	end
end


function attach(sm)
	sm:subscribe({ signal = "on_inventory_open", fun = inventory_open }) 
	sm:subscribe({ signal = "on_inventory_hide", fun = inventory_hide }) 
	sm:subscribe({ signal = "on_fake_drag_drop", fun = on_drag_drop   })
	sm:subscribe({ signal = "on_drop",           fun = on_item_drop   })
	sm:subscribe({ signal = "on_key_down",	     fun = on_key_down    })
	sm:subscribe({ signal = "on_spawn",	     	 fun = update_hud     })
end
