-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_first_update",        fun = this.on_first_update              })
  sm:subscribe({ signal = "on_info",      			fun = this.dof_toggle                   })
end

function dof_toggle(npc, info_id)
  	if 
      info_id == "ui_inventory" 
      or info_id == "ui_car_body" 
      or info_id == "ui_talk"
      or info_id == "ui_trade"
	then
		dsh.timeout(51, function()
			set_dof_params( 1.0, 1.0, 1.0, 1.1 )
  		end)
	elseif 
      info_id == "ui_inventory_hide" 
      or info_id == "ui_car_body_hide" 
      or info_id == "ui_talk_hide"
      or info_id == "ui_trade_hide"
	then
		dsh.timeout(51, function()
			if not db.actor:is_talking() then
				set_dof_params( 0.0, 0.0, 0.0, 0.0 )
			end
		end)
	end
end

function on_first_update()
  set_dof_params( 0.0, 0.0, 0.0, 0.0 )
end
