local ANIMS_ENABLED = true

-- удаление мусора
local summ_trash = 10 -- общее допустимое число бесхозного мусора на всех локаци¤х.
local dist_to_trash = 30 -- рассто¤ние от игрока, свыше которого считаетс¤ мусор.
local tabl_trash = {}
local ini = system_ini()

local cfg = {
	["eat_health"]		= function(v) db.actor.health = v end,
	["eat_power"]		= function(v) db.actor.power = v end,
	["eat_radiation"]	= function(v) db.actor.radiation = v end,
	["eat_satiety"]		= function(v) db.actor.satiety = v end,
	["eat_thirst"]		= function(v) db.actor.thirst = v end,
	["eat_alcohol"]		= function(v) db.actor.alcohol = v end,
	["eat_psy_health"]	= function(v) db.actor.psy_health = v end,
	["wounds_heal_perc"]= function(v) db.actor:heal_wounds( v ) end,
}

local function apply_item( sect )
	if string.find(sect, "^medkit") then
		if ogse_healing.slow_medicine then
			ogse_healing.use_medkit(sect)
			return
		end
	end		

	for line, func in pairs( cfg ) do
		local val = get_float( sect, line )
		if val ~= 0	then
			func(val)
		end
	end

	if sect == "voda" then
		ogse_healing.use_voda(sect)
	end
end

local function respawn_item(item)
	item:zero_effects()

	local item_cond = item:condition()
	local new_sobj = alife():create( 
		item:section(), 
		db.actor:position(), 
		db.actor:level_vertex_id(), 
		db.actor:game_vertex_id(), 
		db.actor:id() 
	)
	
	level.client_spawn_manager():add( new_sobj.id, -1, function(id, obj)
		obj:set_condition( item_cond )
	end )
end

local snd_in_use = false

local function play_use_sound(sect, snd_name)
	local snd = snd_name or get_string( sect, "snd_use" )
	if snd then
		if snd_in_use then
			snd_in_use:stop()
		end
		snd_in_use = sound_object( snd )
		snd_in_use:play( db.actor, 0, sound_object.s2d )
	end
end

local function play_item_use(item)
    local anim = "anm_use"
    local item_hud = get_string(item, "hud")
    local cam_effect = get_string(item, "cam_effect")
    local used_time = get_u32(item, "item_used_timing")
	local trash_time = get_u32(item, "item_trash_timing")
    local snd = get_string(item, "snd_use_anm")
    local outfit = db.actor:item_in_slot(6)

    if outfit then
        if string.find(outfit:section(), "exo") and ( string.find(item, "^medkit") or item == "antirad" ) then
            item_hud = get_string(item, "hud_exo")
            used_time = get_u32(item, "item_used_timing_exo")
            snd = get_string(item, "snd_use_exo_anm")
            cam_effect = get_string(item, "cam_effect_exo")
        elseif (outfit:section() == "scientific_outfit" or outfit:section() == "ecolog_outfit" or outfit:section() == "protection_outfit") and string.find(item, "^medkit") then
            anim = "anm_use_alt"
        end
    end

	if level.get_inventory_wnd():IsShown() then
		level.start_stop_menu(level.get_inventory_wnd(), true)
	elseif level.get_car_body_wnd():IsShown() then
		level.start_stop_menu(level.get_car_body_wnd(), true)			
	end

    level.only_allow_movekeys(true)
    level.set_actor_allow_ladder(false)

	local act_it = db.actor:active_item()
	local act_it_slot = act_it and get_u32(act_it:section(), "slot", false) or false
	local is_det_active = get_actor_obj():IsDetectorActive()

	local prev_active_slot = db.actor:active_slot()
	db.actor:activate_slot(255)

	dsh.wait_condition(function() return not db.actor:active_item() end, function()
		snd_in_use = sound_object(snd)
		snd_in_use:play(db.actor, 0, sound_object.s2d)

		local anm_start = time_global()
		local anm_duration = game.play_hud_motion(2, item_hud, anim, true, 1, true)
		level.add_cam_effector(cam_effect, 7538, false, "", 0, false)

		local hud = get_hud()
		local anim_hud = hud:GetCustomStatic("static_anim") or hud:AddCustomStatic("static_anim", true)
		local anim_hud_wnd = anim_hud:wnd()
		local xml = CScriptXmlInit()
		xml:ParseFile("ui_custom_msgs.xml")
		anim_hud_wnd:SetText(game.translate_string("st_item_used")..": "..game.translate_string(news_manager.get_inv_name(item)))		
		local anim_progress = xml:InitProgressBar("static_anim:anim_progress", anim_hud_wnd)
		anim_progress:Show(true)
		
		local trash_section = get_string_wq(item,"trash_object",nil)
		local dont_drop_trash_in_exo = get_string_wq(item,"dont_drop_trash_in_exo",nil)
		if trash_section then
			if outfit and string.find(outfit:section(), "exo") then
				if not dont_drop_trash_in_exo then				
					dsh.timeout(trash_time, function()
						spawn_trash(trash_section)
					end)
				end
			else 
				dsh.timeout(trash_time, function()
					spawn_trash(trash_section)
				end)
			end
		end

		dsh.timeout(math.min(used_time, anm_duration), function()
			apply_item(item)
		end)

		local tmr = dsh.timeout(anm_duration, function()
			level.only_allow_movekeys(false)
			level.set_actor_allow_ladder(true)

			-- когда в руке длинное оружие и детектор одновременно, если использовать анимированный предмет (аптечку например),
			-- и во время применения переключаться на бег к примеру и ещё в некоторых случаях,
			-- детектор не возвращается и левая рука исчезает вообще, чтоб появилась надо убрать детектор из слота и вернуть обратно.
			if is_det_active and act_it and not (act_it_slot == 0 or act_it_slot == 1 or act_it_slot == 5) then
				local det = db.actor:item_in_slot(8)
				if det then
					db.actor:move_to_ruck(det)
					db.actor:move_to_slot(det, true)
				end
			end

			db.actor:activate_slot(prev_active_slot)

			hud:RemoveCustomStatic("static_anim")
			anim_progress = false
		end)

		dsh.wait_condition(function() return not tmr.slot_desc end, function() end, function()
			if anim_progress then
				anim_progress:SetProgressPos( 100 - 100 * ( ((anm_start + anm_duration) - time_global()) / anm_duration ) )
			end
		end)
	end)
end

local function use_item_without_anim(obj, sobj, sect)
	if ogse_healing.on_before_use_item(obj, sobj) then
		play_use_sound(sect)
	else
		play_use_sound(sect)
	end
end

local function on_actor_before_use( obj, sobj )
    local sect = obj:section()

    if ANIMS_ENABLED then
    	if dynamic_hud.check_item_able(obj:section()) then
    		if not get_string(sect, "snd_use_anm") then --лучше всего отсекать не анимационные предметы по наличию этой строки, потому что строка hud есть у многих предметов без худа почему то.
				return
			elseif db.actor:has_info("ui_talk") then -- Нужно для того что бы диалог не обрывался если мы решили выпить\перекусить с собеседником
				use_item_without_anim(obj, sobj, sect)
			elseif ogsr_actor_animation.allow_animation() then
	            if string.find(sect, "^medkit") then
	                if not ogse_healing.can_use_medkit() then
	                    respawn_item(obj)
	                    return
	                end
	            end
	
	            obj:zero_effects()
	
	            play_item_use(sect)
			else
				respawn_item(obj) --Это важно!
	        end
	    else
	    	respawn_item(obj) --Это важно!
    	end
    else
		use_item_without_anim(obj, sobj, sect)
    end
end

local function animation_off()
	level.only_allow_movekeys(false)
	level.set_actor_allow_ladder(true)
end

function spawn_trash(obj)			
	local pos = device().cam_pos
	local throw_offset_x = -0.1
	local throw_offset_y = 0.2
	local throw_offset_z = 0
	
	if ini:line_exist( obj, "throw_offset_x") then
		throw_offset_x = ini:r_float( obj, "throw_offset_x")
	end
	if ini:line_exist( obj, "throw_offset_y") then
		throw_offset_y = ini:r_float( obj, "throw_offset_y")
	end
	if ini:line_exist( obj, "throw_offset_z") then
		throw_offset_z = ini:r_float( obj, "throw_offset_z")
	end
	
	pos = pos:add(device().cam_top:mul(throw_offset_y))
	pos = pos:add(device().cam_dir:mul(throw_offset_x))	
	pos = pos:add(device().cam_right:mul(throw_offset_z))

	alife():create(obj, pos, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end	

function init_trash(obj)
   local new_binder = gwr_trash_binder(obj)
   obj:bind_object(new_binder)
end

class "gwr_trash_binder" (object_binder)
function gwr_trash_binder:__init(obj) super(obj)
	self.throw_dir = ini:r_string(obj:section(), "throw_dir")

	if ini:line_exist(obj:section(), "remove_time") then
		self.timing = ini:r_s32(obj:section(), "remove_time")
	else
		self.timing = 30	
	end
	
	if ini:line_exist(obj:section(), "throw_impulse_z") then
		self.impulse = ini:r_float(obj:section(), "throw_impulse_z")
	else
		self.impulse = 5
	end
	
	if ini:line_exist(obj:section(), "throw_impulse_y") then
		self.impulse_y = ini:r_float(obj:section(), "throw_impulse_y")
	else
		self.impulse_y = 0.05
	end	

	if db.actor~=nil then
		--надо пнуть объект в сторону от актора

		local dir=GetThrowDir(self.throw_dir)
		dir.y = self.impulse_y
		
		local h = hit()			
		h.direction = dir
		h.draftsman = db.actor
		h.impulse = self.impulse
		h.power = 0
		h.type = 2
		self.object:hit(h)
	end
end

function GetThrowDir(dir)
	if dir=="left" then 
		local v = device().cam_right
		v.x = (-1) * v.x
		v.y = (-1) * v.y
		v.z = (-1) * v.z
		return v
	elseif dir=="right" then
		local v = device().cam_right
		return v
	elseif dir=="forward" then
		local v = device().cam_dir
		return v
	elseif dir=="back" then
		local v = device().cam_dir
		v.x = (-1) * v.x
		v.z = (-1) * v.z
		return v
	end
end

function attach( sm )
	sm:subscribe({ signal = "on_actor_before_use", fun = on_actor_before_use })
	sm:subscribe({ signal = "on_first_update",     fun = animation_off       })
end
