-----------------------------------------------------
-- Сбрасываемый рюкзак / Рюкзак для создания тайника
-- Автор Muvbed, благодарность XiaNi и naxac
-- 24/02/2024
-----------------------------------------------------

function attach( sm )
  sm:subscribe({ signal = "on_item_to_ruck",      	fun = this.item_to_backpack         })
  sm:subscribe({ signal = "on_use",          		fun = this.use_item                 })
  sm:subscribe({ signal = "on_use_box",				fun = this.use_ruck                 })
  sm:subscribe({ signal = "on_update",        		fun = this.update              		})
end


local mark_for_drop = {}
local mark_for_belt = {}
local inv_ruck_id = nil
local current_ruck = nil

function on_key()
	if ogse.load_var("ruck_dropped", 0) == 0 then
		local ruck = alife():create("active_ruck", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id()) 	
		alife():use_ai_locations(ruck, false)
		local id = ruck.id
		level.add_call(
			function()
				if level.object_by_id(id) then 
					return true
				end
			end,
			function()
	            local box = level.object_by_id(id)
				
				level.map_add_object_spot_ser(id, "treasure", "%c[255,238,155,23]Мой рюкзак") 
				news_manager.send_tip(db.actor, "Рюкзак сброшен", nil, nil, 5000) 
				ogse.save_var("ruck_dropped", 1)
				ogsr_quick_slots.buff_saving_slots(id)
				
				local cnt = db.actor:object_count()
		
				for i = 0, cnt - 1 do
					local obj = db.actor:object(i)

					if obj then
						local sect = obj:section()

						if db.actor:is_in_ruck(obj) and 
							not (
								(sys_ini:line_exist(sect, "quest_item") and sys_ini:r_bool(sect, "quest_item")) or 
								death_manager.remove_this_shit_immediately[sect]
							) 
						then
							db.actor:transfer_item(obj, box)
						end
					end
				end
			end
		)
	end
end

function item_to_backpack(obj)
	if ogse.load_var("ruck_dropped", 0) == 1 then
		local sect = obj:section()
		local id = obj:id()

		if 	
			not (sys_ini:line_exist(sect, "quest_item") and sys_ini:r_bool(sect, "quest_item")) and
			not death_manager.remove_this_shit_immediately[sect] 
		then
			if sect == "inv_ruck" then
				local sobj = alife():object(id)

				if sobj then
					alife():release(sobj, true)
					ogse.delete_var("ruck_dropped")
				end
			else
				if sys_ini:line_exist(sect, "belt") and sys_ini:r_bool(sect, "belt") then
					local current_outfit = db.actor:get_current_outfit()
					local current_outfit_sect = current_outfit and current_outfit:section() or "outfit_base"
					local artefact_count = sys_ini:r_u32(current_outfit_sect, "artefact_count")
					local items_count = db.actor:belt_count()
					local locked_cells = 0
					
					for i = 0, items_count - 1 do
						local belt_item = db.actor:item_on_belt(i)
						local belt_item_sect = belt_item:section()
						
						locked_cells = locked_cells + sys_ini:r_u32(belt_item_sect, "inv_grid_width")
					end
					
					for key, val in pairs(db.inv_items) do
						if key == id then
							table.insert(mark_for_drop, id)
							return
						end
					end
					
					if artefact_count - locked_cells >= sys_ini:r_u32(sect, "inv_grid_width") then
						table.insert(mark_for_belt, id)
					else
						table.insert(mark_for_drop, id)
					end
				else
					table.insert(mark_for_drop, id)
				end
			end
		end
	end
end

function take_ruck()
	if current_ruck and current_ruck:id() then
		local id = current_ruck:id()
		local sobj = alife():object(id)
		
		if sobj then
			if not current_ruck:is_inv_box_empty() then
				local cnt = current_ruck:inv_box_count()

				for i = 0, cnt - 1 do
					local item = current_ruck:object_from_inv_box(i)
			
					if item then
						local sect = item:section()
			
						current_ruck:transfer_item(item, db.actor)
					end
				end
			end
			
			if ogse.load_var("ruck_dropped", 0) == 1 then
				ogse.delete_var("ruck_dropped")
				ogsr_quick_slots.restore_saving_slots(id)
			else
				alife():create("inv_ruck", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
			end
			
			level.start_stop_menu(level.main_input_receiver(), true)
			level.map_remove_object_spot(id, "treasure")
			alife():release(sobj, true)
		end
	end
end

function use_item(obj)
    if obj:section() == "inv_ruck" then
    	inv_ruck_id = obj:id()
    end
end

function use_ruck(obj)
	local sect = obj:section()
	
	if sect == "active_ruck" then
		current_ruck = obj
		ogse.save_var("ruck_used", 1)
	elseif ogse.load_var("ruck_used", 0) == 1 then
		current_ruck = nil
		ogse.delete_var("ruck_used")
	end
end

function update()
	ogse_signals.get_mgr():reschedule(100)

	if table.getn(mark_for_belt) > 0 then
		local cnt = db.actor:object_count()
	
		for i = 0, cnt - 1 do
			local obj = db.actor:object(i)
	
			if obj then
				local id = obj:id()
	
				for _, s in ipairs( mark_for_belt ) do
					if id == s then
						db.actor:move_to_belt(obj)
						table.remove(mark_for_belt, _)
					end
			    end
			end
		end
	end

	if table.getn(mark_for_drop) > 0 then
		local cnt = db.actor:object_count()
	
		for i = 0, cnt - 1 do
			local obj = db.actor:object(i)
	
			if obj then
				local id = obj:id()
	
				for _, s in ipairs( mark_for_drop ) do
					if id == s then
						db.actor:drop_item(obj)
						table.remove(mark_for_drop, _)
					end
			    end
			end
		end
	end

	if inv_ruck_id then
		local sobj = alife():object(inv_ruck_id)

		if not sobj or sobj:section_name() ~= "inv_ruck" then 
			local ruck = alife():create("active_ruck", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id()) 
			alife():use_ai_locations(ruck, false)
			level.map_add_object_spot_ser(ruck.id, "treasure", "%c[255,238,155,23]Мой тайник") 
			news_manager.send_tip(db.actor, "Тайник заложен", nil, nil, 5000) 
		end 

		inv_ruck_id = nil 
	end
end
