

-- https://github.com/dsh2dsh/op2ogse/blob/master/gamedata/scripts/sound_theme.script

nstl = 64

ph_snd_themes = {
	freedom_speech_normal = {
		[[characters_voice\scenario\military\freedom_megafon\freedom_megafon_music_1]],
		[[characters_voice\scenario\bar\radio_music\radio_music_1]],
		[[characters_voice\scenario\military\freedom_megafon\freedom_megafon_music_3]],
		[[characters_voice\scenario\bar\radio_music\bar_music_13]],
		[[characters_voice\scenario\military\freedom_megafon\freedom_megafon_music_5]],
		[[characters_voice\scenario\bar\radio_music\bar_music_8]],
		[[characters_voice\scenario\military\freedom_megafon\freedom_megafon_music_7]],
		[[characters_voice\scenario\bar\radio_music\bar_music_10]],
		[[characters_voice\scenario\military\freedom_megafon\freedom_megafon_music_10]],
		[[characters_voice\scenario\military\freedom_megafon\freedom_megafon_music_11]],
	},
	sidor_music_day = {
		[[characters_voice\scenario\esc\sidor_music_1]],
		[[characters_voice\scenario\esc\sidor_music_2]],
		[[characters_voice\scenario\esc\sidor_music_3]],
		[[characters_voice\scenario\esc\sidor_music_4]],
		[[characters_voice\scenario\esc\sidor_music_5]],
		[[characters_voice\scenario\esc\sidor_music_6]],
		[[characters_voice\scenario\esc\sidor_music_7]],
		[[characters_voice\scenario\esc\sidor_music_8]],
		[[characters_voice\scenario\esc\sidor_music_9]],
		[[characters_voice\scenario\esc\sidor_music_10]],
		[[characters_voice\scenario\esc\sidor_music_11]],
		[[characters_voice\scenario\esc\sidor_music_12]],
		[[characters_voice\scenario\esc\sidor_music_13]],
		[[characters_voice\scenario\esc\sidor_music_14]],
		[[characters_voice\scenario\esc\sidor_music_15]],
	},
	blockpost_music_day = {
		[[characters_voice\scenario\esc\sidor_music_1]],
		[[characters_voice\scenario\esc\sidor_music_2]],
		[[characters_voice\scenario\esc\sidor_music_3]],
		[[characters_voice\scenario\esc\sidor_music_4]],
		[[characters_voice\scenario\esc\sidor_music_5]],
		[[characters_voice\scenario\esc\sidor_music_6]],
		[[characters_voice\scenario\esc\sidor_music_7]],
		[[characters_voice\scenario\esc\sidor_music_8]],
		[[characters_voice\scenario\esc\sidor_music_9]],
		[[characters_voice\scenario\esc\sidor_music_10]],
		[[characters_voice\scenario\esc\sidor_music_11]],
		[[characters_voice\scenario\esc\sidor_music_12]],
		[[characters_voice\scenario\esc\sidor_music_13]],
		[[characters_voice\scenario\esc\sidor_music_14]],
		[[characters_voice\scenario\esc\sidor_music_15]],
	},
	music_horror_time = {
		[[characters_voice\scenario\esc\esc_music_horror_1]],
		[[characters_voice\scenario\esc\esc_music_horror_2]],
		[[characters_voice\scenario\esc\esc_music_horror_3]],
		[[characters_voice\scenario\esc\esc_music_blowout_1]],
		[[characters_voice\scenario\esc\esc_music_horror_4]],
	},
	radio_music_bandit = {
		[[characters_voice\scenario\darkscape\bandit_radio_1]],
		[[characters_voice\scenario\darkscape\bandit_radio_2]],
		[[characters_voice\scenario\darkscape\bandit_radio_3]],
	},
    music = {
        "characters_voice\\scenario\\megafon\\megafon_music_1",
        "characters_voice\\scenario\\megafon\\megafon_music_2",
        "characters_voice\\scenario\\megafon\\megafon_music_3"
    },
    humor = {
        "characters_voice\\scenario\\escape\\comandir_megafon_1",
        "characters_voice\\scenario\\escape\\comandir_megafon_2",
        "characters_voice\\scenario\\escape\\comandir_megafon_3",
        "characters_voice\\scenario\\escape\\comandir_megafon_4",
        "characters_voice\\scenario\\escape\\comandir_megafon_5",
        "characters_voice\\scenario\\escape\\comandir_megafon_6",
        "characters_voice\\scenario\\escape\\comandir_megafon_7",
        "characters_voice\\scenario\\escape\\comandir_megafon_8",
        "characters_voice\\scenario\\escape\\comandir_megafon_9",
        "characters_voice\\scenario\\escape\\comandir_megafon_10",
        "characters_voice\\scenario\\escape\\comandir_megafon_11",
        "characters_voice\\scenario\\escape\\comandir_megafon_12",
        "characters_voice\\scenario\\escape\\comandir_megafon_13",
        "characters_voice\\scenario\\escape\\comandir_megafon_14",
        "characters_voice\\scenario\\escape\\comandir_megafon_15",
        "characters_voice\\scenario\\escape\\comandir_megafon_16",
        "characters_voice\\scenario\\escape\\comandir_megafon_17"
    },
    epic = {
        "characters_voice\\scenario\\escape\\megafon_1",
        "characters_voice\\scenario\\escape\\megafon_2",
        "characters_voice\\scenario\\escape\\megafon_3",
        "characters_voice\\scenario\\escape\\megafon_4"
    },
    alarm1 = {
        "characters_voice\\scenario\\megafon\\megafon_alarm_1",
        "characters_voice\\scenario\\megafon\\megafon_alarm_10",
        "characters_voice\\scenario\\megafon\\megafon_alarm_11",
        "characters_voice\\scenario\\megafon\\megafon_alarm_12",
        "characters_voice\\scenario\\megafon\\megafon_alarm_13"
    },
    alarm2 = {
        "characters_voice\\scenario\\megafon\\megafon_alarm_2",
        "characters_voice\\scenario\\megafon\\megafon_alarm_3",
        "characters_voice\\scenario\\megafon\\megafon_alarm_4",
        "characters_voice\\scenario\\megafon\\megafon_alarm_5",
        "characters_voice\\scenario\\megafon\\megafon_alarm_6"
    },
    siren = {"ambient\\siren2"},
    bomb = {"detectors\\bomb_timer"},
    detector = {"detectors\\da-2_beep1"},
    radio_music = {
		[[characters_voice\scenario\bar\radio_music\bar_music_1]],
		[[characters_voice\scenario\bar\radio_music\bar_music_2]],
		[[characters_voice\scenario\bar\radio_music\bar_music_3]],
		[[characters_voice\scenario\bar\radio_music\bar_music_4]],
		[[characters_voice\scenario\bar\radio_music\bar_music_5]],
		[[characters_voice\scenario\bar\radio_music\bar_music_6]],
		[[characters_voice\scenario\bar\radio_music\bar_music_7]],
		[[characters_voice\scenario\bar\radio_music\bar_music_8]],
		[[characters_voice\scenario\bar\radio_music\bar_music_9]],
		[[characters_voice\scenario\bar\radio_music\bar_music_10]],
		[[characters_voice\scenario\bar\radio_music\bar_music_11]],
		[[characters_voice\scenario\bar\radio_music\bar_music_12]],
		[[characters_voice\scenario\bar\radio_music\bar_music_13]],
	},
    dolg_speech = {
        [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
        [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_3]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_4]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_5]],
        [[characters_voice\scenario\megafon\megafon_music_1]],
        [[characters_voice\scenario\megafon\megafon_music_2]],
        [[characters_voice\scenario\megafon\megafon_music_3]]
    },
    -- -------------------------------------------------------------ARENA_EXTENSION_MOD------------------------------------------------------------------
    arena_fight_10_sec = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_10_sec]]},
    arena_fight_20_sec = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_20_sec]]},
    arena_fight_30_sec = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_30_sec]]},
    arena_fight_40_sec = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_40_sec]]},
    arena_fight_50_sec = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_50_sec]]},
    aem_beast = {[[aem_snd\aem_beast]]},
    aem_bloodsucker = {[[aem_snd\aem_bloodsucker]]},
    aem_burer = {[[aem_snd\aem_burer]]},
    aem_fight_begin = {[[aem_snd\aem_fight_begin]]},
    aem_foul = {[[aem_snd\aem_foul]]},
    aem_no_chance = {[[aem_snd\aem_no_chance]]},
    aem_out_of_time = {[[aem_snd\aem_out_of_time]]},
    aem_pseudodog = {[[aem_snd\aem_pseudodog]]},
    aem_snork = {[[aem_snd\aem_snork]]},
    aem_special = {[[aem_snd\aem_special]]},
    aem_victory = {[[aem_snd\aem_victory]]},
    dolg_matugalnik = {
        [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
        [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]],
        [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
        [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_3]],
        [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_4]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_5]],
        [[characters_voice\scenario\bar\arena_megafon\mega_arena_new_fight]]
    },
    -- -------------------------------------------------------------ARENA_EXTENSION_MOD------------------------------------------------------------------

    dolg_alarm = {[[characters_voice\scenario\bar\dolg_megafon\megaphone_duty_alarm]]},
    dolg_megafon_1_hit = {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_1]]},
    dolg_megafon_2_hit = {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_2]]},
    dolg_megafon_kill = {[[characters_voice\scenario\bar\dolg_megafon\duty_gunfire_mega_3]]},
    arena_introduce_pseudodog = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_pseudodog]]},
    arena_introduce_snork = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_snork]]},
    arena_introduce_bloodsucker = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_bloodsucker]]},
    arena_introduce_burer = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_burer]]},
    arena_introduce_savage = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_zver]]},
    arena_actor_afraid = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_coward]]},
    arena_fight_begin = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_start]]},
    arena_fight_victory = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_win_1]]},
    arena_fight_victory_notime = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_win_2]]},
    arena_fight_lose = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_out_of_time_win]]},
    arena_fight_death = {[[characters_voice\scenario\bar\arena_megafon\mega_arena_dead]]},
    bar_start_megafon = {
        [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_1]],
        [[characters_voice\scenario\bar\barman_megafon\megaphone_barman_2]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_1]],
        [[characters_voice\scenario\bar\dolg_megafon\mega_duty_propaganda_2]]
    },
    mon_monolith_damaged = {[[characters_voice\scenario\sarcofag\monolith_damaged]]},
    mon_monolith_heavy_damaged = {[[characters_voice\scenario\sarcofag\monolith_heavy_damaged]]},
    mon_monolith_alarm = {[[characters_voice\scenario\sarcofag\monolith_alarm]]},
    mon_monolith_recharged = {[[characters_voice\scenario\sarcofag\monolith_recharged]]},
    sar_monolith_call = {
        [[characters_voice\scenario\sarcofag\monolith_call_1]],
        [[characters_voice\scenario\sarcofag\monolith_call_2]],
        [[characters_voice\scenario\sarcofag\monolith_call_3]],
        [[characters_voice\scenario\sarcofag\monolith_call_4]],
        [[characters_voice\scenario\sarcofag\monolith_call_5]],
        [[characters_voice\scenario\sarcofag\monolith_call_6]],
        [[characters_voice\scenario\sarcofag\monolith_call_7]]
    },
    gar_seryi_shooting = {[[characters_voice\scenario\garbage\distance_shooting]]},
    distance_shooting = {[[characters_voice\scenario\garbage\distance_shooting]]},
    gar_seryi_shooting_2 = {[[characters_voice\scenario\bandits\bandit_replic_2]]},
    aes_battle1 = {"ambient\\battle_1"},
    aes_battle2 = {"ambient\\battle_2"},
    gar_bandits_seryi = {
        [[characters_voice\scenario\garbage\grey_bandit_1]],
        [[characters_voice\scenario\garbage\grey_bandit_2]],
        [[characters_voice\scenario\garbage\grey_bandit_3]],
        [[characters_voice\scenario\garbage\grey_bandit_4]],
        [[characters_voice\scenario\garbage\grey_bandit_5]]
    },
    radar_drone = {"ambient\\radar_1"},
    radar_thunder = {"ambient\\radar_2"},
    radar_sparks = {"ambient\\radarsparks_1"},
    aes_teleport = {"anomaly\\teleport_incoming"},
    yan_antenna = {{"characters_voice\\scenario\\yantar\\psy_voices_1"}}, --' Стерео
    radar_meh_on = {"ambient\\cooling_run"},
    radar_meh_off = {"ambient\\cooling_stop"},
    radar_meh_loud_on = {"ambient\\cooling_run_loud"},
	radar_meh_loud_off = {"ambient\\cooling_stop_loud"},
    system_message_1 = {[[characters_voice\scenario\yantar\system_message_1]]},
    system_message_2 = {[[characters_voice\scenario\yantar\system_message_2]]},
    system_message_3 = {[[characters_voice\scenario\yantar\system_message_3]]},
    system_message_4 = {[[characters_voice\scenario\yantar\system_message_4]]},
    system_message_5 = {[[characters_voice\scenario\yantar\system_message_5]]},
    agro_test = {[[weapons\grenade1]]},
    bar_arena_public = {
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_1",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_1",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_2",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_3",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_4",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_5",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_6",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_7",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_8",
        "characters_voice\\scenario\\bar\\arena_public\\new_arena_public_9"
    },
    bar_arena_public_death = {
        "ambient\\arena\\crowd_wave_1",
        "ambient\\arena\\crowd_wave_2",
        "ambient\\arena\\crowd_wave_3"
    },
    bar_arena_fight_1 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_1_ready"},
    bar_arena_fight_1_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_1_finish"},
    bar_arena_fight_2 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_2_ready"},
    bar_arena_fight_2_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_2_finish"},
    bar_arena_fight_3 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_3_ready"},
    bar_arena_fight_3_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_3_finish"},
    bar_arena_fight_4 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_4_ready"},
    bar_arena_fight_4_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_4_finish"},
    bar_arena_fight_5 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_5_ready"},
    bar_arena_fight_5_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_5_finish"},
    bar_arena_fight_6 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_6_ready"},
    bar_arena_fight_6_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_6_finish"},
    bar_arena_fight_7 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_7_ready"},
    bar_arena_fight_7_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_7_finish"},
    bar_arena_fight_8 = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_8_ready"},
    bar_arena_fight_8_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_8_finish"},
    x18_sound_1 = {"ambient\\x18\\x18_hit_8"},
    x18_sound_2 = {"ambient\\x18\\x18_metal_2"},
    x18_sound_3 = {"ambient\\x18\\x18_metal_3"},
    x18_sound_4 = {"ambient\\x18\\x18_metal_4"},
    x18_sound_5 = {"ambient\\x18\\x18_metal_5"},
    x18_sound_6 = {"ambient\\x18\\x18_creak_2"},
    x18_sound_7 = {"ambient\\x18\\x18_creak_1"},
    x18_sound_8 = {"ambient\\x18\\x18_hit_7"},
    x18_sound_9 = {"ambient\\x18\\x18_footsteps_2"},
    x18_sound_10 = {"ambient\\x18\\x18_move_4"},
    x18_sound_11 = {"ambient\\x18\\x18_footsteps"},
    x18_sound_12 = {"ambient\\x18\\x18_move_3"},
    x16_engine1_run = {"ambient\\x16\\x16_engine1_run"},
    x16_engine1_stop = {"ambient\\x16\\x16_engine1_stop"},
    x16_engine2_run = {"ambient\\x16\\x16_engine2_run"},
    x16_engine2_stop = {"ambient\\x16\\x16_engine2_stop"},
    x16_hum_2 = {"ambient\\x16\\x16_hum_2"},
    x16_switch_1 = {"ambient\\x16\\switch_1"},
    x16_switch_2 = {"ambient\\x16\\switch_2"},
    x18_firedoor = {"anomaly\\fireball_idle"},
    mon_poltergeist = {"anomaly\\anomaly_gravy_hit1"},
    psy_voices = {{[[characters_voice\scenario\yantar\psy_voices_1]]}}, --' Стерео
    heli_explosion = {[[weapons\heli_explosion]]},
    trader_door_open_start = {[[device\door_start]]},
    trader_door_close_start = {[[device\door_closing]]},
    trader_door_close_stop = {[[device\door_stop]]},
    trader_door_locked = {[[device\door_locked]]},
    trader_door_unlock = {[[device\door_servomotor]]},
    wood_small_open = {[[device\wood_small_open]]},
    wood_small_close_start = {[[device\wood_small_close_start]]},
    wood_small_close_stop = {[[device\wood_small_close_stop]]},
    wood_large_open = {[[device\wood_large_open]]},
    wood_large_close_start = {[[device\wood_large_close_start]]},
    wood_large_close_stop = {[[device\wood_large_close_stop]]},
    metal_small_open = {[[device\metal_small_open]]},
    metal_small_close_start = {[[device\metal_small_close_start]]},
    metal_small_close_stop = {[[device\metal_small_close_stop]]},
    
    generator = {[[ambient\special\marsh_generator]]},
    
    -- fake_static
    -- snd_static не слышно в некоторых местах, поэтому используется это :(
    esc_vortex = {[[ambient\fake_static\esc\vortex]]},
    esc_car = {[[ambient\fake_static\esc\car]]},
    esc_gravi = {[[ambient\fake_static\esc\gravi]]},
    
    gar_hangar_wind = {[[ambient\fake_static\gar\hangar_wind]]},
    gar_tree_sux = {[[ambient\fake_static\gar\tree_sux]]},
    gar_mincer = {[[ambient\fake_static\gar\mincer]]},
    gar_metal = {[[ambient\fake_static\gar\metal]]},
    
    agr_glitch = {[[ambient\fake_static\agr\glitch]]},
    agr_trans = {[[ambient\fake_static\agr\trans]]},
    agr_wind = {[[ambient\fake_static\agr\wind]]},
    
    val_bus = {[[ambient\fake_static\val\bus]]},
    val_forest = {[[ambient\fake_static\val\forest]]},
    val_heli = {[[ambient\fake_static\val\heli]]},
    val_ventil = {[[ambient\fake_static\val\ventil]]},
}

-----------------------------------------------------------------------------------------------------------------------------------
--	Theme  functions
-----------------------------------------------------------------------------------------------------------------------------------
function weather_class(avail_types, npc)
	return level.rain_factor() < 0.07 and "weather_good" or "weather_bad"
end

function combat_class(avail_types, npc)
	return ( npc:best_enemy() or npc:best_danger() ) and "" or "state"
end

-------------------------------------------------------------------------
-- ЗВУКИ СТАЛКЕРОВ
-------------------------------------------------------------------------
local sounds_base = stalker_ids.sound_script + 10000
function id()
	sounds_base = sounds_base + 1
	return sounds_base - 1
end

theme = {
	-- погода
	weather 									= {exec = this.weather_class, 
													types = {weather_bad	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
						 							weather_good	= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}} }},

	-- состояния тела
	state 										= {exec = this.combat_class, 
													types = {state	= {min_snd = 60, max_snd = 90, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}} },
	

	sleep										= {min_snd = 10, max_snd = 15, rnd = 75, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- просьба о помощи
	help										= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_see									= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	help_heavy									= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_thanx									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy_shoot							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- окрик
	hail										= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- ожидание
	wait										= {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- speech
    speech										= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    speech1										= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    
	-- угрозы
	threat_weap									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_back									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_stop									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- реакции
	--
	reac_see									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	--
	--
	--
	--
	
	--
	reac_music									= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_joke									= {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- болтовня
	talk_hello									= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_hello_friend							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_bye									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_accept									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_reject									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_abuse									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- реакции на юзание
	use_yes_fight								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_sleep								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_kamp								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_default								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_fight								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_sleep								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_weapon								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_default								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_abuse									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- бой
	fight_attack								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_search								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_attack_many							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_attack_one							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_backup								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_detour								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy_down							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy_hit								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_friend_hitted							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_friendly_fire							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy_lost							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_threat_close							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_threat_distant						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_tolls									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	
	beware_grenade								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	zombied_fight_attack						= {min_snd = 5, max_snd = 10,rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- торговля
	trade_yes									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	trade_no									= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- игра на губной гармошке
	intro_music									= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	harmonica									= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- игра на гитаре
	guitar										= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- шутки, прибаутки
	intro_joke									= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	joke										= {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- УНИКАЛЬНЫЕ ТЕМЫ	
	-- Escape
	esc_tolik_help								= {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	esc_factory_raid							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_attack							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_victory							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_go								= {min_snd = 3, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	esc_tolik_to_wolf							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_to_lager							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_thanks							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	esc_wolf_say_thanks							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_lager_killer							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fanat_dialog							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fanat_ready								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	esc_bridge_soldiers							= {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_bandit_shustryi							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_shustryi_help							= {min_snd = 5, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_radio								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	esc_petruha_raport							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_raport_radio					= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_call							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fox_thanks								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_shustryi_thanks							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
			
	-- Garbage DramMoment
	gar_dm_bandit_backoff1						= {min_snd = 5, max_snd = 8, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_bandit_backoff2						= {min_snd = 5, max_snd = 8, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_bandit_demand						= {min_snd = 8, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_no_money						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_help_me						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_thank_you						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	gar_hellcar_alarm							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_ambush							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_bandits_seryi							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	gar_seryi_see_actor							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dolg_blokpost							= {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_direction_fire							= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_to_battle						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	
	-- DarkValley
	val_prisoner_captive_help_me    			= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_come_here  			= {min_snd = 4, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_open       			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_thanx      			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_leader_call             			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_leader_jeer             			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_guard_jeer              			= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	--
	--
	val_escort_guards               			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase1      			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase2      			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase3      			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase1         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase2         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase3         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase4         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase5         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase6         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase7         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_dead                 			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_go_home         			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_phrase_invite        			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Pripyat
	pri_followers_leader_phrase1_1  			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_2  			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_3  			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_final_phrase1     			= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_final_phrase2     			= {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Agroprom
	agr_factory_soldiers						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	-- desertir
	agr_dont_shoot								= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_desertir_spam							= {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_1							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_2							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_3							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    agr_stalker_help_4							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    agr_krot_thanks_2							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_krot_fear								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_doctor_1								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
-- Radar

	-- Bar Rostok Duty Guards
	--
	--
	bar_bar_osvedomitel_hello					= {min_snd = 15, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello						= {min_snd = 2, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	bar_dolg_leader_hello						= {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Bar dolg guard
	bar_dolg_guard_stop							= {min_snd = 15, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_guard_prohodi							= {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_guard_busy							= {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Bar dolg hangar bridge
	bar_dolg_hangar_bridge_hello				= {min_snd = 16, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	bar_guard_enter								= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      
	bar_guard_stop								= {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      

	-- Bar dolg Petrenko
	bar_dolg_petrenko_hello						= {min_snd = 3, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	-- Bar psyh
	--
	--
	--
	bar_arena_public							= {min_snd = 5, max_snd = 7, rnd = 80, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Rostok volkodav
	rostok_volkodav_talk_1						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      
	rostok_volkodav_talk_2						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	-- Rostok kruglov
	rostok_kruglov_help_1                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_2                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_3                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_4                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_5                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_6                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    rostok_kruglov_torrid                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	kruglov_stop_enemy_1                        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	kruglov_stop_enemy_2                        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--yantar sounds
	yantar_professor_idle						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_to_kruglov_1				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_to_kruglov_2				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_professor_1				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_professor_2				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_actor						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	--
	--
	yantar_professor_talk_1						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_radiation_quest_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_radiation_quest_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_4			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_5			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_6			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_7			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_8			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_9			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    yantar_kruglov_radiation_quest_10			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--
	--
	--
	--
	--
	yantar_probe_1								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_2								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_3								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

    -- Military sounds
    mil_max_thanx                  				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_before_collect         				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_kolyan                     				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_to_kolyan              				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_to_tolyan              				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh1             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh2             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh3             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh4             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_laugh5             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase1            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase2            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase3            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase4            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase5            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase6            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_collect_phrase7            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_crazy                      				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_about_sniper          				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_go_attack             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_patrol             				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_after_kill1           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_after_kill2           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_after_kill3           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    --
    --
    --
    mil_guard_to_max               				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    --
    mil_lukash_to_actor            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    --
    mil_dolg_killer                				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_scull                 				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_max_to_actor               				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    --
    mil_pavlik_to_ara              				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_ara_to_pavlik              				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_ara_ambush                 				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_hunter1                    				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_hunter2                    				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_hunter3                    				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_getready              				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_lukash_done           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush1            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush2            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush3            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush4            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush5            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_ambush6            				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory1           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory2           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory3           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory4           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_freedom_victory5           				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_before_attack1        				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}, 
    mil_dolg_before_attack2        				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_fight                 				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_dolg_silent                				= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    mil_cherep_hi                  				= {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}}
}
   
--' В темах для игрока интервал задается в миллисекундах!!!
actor_theme = {
	level_border_detector = {
		min_snd = 10, 
		max_snd = 100,
		sounds = {
			xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_1]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_2]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_2]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_4]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_5]]),
			xr_sound.get_safe_sound_object([[detectors\geiger_6]]) 
		}
	}
}

function attach(sm)
    sm:subscribe({signal = "on_init", fun = this.on_actor_init}) -- Нужно вызывать до начала спавна НПС.
    sm:subscribe({signal = "on_npc_before_spawn", fun = this.load_sound}) -- Вроде как должно вызываться до загрузки гулага
end

local preloaded = {}

local function preload_theme_sect(name)
    for _, sf in ipairs({"_rnd", "_spec", "_seq", "_single"}) do
        local theme_name = name .. sf
        ASSERT(not preloaded[theme_name], "[%s] already preloaded", theme_name)
        if sys_ini:section_exist(theme_name) then
            preloaded[theme_name] = {}
            local t = get_section_keys_and_values(theme_name)
            for k, v in pairs(t) do
                local flag, path = unpack(parse_names(v))
                ASSERT(path, "wrong path in %s: %s, flag = %s", theme_name, v, flag)
                flag = flag == "0" or sf == "_spec"
                preloaded[theme_name][k] = {path, flag}
            end
        end
    end
end

local function preload_themes(t)
    for k, v in pairs(t) do
        if v.types then
            preload_themes(v.types)
        else
            preload_theme_sect(k)
        end
    end
end

local function select_sound_from_ltx( obj, section )
  for _, k in ipairs({
      tostring( obj:story_id() ),
	  obj:profile_name(),
	  obj:character_community(),
      "stalker"
    }) do
    local t = preloaded[ section ][ k ]
    if t then return unpack( t ) end
  end
end

-- загрузка звуков на основе данных ltx
local default_prefix = "characters_voice\\"

function load_sound_from_ltx(obj, name, tbl)
    local id = obj:id()
    tbl.max_ids[id] = {}
    table.insert(db.sound[obj:id()].known_max_ids, tbl.max_ids)
    for _, sf in ipairs({"_rnd", "_spec", "_seq", "_single"}) do
        local n = name .. sf
        if preloaded[n] then
            local path, use_def = select_sound_from_ltx(obj, n)
            if path then
                local t = {
          			[ "path" ] = path,
                }
                if use_def then
                    t.prefix = default_prefix
                end
                local snd_key = (sf == "_rnd" or sf == "_spec") and "rnd" or "into"
                if snd_key == "into" then
                    tbl.max_ids[id].into_cycled = sf == "_seq"
                end
                tbl.max_ids[id][snd_key .. "_load"] = t
            end
        end
    end
end

local function load_theme_sound(npc, tbl)
    for k, v in pairs(tbl) do
        if v.types then
            load_theme_sound(npc, v.types)
        else
            load_sound_from_ltx(npc, k, v)
        end
    end
end

local function cleanup_max_ids(obj)
    local t = db.sound[obj:id()]
    if t then
        for _, max_ids in ipairs(t.known_max_ids) do
            max_ids[obj:id()] = nil
        end
    end
end

function load_sound(obj)
    cleanup_max_ids(obj)
    db.sound[obj:id()] = {
        ["known_max_ids"] = {}
    }
end

function on_actor_init()
    preload_themes(theme)
end
