--[[-----------------------------------------------------------------------------------------------
 File			: toxic_area.script
 Description 	: Ёффекты попадани€ в загр€зненную область
 Author  		: Muvbed, звуки из NLC
--]]-----------------------------------------------------------------------------------------------

function attach(sm)
	sm:subscribe({signal = "on_spawn", fun = this.init_restrictors})
	sm:subscribe({signal = "on_update", fun = this.update_state})
	sm:subscribe({signal = "update_artefacts_on_belt", fun = this.update_conditions})
	sm:subscribe({signal = "on_update", fun = this.update_static})
	sm:subscribe({signal = "on_update", fun = this.update_breath})
end

local toxic_restrictors = {}
local local_toxic_restrictor = nil
local is_actor_inside = false

function init_restrictors()
	if ogse.var_exists("toxic_restrictors") then
		toxic_restrictors = ogse.load_var("toxic_restrictors")
	else
		for id, sobj in alife():objects() do
			if string.find(sobj:name(), "toxic_restrictor") then
				table.insert(toxic_restrictors, id)
			end
		end
		
		ogse.save_var("toxic_restrictors", toxic_restrictors, "array", "u16")
	end
	
	local_toxic_restrictor = nil
	
	for i = 1, #toxic_restrictors do
		local id = toxic_restrictors[i]
		local sobj = alife():object(id)
		
		if sobj and level.name() == object_level_name(sobj) then
			local_toxic_restrictor = id
		end
	end
end

function update_state()
	ogse_signals.get_mgr():reschedule(200)
	
	is_actor_inside = false
	
	if db.actor and db.actor:alive() then	
		local zone = level.object_by_id(local_toxic_restrictor)
		local helmet = db.actor:item_in_slot(10)
		
		if not helmet and zone and zone:inside(db.actor:position()) then
			is_actor_inside = true
			
			if xr_conditions.can_send_tutorial() and not has_alife_info("encyclopedy_tutorial_gaz") then
				game.start_tutorial("part_3_gaz")
				db.actor:give_info_portion("encyclopedy_tutorial_gaz")
			end
		end
	end
end

function update_conditions(dt)
    if is_actor_inside then
    	local act = db.actor
    	local def_stand_power = get_float( "actor_condition", "stand_power" )

		act.power = def_stand_power * dt * 2
		act.health = -0.001 * act.health
    end
end

function update_static()
	ogse_signals.get_mgr():reschedule(250)

    if is_actor_inside then
        add_poison_static("inv_poison_static_red")
        
        level.add_pp_effector("acidic.ppe", 1600, true)
    	level.set_pp_effector_factor(1600, 0.25)
    	level.add_pp_effector("blur.ppe", 1601, true)
    	level.set_pp_effector_factor(1601, 1.0)
    else
    	remove_poison_static()
    	
    	level.remove_pp_effector(1600)
    	level.remove_pp_effector(1601)
    end
end

local breath_sound = {
    "actor\\nlc7\\gas_mask_breath_in_0",
    "actor\\nlc7\\gas_mask_breath_in_1",
    "actor\\nlc7\\gas_mask_breath_in_2"
}
    
function update_breath()
	ogse_signals.get_mgr():reschedule( 2000 + math.random( 2000 ) )
	
	if is_actor_inside then
		local act = db.actor
	    local snd_obj = xr_sound.get_safe_sound_object(breath_sound[math.random(1, 3)])
	
		act.power = -0.05
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function add_poison_static(static)
	local hud = get_hud()

	remove_poison_static()
	hud:AddCustomStatic(static, true)
end

function remove_poison_static()
	local hud = get_hud()
	
	if hud:GetCustomStatic("inv_poison_static_red") then
		hud:RemoveCustomStatic("inv_poison_static_red")
	end
end
