


function attach( sm )
	sm:subscribe({ signal = "on_use_box", fun = this.on_use_obj })
	sm:subscribe({ signal = "on_save", fun = this.save })
	sm:subscribe({ signal = "on_load", fun = this.load })
	sm:subscribe({ signal = "on_npc_use", fun = this.on_npc_use })
end

function on_use_obj( obj, who )
	get_treasure_manager():treasure_empty( obj, obj:story_id() )
end

function on_npc_use( obj )
	if obj:alive() then return end
	--
	local sobj = alife():object( obj:id() )
	if not sobj.treasure_processed and not GetShift() then -- Проверка на шифт сделана, чтоб не срабатывало при попытке перетащить труп.
		get_treasure_manager():use( obj )
		--
		give_money( obj )
		--
		sobj.treasure_processed = true
	end
end

-----------------------------------------------------------------
function give_money(npc)
	if (npc and db.actor) then
		if npc ~= nil and 
			not string.find(npc:section(), "arena") and
			not string.find(npc:section(), "aem")
		then
			local money = npc:money()
			if money ~= nil and money ~=0 then
				local deadmoney = money
				local news_texti = "%c[255,238,155,23]Имя: %c[default]"..get_charname(npc:character_name()).."\\n%c[255,238,155,23]Обнаружено денег: %c[default]"..game.translate_string(tostring(deadmoney).." руб.")
				db.actor:give_game_news(news_texti, "ui\\ui_iconsTotal", Frect():set(0,0,83,47), 1, 4000)
				db.actor:give_money(deadmoney)
				npc:give_money(-money)
			end
		end
	end
end

local treasure_manager = nil
secret_always_possible = false

function parse_spawns(line)
	if line == nil then
		return {}
	end

	--' если default-ов больше, чем значений в ini, то забить недостающие последним значением из ini
	local t = parse_names(line)
	local n = table.getn(t)
		
	local ret_table = {}
	local k = 1

	while k <= n do
		local spawn = {}
		spawn.section = t[k]
		-- Проверяем что это не последняя запись
		if t[k+1] ~= nil then
			local p = tonumber(t[k+1])
			-- проверяем что вторым числом задана вероятность, а не другая секция спавну
			if p then
				-- забиваем число
				spawn.prob = p
				k = k + 2
			else
				-- забиваем дефолт 1
				spawn.prob = 1
				k = k + 1
			end
		else
			spawn.prob = 1
			k = k + 1
		end
		table.insert(ret_table, spawn)
	end
	return ret_table
end


class "CTreasure"
function CTreasure:__init()
	ASSERT( sys_ini:section_exist("treasure_list"), "There is no section [treasure_list] in treasure_manager.ltx" )
	local n = sys_ini:line_count("treasure_list")
	local id, value = "",""
	local treasures_for_trade = {}

	self.treasure_info = {} --Начальная установка

	for i=0,n-1 do --Итерируемся по всем настройкам фраз
		result, id, value = sys_ini:r_line("treasure_list",i)
		
		self.treasure_info[id] = {}

		self.treasure_info[id].target		= utils.cfg_get_number(sys_ini, id, "target", nil, true)
		self.treasure_info[id].name			= utils.cfg_get_string(sys_ini, id, "name", nil, true, "")
		self.treasure_info[id].description	= utils.cfg_get_string(sys_ini, id, "description", nil, true, "")
		self.treasure_info[id].items		= parse_spawns(utils.cfg_get_string(sys_ini, id, "items", nil, true, ""))

		local community	= parse_names(utils.cfg_get_string(sys_ini, id, "community", nil, false, "", "stalker, bandit, dolg, freedom"))
		self.treasure_info[id].community = {}
		for k,v in pairs(community) do
			self.treasure_info[id].community[v] = true
			
			if v == "stranger" then
				treasures_for_trade[id] = true
			end
		end
		
		ogse.save_var(script_name() .. ".treasures_for_trade", treasures_for_trade, "table")

		if self.treasure_info[id].items == nil then
			abort("cant find 'items' in %s", id)
		end

		self.treasure_info[id].condlist		= xr_logic.parse_condlist(db.actor_proxy, "treasure_manager", "condlist", utils.cfg_get_string(sys_ini, id, "condlist", nil, false, "", ""))
		
		--' Отметим тайник как новый
		self.treasure_info[id].active = false
		self.treasure_info[id].done = false
	end

	--' Вспомогательные таблицы для облегчения поиска
	self.treasure_by_target = {}
	for k,v in pairs(self.treasure_info) do
		self.treasure_by_target[v.target] = k	
	end
end
--' Юзание инициатора (возможность выдать тайник)
function CTreasure:use(npc)
	local npc_community = npc:character_community()
	
	if string.sub(npc_community,1,3) == "pre" then
		npc_community = string.sub(npc_community,4,-1)
	end
			
	--' У военных тайник получить нельзя.
	if npc_community == "military" then 
		return
	end
	
	-- This block prevents getting new secrets from previously-searched bodies
	--' Проверим, не вызывались ли мы уже для этого объекта. 
	local se_obj = alife():object(npc:id())
	if secret_always_possible then se_obj.treasure_processed = false end
	if se_obj.treasure_processed == true then
		return
	end
	se_obj.treasure_processed = true

	-- how often is a secret possible? about 1 in 3
	if not secret_always_possible and math.random(100) < 65 then return end

	secret_always_possible = false -- reset to avoid multiple secrets

	--' Нужно рандомно выбрать один из тайников.
	local avail = {}
	local tr_sum = 0
	for k,v in pairs(self.treasure_info) do
		if not v.done then
			local treasure_prob = xr_logic.pick_section_from_condlist(db.actor, npc, v.condlist)
			treasure_prob = (not treasure_prob or treasure_prob == "") and 0 or tonumber(treasure_prob)

			-- nv - don't include treasure_prob == 0 case!
			if 
				treasure_prob > 0 
				and v.community[npc_community] == true 
				and not v.active
			then
				if treasure_prob == 100 then
					self:give_treasure(k)
					return
				else
					table.insert(avail, {k = k, prob = treasure_prob})
					tr_sum = tr_sum + treasure_prob
				end
			end
		end
	end

	if tr_sum == 0 or math.random(100) < 95 then return end

	local tr_w = math.random(tr_sum)
	for k,v in pairs(avail) do
		tr_w = tr_w - v.prob
		if tr_w <= 0 then
			--' Выдать тайник
			self:give_treasure(v.k)
			break
		end
	end
end
--' Сохранение
function CTreasure:check()
	--' Проверка тайников
	for k,v in pairs(self.treasure_info) do
		--' Выдать тайник
		if not v.active and not v.done then
			self:give_treasure(k)
		end
	end
end
-- Выдача тайника
function CTreasure:give_treasure(k)
	local v = self.treasure_info[k]
	
	if v.active or v.done then
		return
	end
	
	local sobj = alife():story_object(v.target)
	ASSERT(sobj, "!!Can't find treasure_box with story_id: [%s]", v.target)
	local text = "%c[255,238,155,23]"..game.translate_string(v.name).."\\n".."%c[default]"..game.translate_string(v.description)

	for k,t in pairs(v.items) do
		local class = get_class(t.section)
		if class == clsid.wpn_ammo or class == clsid.wpn_ammo_vog25 or class == clsid.wpn_ammo_og7b or class == clsid.wpn_ammo_m209 then
			ogse.spawn_ammo_in_inv(t.section, t.prob, sobj)
		else
			ogse.spawn_item_in_inv(t.section, sobj, t.prob)
		end
	end
	
	news_manager.send_treasure(v.name)

	-- Пометим тайник как выданный		
	level_tasks.add_location_by_id(sobj.id, "treasure", text)

	self.treasure_info[k].active = true
	self.treasure_info[k].done = true
end

--' Снимаем отметку с тайника
function CTreasure:treasure_empty(box, box_story_id)
	local k = self.treasure_by_target[box_story_id]

	if k == nil or self.treasure_info[k] == nil then 
		return
	end

	self.treasure_info[k].active = false
	level_tasks.remove_location_by_id(box:id(), "treasure")
end
-- Сохранение
function CTreasure:save()
	local treasures = {}
	for k,v in pairs(self.treasure_info) do
		table.insert( treasures, { v.target, v.active, v.done } )
	end
	ogse.save_var(
		script_name() .. ".treasures", treasures, "array_template",
		{ "u16", "bool", "bool" }
	)
end

-- Загрузка
function CTreasure:load( p )
	local treasures = ogse.load_var_safe( script_name() .. ".treasures" )
	for _, item in ipairs( treasures ) do
		local id, active, done = unpack( item )
		local k    = self.treasure_by_target[ id ]
		local info = self.treasure_info[ k ]
		info.active = active
		info.done   = done
	end
end

function CTreasure:get_treasures_for_trade()
	local treasures = ogse.load_var_safe(script_name() .. ".treasures_for_trade")
	
	if not treasures then
		return nil
	end
	
	local valid_treasures = {}
	
	for k, v in pairs(treasures) do
		if v == true then
			table.insert(valid_treasures, k)
		end
	end

	if #valid_treasures > 0 then
		return valid_treasures
	end
	
	return nil
end

function CTreasure:use_treasure_for_trade()
	local valid_treasures = self.get_treasures_for_trade()
	
	if not valid_treasures then return end
	
	local treasures = ogse.load_var_safe(script_name() .. ".treasures_for_trade")
	local random_index = math.random(#valid_treasures)
	local selected_key = valid_treasures[random_index]
	
	treasures[selected_key] = false
	
	ogse.save_var(script_name() .. ".treasures_for_trade", treasures, "table")

	self:give_treasure(selected_key)
end


function get_treasure_manager()
	if treasure_manager == nil then
		treasure_manager = CTreasure()
	end
	return treasure_manager
end

function save()
	get_treasure_manager():save()
end
function load()
	get_treasure_manager():load()
end
