--[[-----------------------------------------------------------------------------------------------
 File			: ui_loader.script
 Description	: Общие функции
 Source			: ABC Inferno
 Author			: serg101188
 Date			: 23.11.2011
 Last edit		: 16.10.2021
 UPD by Muvbed	: 2024
--]]-----------------------------------------------------------------------------------------------

local kShifts = {
	[DIK_keys.DIK_RSHIFT] = true,
	[DIK_keys.DIK_LSHIFT] = true
}

-- Нажатие клавиши
function on_key(dik, bind)
	if kShifts[dik] then _G.ShiftPressed = true end
	hotkeys.on_key(dik, bind)
	xr_signals.on_event( "key_press", dik, bind )
end

-- Отпускание клавиши
function on_key_free(dik, bind)
	if kShifts[dik] then _G.ShiftPressed = nil end
	xr_signals.on_event("key_release", dik, bind)
end

-- Новые статьи
function encyclopedy_news(group, name)
	ui_pda_dialogs.encyclopedy_news(group, name)
end

-- Фокус на ячейке инвентаря
function on_cell_item_focus(obj)
	xr_signals.on_event("cell_item_focus", obj)
end

-- Потеря фокуса ячейки инвентаря
function on_cell_item_focus_lost(obj)
	xr_signals.on_event("cell_item_focus_lost", obj)
end

-- Вращение колесиком мыши
function on_wheel_rotation(vol)
	xr_signals.on_event("mouse_wheel", vol)
end

-- net_spawn
function net_spawn(data)
	xr_signals.on_event("net_spawn")
end

-- net_destroy
function net_destroy()
	xr_signals.on_event("net_destroy")
end

-- __finalize()
function init()
	xr_signals.init()
end

-- Получение инфопоршена
function on_info(npc, info_id)
	xr_signals.on_event("info", info_id)
	ui_loader_pda.on_info(info_id)
	ui_loader_trade.on_info(info_id)
	ui_loader_carbody.on_info(info_id)
	ui_loader_inventory.on_info(info_id)
end

-- Взятие предмета в инвентарь
function on_item_take(obj)
	xr_signals.on_event("item_take", obj)
end

-- Сброс предмета из инвентаря
function on_item_drop(obj)
	xr_signals.on_event("item_drop", obj)
end

-- Обновление биндера
function update()
	xr_signals.on_update(delta)
	rx_shoot_enable.shoot_effect()
	ui_loader_inventory.update()
	ui_loader_carbody.update()
	ui_loader_trade.update()
	ui_loader_hud.update()
	ui_loader_pda.update()
end