-- ----------------------------------------------------------------------------------------------------
-- Общие функции
-- ----------------------------------------------------------------------------------------------------
function pda_on()
	--cmd("g_3d_pda", "on")
end

function pda_off()
	--cmd("g_3d_pda", "off")
end

function disable_ui_elements(actor, npc, p)
    local i, v = 0, 0
    for i, v in pairs(p) do
        if v == "all" then
            bind_stalker.hide_weapon()
            level.disable_input()
            level.hide_indicators()
            break
        elseif v == "weapon" then
            bind_stalker.hide_weapon()
        elseif v == "input" then
            level.disable_input()
        elseif v == "hud" then
            level.hide_indicators()
        end
    end
end

function enable_ui_elements(actor, npc, p)
    local i, v = 0, 0
    for i, v in pairs(p) do
        if v == "all" then
            level.show_indicators()
            level.enable_input()
            bind_stalker.restore_weapon()
            break
        elseif v == "hud" then
            level.show_indicators()
        elseif v == "input" then
            level.enable_input()
        elseif v == "weapon" then
            bind_stalker.restore_weapon()
        end
    end
end

function disable_ui(actor, npc)
    bind_stalker.hide_weapon()
    level.disable_input()
    level.hide_indicators()
end

function enable_ui(actor, npc)
    level.show_indicators()
    level.enable_input()
    bind_stalker.restore_weapon()
end

function run_cam_effector(actor, npc, p)
    if p[1] then
        local loop, num = false, (1000 + math.random(100))
        
        if p[2] and type(p[2]) == "number" and p[2] > 0 then
            num = p[2]
        end

        if p[3] and p[3] == "true" then
            loop = true
        end
        
        --level.add_pp_effector(p[1] .. ".ppe", num, loop)
	    level.add_cam_effector("camera_effects\\" .. p[1] .. ".anm", num, loop, "")	                  
    end
end

function stop_cam_effector(actor, npc, p)
    if p[1] and type(p[1]) == "number" and p[1] > 0 then
        level.remove_cam_effector(p[1])
    end
end

function run_postprocess(actor, npc, p)
    if p[1] then
        local loop, num = false, (2000 + math.random(100))
        
        if p[2] and type(p[2]) == "number" and p[2] > 0 then
            num = p[2]
        end

        if p[3] and p[3] == "true" then
            loop = true
        end
        
        level.add_pp_effector(p[1] .. ".ppe", num, loop)
    end
end

function stop_postprocess(actor, npc, p)
    if p[1] and type(p[1]) == "number" and p[1] > 0 then
        level.remove_pp_effector(p[1])
    end
end

function run_tutorial(actor, npc, p)
	game.start_tutorial(p[1])
end
function run_tutorial_if_newbie(actor, npc, p)
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial(p[1])
	end
end

function teleport_actor(actor, npc, p)
	local point = patrol(p[1])
	local look = patrol(p[2])
	
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())	
end

-----------------------------------------------------------------------------
local drop_point, drop_object = 0, 0
local function drop_object_item(item)
    drop_object:drop_item_and_teleport(item, drop_point)
end

function drop_actor_inventory(actor, npc, p)
    if p[1] then
        drop_point  = patrol(p[1]):point(0)
        drop_object = actor
        actor:inventory_for_each(drop_object_item)
    end
end

-- FIXME: drop_npc_inventory doesn't work
function drop_npc_inventory(actor, npc, p)
    if p[1] then
        drop_point  = patrol(p[1]):point(0)
        drop_object = npc
        npc:inventory_for_each(drop_object_item)
    end
end

function drop_npc_item(actor, npc, p)
    if p[1] then
        local item = npc:object(p[1])
        if item then
		    npc:drop_item(item)
		end
    end
end

function drop_npc_items(actor, npc, p)
    local item = 0
	for i, v in pairs(p) do
        item = npc:object(v)
        if item then
		    npc:drop_item(item)
        end
    end
end

function give_item(actor, npc, p)
    if p[1] then
		if not npc:object(p[1]) then
        	alife():create(p[1], npc:position(), npc:level_vertex_id(), npc:game_vertex_id(), npc:id())
        end
    end
end

function give_items(actor, npc, p)
    local pos, lv_id, gv_id, npc_id = npc:position(), npc:level_vertex_id(), npc:game_vertex_id(), npc:id()
	for i, v in pairs(p) do
        alife():create(v, pos, lv_id, gv_id, npc_id)
    end
end

function play_particle_on_path(actor, npc, p)
    local name = p[1]
    local path = p[2]
    local point_prob = p[3]
    if name == nil or path == nil then
        return
    end

    if point_prob == nil then
        point_prob = 100
    end
    
    local path = patrol(path)
    local count = path:count()
    for a = 0,count-1,1 do   
        local particle = particles_object(name)
        if math.random(100) <= point_prob then
            particle:play_at_pos(path:point(a))
        end
    end   
end

-----------------------------------------------------------------------------
function monster_berserk(actor, npc)
    npc:berserk()
end

function activate_bolt(actor, npc)
	db.actor:activate_slot(5)
end

--[[
send_tip(news_id:sender:sender_id)
    1. news_id
    2. sender*
    3. sender_id*
    * - not necessary
--]]
function send_tip(actor, npc, p)
    news_manager.send_tip(actor, p[1], nil, p[2], nil, p[3])
end

--[[
Дать сталкеру небольшой пинок. Например чтоб скинуть его с возвышения.
параметры: actor, npc, p[direction,bone,power,impulse,reverse=false]
    1. direction - если строка, то считается, что это имя пути и в сторону
        первой точки производится толчек. Если же это число, то оно
        рассматривается как story_id персонажа от которого должен поступить хит.
    2. bone - строка. Имя кости, по которой наносится удар.
    3. power - сила удара
    4. impulse - импульс
    5. reverse (true/false) - изменение направления удара. по умолчанию false
--]]
function hit_npc(actor, npc, p)
	local h = hit()
	local rev = p[5] and p[5] == 'true'
	h.draftsman = npc
	h.type = hit.wound
	if type(p[1]) == 'number' then
		local hitter = level_object_by_sid(p[1])
		if not hitter then return end
	    if rev then
	        h.draftsman = hitter
		    h.direction = hitter:position():sub(npc:position())
	    else
		    h.direction = npc:position():sub(hitter:position())
	    end
	else
	    if rev then
	        h.draftsman = nil
		    h.direction = npc:position():sub(patrol(p[1]):point(0))
	    else
		    h.direction = patrol(p[1]):point(0):sub(npc:position())
	    end
	end
	h:bone(p[2])
	h.power = p[3]
	h.impulse = p[4]
	npc:hit(h)
end

--[[
Дать обьекту, заданному story_id, хит.
параметры: actor, npc, p[sid,bone,power,impulse,hit_src=npc:position()]
    1. sid - story_id обьекта, по которому наносится хит.
    2. bone - строка. Имя кости, по которой наносится удар.
    3. power - сила удара
    4. impulse - импульс
    5. hit_src - если число, то рассматривается как story_id обьекта, со стороны
        которого наносится хит (он же является и инициатором хита), иначе это
        точка (waypoint), из которой по объекту наносится хит.
        Если не задано, то берется позиция обьекта, из которого была вызвана
        данная функция.
--]]
function hit_obj(actor, npc, p)
	local h = hit()
	local obj = level_object_by_sid(p[1])
	local sid = nil

	if not obj then
--		abort("HIT_OBJ [%s]. Target object does not exist", npc:name())
		return
	end

	h:bone(p[2])
	h.power = p[3]
	h.impulse = p[4]

	if p[5] then
	    sid = tonumber(p[5])
	    if sid then
	        sid = level_object_by_sid(sid)
	        if sid then
	            h.direction = vector():sub(sid:position(), obj:position())
	        end
	    end
	    if not sid then
	        h.direction = vector():sub(patrol(p[5]):point(0), obj:position())
	    end
	else
	    h.direction = vector():sub(npc:position(), obj:position())
	end

	h.draftsman = sid or npc
	h.type = hit.wound
	obj:hit(h)
end

--[[
Дать сталкеру небольшой пинок после смерти. Аналогично предыдущему, только направление хита теперь
вычисляется через убийцу. Поэтому параметра direction нет.
параметры: actor, npc, p[bone,power,impulse]
FIXME: killer:position() isn't working
--]]
function hit_by_killer(actor, npc, p)
	if not npc then return end
	local t = db.storage[npc:id()].death
	if t == nil or t.killer == -1 then return end
	local killer = db.storage[t.killer]
	if killer == nil then return end
	local p1, p2
	p1 = npc:position()
	p2 = killer:position()
	local h = hit()
	h.draftsman = npc
	h.type = hit.wound
	h.direction = utils.vector_copy_by_val(p1):sub(p2)
	h:bone(p[1])
	h.power = p[2]
	h.impulse = p[3]
	npc:hit(h)
end

function set_friends(actor, npc, p)
    local npc1
	for i, v in pairs(p) do
		npc1 = level_object_by_sid(v)
		if npc1 and npc1:alive() then
			npc:set_relation(game_object.friend, npc1)
			npc1:set_relation(game_object.friend, npc)
		end
	end
end

function set_enemies(actor, npc, p)
    local npc1
	for i, v in pairs(p) do
		npc1 = level_object_by_sid(v)
		if npc1 and npc1:alive() then
			npc:set_relation(game_object.enemy, npc1)
			npc1:set_relation(game_object.enemy, npc)
		end
	end
end

-- играть звук в голове актёра
function play_snd(actor, npc, p)
	if p[1] then
		local snd_obj = xr_sound.get_safe_sound_object(p[1])
		if snd_obj then
			snd_obj:play_no_feedback(actor, sound_object.s2d, p[2] or 0, vector(), 1.0)
		end
	end
end

-- играть звук от указанного объекта
function play_snd_from_obj(actor, npc, p)
	if p[1] and p[2] then
		local snd_obj = xr_sound.get_safe_sound_object(p[2])
		local obj     = level_object_by_sid(p[1])
        if obj ~= nil then
			if snd_obj then
				snd_obj:play_no_feedback(obj, sound_object.s3d, 0, obj:position(), 1.0)
			end
		end
	end
end
-- играть звук от указанного объекта. Объект от которого играть задаётся параметром npc
function play_snd_from_obj2(actor, npc, p)
	ASSERT(p[1], "play_snd_from_obj2: sound is not defined for object '%s'", npc:name())
	local snd_obj = xr_sound.get_safe_sound_object(p[1])
	ASSERT(snd_obj, "play_snd_from_obj2: problem creating sound '%s' for object '%s'", p[1], npc:name())
	snd_obj:play_no_feedback(npc, sound_object.s3d, 0, npc:position(), 1.0)
end

-- играть звук от указанного объекта
function play_snd_now(actor, npc, p)
	xr_sound.set_sound_play(npc, p[1])
end

-- прибавить к указанному счётчику актёра 1
function inc_counter(actor, npc, p)
	if p[1] then
		xr_logic.pstor_store(actor, p[1], xr_logic.pstor_retrieve(actor, p[1], 0) + 1)
	end
end

function dec_counter(actor, npc, p)
	if p[1] then
		xr_logic.pstor_store(actor, p[1], xr_logic.pstor_retrieve(actor, p[1], 0) - 1)
	end
end

-- переключает камеру на монстра или на актёра
function alien_control( actor, npc, p )
	npc:set_alien_control( p[1] == "true" )
end

-- слелать актёра врагом персонажам, которые в онлайне под указанным смартом
function set_gulag_enemy_actor( actor, npc, p )
	if p[1] then
		xr_gulag.setGulagEnemy(p[1], actor)
	end
end

-- принудительное обновление смарта. Использовать только в КРАЙНИХ случаях!!!
-- каждое использование согласовывать со мной. Чугай.
function smart_terrain_force_update(actor, npc, p)

	if p[1] then
		local gulag = xr_gulag.get_gulag(p[1])

		if gulag then
			gulag.smrttrn:update()
		end
	end
end

------------------------------------------------------------------------------------------------------------------------

-- Эффект от удара по морде (Muvbed)
function actor_punch(npc)
	if not db.actor:alive() then return end
	if db.actor:position():distance_to_sqr(npc:position()) > 3.24 then
		return
	end
	
	local active_item = db.actor:active_item()
	if active_item then
		bind_stalker.hide_weapon()
		bind_stalker.restore_weapon()
	end

	level.disable_input()

	dsh.timeout( 1000, function()
		level.enable_input()
	end )
	
	local snd_obj = xr_sound.get_safe_sound_object([[affects\hit_fist]])
	if snd_obj then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	
	local h = hit()
	h.draftsman = db.actor
	h.type = hit.strike
	h.direction = vector():set(0, 0, 0)
	h:bone("bip01_head")
	h.power = 0.1
	h.impulse = 0
	db.actor:hit(h)

	level.add_cam_effector("camera_effects\\fusker.anm",959,false,"")
	level.add_pp_effector("facer.ppe",959,false)
	level.set_pp_effector_factor(959,0.15)
	level.add_pp_effector("wink.ppe",960,false)
end

-- Принудительное усыпание игрока на радаре.
function force_actor_sleep(npc)
	db.actor:actor_sleep(10, 0)
end


-- забывание обиды
function clearAbuse(npc)
	xr_abuse.clear_abuse(npc)
end


---Выключение динамической лампочки (hanging_lamp)
function turn_off(actor, npc, p)
	local obj = level_object_by_sid(p[1])

	if not obj then
		abort("TURN_OFF [%s]. Target object does not exist", npc:name())
		return
	end
	obj:get_hanging_lamp():turn_off()
end
function turn_off_object(actor, npc)
	npc:get_hanging_lamp():turn_off()
end

---Включение динамической лампочки (hanging_lamp)
function turn_on(actor, npc, p)
	local obj = level_object_by_sid(p[1])

	if not obj then
		abort("TURN_ON [%s]. Target object does not exist", npc:name())
		return
	end
	obj:get_hanging_lamp():turn_on()
end
function turn_on_object(actor, npc)
	npc:get_hanging_lamp():turn_on()
end

------------------------------------------------------------------------------------------------

-- Кто-то из участников сценки вступил в бой - теперь нужно пообижать всех на всех
function gar_dm_bandits_fight(actor, npc)
  local novice = level_object_by_sid( 104 )
  if not ( novice and novice:alive() ) then return end
	local ignore_actor = false
	local bandits = { 101, 102, 103 }
	for _, sid in ipairs( bandits ) do
		local bandit = level_object_by_sid( sid )
		if bandit and bandit:alive() then
			bandit:set_character_community( "bandit", 0, 0 )
			novice:set_relation( game_object.enemy, bandit )
			if not ignore_actor then
				bandit:set_relation( game_object.enemy, db.actor )
			end
			bandit:set_relation( game_object.enemy, novice )
 		end
	end
end

function gar_dm_bandit_demand(actor, npc)
	if has_alife_info("gar_dm_bandit1_demand") or
	   has_alife_info("gar_dm_bandit2_demand") or
	   has_alife_info("gar_dm_bandit3_demand") then
		return
	end
	local r = math.random(3)
	if r == 1 then
		actor:give_info_portion("gar_dm_bandit1_demand")
	elseif r == 2 then
		actor:give_info_portion("gar_dm_bandit2_demand")
	else
		actor:give_info_portion("gar_dm_bandit3_demand")
	end
end

function gar_send_dymon_alarm(actor, npc)
	if has_alife_info("gar_start_graveyard") then
		news_manager.send_tip(actor, "tips_gar_hellcar_alarm", 2, "bes", 9000)
	end
end

function gar_direction_fire(actor, npc)
	if has_alife_info("gar_hellcar_help") 
	  and not has_alife_info("gar_counter_fire") 
	  and not has_alife_info("gar_open_fire") 
	then
		news_manager.send_tip(actor, "gar_direction_fire", 0, "bes", 0)
	end
end

function gar_hellcar_victory(actor, npc)
	if not has_alife_info("gar_hellcar_tips_end") 
	  and has_alife_info("gar_hellcar_help") 
	  and not has_alife_info("gar_hellcar_thanks") 
	then
		news_manager.send_tip(actor, "gar_hellcar_victory", 0, "bes", 0)
		db.actor:give_info_portion("gar_hellcar_tips_end")
	end
end

function gar_seryi_victory(actor, npc)
	if not has_alife_info("gar_seriy_bandits_killed") then
		actor:give_info_portion("gar_seriy_bandits_killed")
		news_manager.send_tip(actor, "gar_hellcar_victory_2", 0, "ser", 8000)
		local snd_obj = xr_sound.get_safe_sound_object([[device\pda\inv_tip]])
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function gar_wounded_set_bandit(actor, npc)
	npc:set_character_community( "bandit", 0, 0 )
end

--' Делаем третий вариант сообщения
function gar_boars_counter(actor, npc)
	if xr_gulag.isGulagEnemy( "gar_dolg_blokpost", db.actor ) then return end

	local c = xr_logic.pstor_retrieve(actor, "gar_boars_counter", 0)
	if c < 1 then
		news_manager.send_tip(actor, "gar_actor_looser", 0, "dolg", 0)
	else
		if c > 2 then
			news_manager.send_tip(actor, "gar_actor_winner", 0, "dolg", 0)
			db.actor:give_info_portion("gar_kill_boars_request")
			db.actor:give_info_portion("gar_free_pass")
		else
			news_manager.send_tip(actor, "gar_actor_normal", 0, "dolg", 0)
		end
	end
end

--' Escape

--' Предупреждение солдат под мостом
function esc_bridge_warning_tip()
	if 
	  utils.npc_in_zone(db.actor, db.zone_by_name["esc_bridge_kill_zone"]) 
	  and not has_alife_info("esc_bridge_warning")
	then
		db.actor:give_info_portion("esc_bridge_warning")
		news_manager.send_tip(db.actor, "esc_bridge_warning_tip", 0, "soldier", 0)
	end
end

--' Агр солдат под мостом
function esc_bridge_set_enemy_actor()
	xr_gulag.setGulagEnemy("esc_bridge", db.actor)
end

--' Смена группировки солдат на настоящих военных
function esc_bridge_set_mil()	
	for id, _ in pairs(db.creature) do
		local obj = level.object_by_id(id)

		if obj 
		  and obj:is_stalker() 
		  and obj:character_community() == "premilitary" 
		  and obj:alive() 
		then
			obj:set_character_community( "military", 0, 0 )
		end
	end
end

--' Лис даёт награду, только если ГГ действительно помог убить собак
function esc_fox_dogs_counter()
	local cnt = xr_logic.pstor_retrieve(db.actor, "esc_fox_dogs_counter", 0)

	if cnt > 0 then
		db.actor:give_info_portion("fox_dogs")
	end
end

function play_snd_from_radio(actor, npc)
	local snd_obj	= xr_sound.get_safe_sound_object([[characters_voice\scenario\escape\wolf_to_rangers_1]])
	local obj		= npc:object("hand_radio")
	if snd_obj then
		snd_obj:play_no_feedback(obj, sound_object.s3d, 0, obj:position(), 1.0)	
	end
end

function esc_direction_fire(actor, npc)
	if has_alife_info("esc_yes") and not has_alife_info("esc_fanat_die") then
		news_manager.send_tip(actor, "esc_direction_fire", 7, "fanat", 0)
	end
end

function esc_fanat_victory(actor, npc)
	if has_alife_info("escape_lager_killers_die") and not has_alife_info("esc_fanat_die") then
		-- nv140312 play victory only if Marked One volunteered to help
		if has_alife_info("escape_lager_help") then
			news_manager.send_tip(actor, "esc_fanat_victory", 0, "fanat", 10000)
		end
	end
end

function esc_return_dv(actor, npc)
		news_manager.send_tip(actor, "esc_return_dv", 0, "trader", 10)
end



-- function esc_lager_forgive_actor(actor, npc)
--	xr_gulag.setGulagNeutral("esc_lager", db.actor)
-- end

--' garbage

function gar_mapspot_blockpost (actor, npc)
	level_tasks.add_location_by_sid(story_ids.gar_spot_dolg_blokpost, "crlc_small", "gar_dolg_blokpost_leader_name")
end
	
function actor_friend(actor, npc)
	npc:set_relation(game_object.friend, actor)
end

function actor_friend2(npc, actor)
	npc:set_relation(game_object.friend, actor)
end

function actor_neutral(actor, npc)
	npc:set_relation(game_object.neutral, actor)
end

function actor_enemy(actor, npc)
	npc:set_relation(game_object.enemy, db.actor)
	npc:set_goodwill(-5000, db.actor)
end

function give_all_quests(actor, npc)
	--bar_dialogs.quests()
end

function give_rostok_quests(actor, npc)
	bar_dialogs.rostok_quests()
end


-- Вызов этой функции отключит обработчик [combat] боя для персонажа.
-- Используется в случаях, когда все необходимые действия, такие как переключение на другую секцию,
-- уже выполнены, и повторно выполнять их во время боя нельзя (а условия секции [combat] проверяются на каждом
-- апдейте, когда персонаж в бою, если, конечно, не отключены вызовом этой функции).
function disable_combat_handler(actor, npc)
	if db.storage[npc:id()].combat then
		db.storage[npc:id()].combat.enabled = false
	end
	
	if db.storage[npc:id()].mob_combat then
		db.storage[npc:id()].mob_combat.enabled = false
	end
end

function log_bp1(actor, npc)
end

function psi_hit_npc(actor, npc,p)
end


function mil_paul_frost_dead (actor, npc)
end

function set_freedom_actor_enemy (actor, npc)
    local luk = level_object_by_sid (707)
    this.actor_enemy (actor, luk)
end

function military_dolg_dead()
	local gulag = xr_gulag.get_gulag_by_name( "mil_dolg" )
	for obj_id, _ in pairs( gulag.Object_begin_job ) do
		local sobj = alife():object( obj_id )
		if sobj then
			if sobj:alive() and object_level_name( sobj ) == "l07_military" then
				return false
			end
		end
	end
	--
	db.actor:give_info_portion("mil_dolg_dead")
	return true
end

function mil_patrol_death_check (actor, npc)
    if has_alife_info("mil_patrol_man1_dead") and has_alife_info("mil_patrol_man2_dead") and has_alife_info("mil_patrol_man3_dead") then
       actor:give_info_portion ("mil_patrol_dead")
    end
end

function mil_cook_dead (actor, npc)
    --level_tasks.set_task_state (task.fail, "mil_freedom_rg6_task", 2)
end

function search_gulag_job(actor, npc)
	xr_gulag.resetJob(npc)
end


--------------------------------------------------------- 
-- BAR-ROSTOK
--------------------------------------------------------- 

function bar_freedom_spam_1(actor, npc)
	news_manager.send_tip(actor, "bar_freedom_spam_1", nil, "killer", nil, 509)
end
function bar_freedom_spam_2(actor, npc)
	news_manager.send_tip(actor, "bar_freedom_spam_2", nil, "killer", nil, 509)
end
function bar_freedom_spam_3(actor, npc)
	news_manager.send_tip(actor, "bar_freedom_spam_3", nil, "killer", nil, 509)
end
function bar_freedom_spam_4(actor, npc)
	news_manager.send_tip(actor, "bar_freedom_spam_4", nil, "killer", nil, 509)
end
function bar_ecolog_spam_1(actor, npc)
	news_manager.send_tip(actor, "bar_ecolog_spam_1", nil, "ecolog", nil, 503)
end
function bar_ecolog_spam_2(actor, npc)
	news_manager.send_tip(actor, "bar_ecolog_spam_2", nil, "ecolog", nil, 503)
end
function bar_ecolog_spam_3(actor, npc)
	news_manager.send_tip(actor, "bar_ecolog_spam_3", nil, "ecolog", nil, 503)
end
function bar_ecolog_spam_4(actor, npc)
	news_manager.send_tip(actor, "bar_ecolog_spam_4", nil, "ecolog", nil, 503)
end
function bar_ecolog_spam_5(actor, npc)
	if not has_alife_info("bar_heli_scene_volkodav_die") and not has_alife_info("bar_ecolog_saw_chase") then
		news_manager.send_tip(actor, "bar_freedom_chase", nil, "ecolog", nil, 503)
		db.actor:give_info_portion("bar_ecolog_saw_chase")
	end
end
function bar_ecolog_hit(actor, npc)
	news_manager.send_tip(actor, "bar_ecolog_hit", nil, "ecolog", nil, 503)
end
function bar_freedom_spam_5(actor, npc)
	if not has_alife_info("bar_heli_scene_volkodav_die") then
		news_manager.send_tip(actor, "bar_ecolog_escape", nil, "killer", nil, 509)
	end
end
function bar_freedom_angry_actor(actor,npc)
	if has_alife_info("bar_ecolog_crush_actor_enemy")
	then
		npc:set_relation(game_object.enemy, db.actor)
	end
end
function bar_freedom_defence_ecolog(actor,npc)
	news_manager.send_tip(db.actor, "bar_ecolog_attack", nil, "ecolog", nil, 503)
end		
function bar_freedom_angry_actor_notify(actor,npc)
	if has_alife_info("bar_ecolog_crush_actor_enemy") then
		news_manager.send_tip(actor, "bar_freedom_attack_spy", 4, "killer", nil, 509)
	end
end
function bar_crush_heli_start(actor,npc)
	news_manager.send_tip(actor, "bar_ecolog_crush_start_heli", nil, "ecolog", nil, 503)
end
function rostok_kruglov_tip_1(actor,npc)
	news_manager.send_tip(actor, "rostok_kruglov_spam_1", nil, "ecolog", nil, 503)
end
function rostok_kruglov_tip_2(actor,npc)
	news_manager.send_tip(actor, "rostok_kruglov_spam_2", nil, "ecolog", nil, 503)
	level_tasks.add_location_by_sid(story_ids.rostok_banda_volkodava, "volkodav_location", "rostok_banda_volkodava")
end
function rostok_kruglov_attract_1(actor,npc)
	xr_sound.set_sound_play(npc, "kruglov_stop_enemy_1")
	local tips_sound = news_manager.send_tip_nosound(db.actor, "bar_freedom_chase", 0, "ecolog")
	if tips_sound ~= nil then
		--' Играем звук забитый
		tips_sound:play(db.actor, 0, sound_object.s2d)
	end
end
function rostok_kruglov_attract_2(actor,npc)
	xr_sound.set_sound_play(npc, "kruglov_stop_enemy_2",3)
	local tips_sound = news_manager.send_tip_nosound(db.actor, "rostok_kruglov_follow_2",3000, "ecolog")
	if tips_sound ~= nil then
		--' Играем звук забитый
		tips_sound:play(db.actor, 0, sound_object.s2d)
	end
end
function rostok_kruglov_ambush(actor,npc)
	xr_sound.set_sound_play(npc, "rostok_kruglov_help_5")
	local tips_sound = news_manager.send_tip_nosound(db.actor, "rostok_kruglov_follow_3", 0, "ecolog")
	if tips_sound ~= nil then
		--' Играем звук забитый
		tips_sound:play(db.actor, 0, sound_object.s2d)
	end
end
function bar_crush_heli_down(actor,npc)
	news_manager.send_tip(actor, "bar_ecolog_crush_heli_down", 1, "killer", nil, 509)
end
function bar_ecolog_crush_attract_actor(actor,npc)
	if not has_alife_info("bar_heli_scene_professor_die") then
		news_manager.send_tip(actor, "bar_ecolog_crush_attract_actor", nil, "ecolog")
	end
end
function bar_freedom_attack_attract_actor(actor,npc)
		news_manager.send_tip(actor, "bar_freedom_attack_attract_actor", nil, "killer")
	end
function bar_freedom_attack_start(actor,npc)
		if not has_alife_info("bar_freedom_defence_ecolog") then
			news_manager.send_tip(db.actor, "bar_freedom_attack", nil, "killer", nil, 509)
            db.actor:give_info_portion("bar_freedom_defence_ecolog")
		end
	end
function bar_arena_hit(actor, npc)
	local h = hit()
	h.power = 0.01
	h.direction = npc:direction()
	h.draftsman = db.actor 
	h.impulse = 1
	h.type = hit.wound
	npc:hit(h)
end
function esc_hit_from_fox(actor, npc)
	local fox = level_object_by_sid (005)
	if fox == nil then
		return
	end
	local h = hit()
	h.power = 0.01
	h.direction = npc:direction()
	h.draftsman = fox 
	h.impulse = 1
	h.type = hit.wound
	npc:hit(h)
end

function bar_territory_logic(actor, npc)
	local level = level.name()
	if 	level == "l05_bar" then
		if dialogs.actor_in_dolg(actor,npc) then
			if has_alife_info("bar_dolg_territory_kill") then
				news_manager.send_tip(actor, "bar_territory_dolg_kill", nil, "dolg", nil, 507)
				xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava_2", db.actor)
				xr_gulag.setGulagEnemy("bar_visitors", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_3_hit") then
				news_manager.send_tip(actor, "bar_territory_dolg_3_hit", nil, "dolg", nil, 507)
				xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava_2", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_2_hit") then
				news_manager.send_tip(actor, "bar_territory_dolg_2_hit", nil, "dolg", nil, 507)
				return
			end
			if has_alife_info("bar_dolg_territory_1_hit") then
				news_manager.send_tip(actor, "bar_territory_dolg_1_hit", nil, "dolg", nil, 507)
				return
			end
		else
			if has_alife_info("bar_dolg_territory_kill") then
				db.actor:give_info_portion("bar_territory_nodolg_kill")
				news_manager.send_tip(actor, "bar_territory_nodolg_kill", nil, "dolg", nil, 507)
				xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava_2", db.actor)
				xr_gulag.setGulagEnemy("bar_visitors", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_2_hit") then
				db.actor:give_info_portion("bar_territory_nodolg_2_hit")
				news_manager.send_tip(actor, "bar_territory_nodolg_2_hit", nil, "dolg", nil, 507)
				xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
				xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava", db.actor)
				xr_gulag.setGulagEnemy("bar_zastava_2", db.actor)
				xr_gulag.setGulagEnemy("bar_visitors", db.actor)
				return
			end
			if has_alife_info("bar_dolg_territory_1_hit") then
				db.actor:give_info_portion("bar_territory_nodolg_1_hit")
				news_manager.send_tip(actor, "bar_territory_nodolg_1_hit", nil, "dolg", nil, 507)
				return
			end	
		end
	end
	return
end

function bar_psih_come(actor, npc)
	news_manager.send_tip(actor, "bar_psih_come", nil, "barman")
end

function bar_actor_is_enemy(actor, npc)
	xr_gulag.setGulagEnemy("bar_dolg_general", db.actor)
	xr_gulag.setGulagEnemy("bar_dolg_veterans", db.actor)
	xr_gulag.setGulagEnemy("bar_dolg_bunker", db.actor)
	xr_gulag.setGulagEnemy("bar_visitors", db.actor)
end

local items_no_transfer = {
	["device_pda"] = true,
	["bolt"] = true,
}
local function transfer_object_item(item)
    out_object:transfer_item(item, in_object)
end
function bar_arena_teleport ( actor, npc)
	level.add_pp_effector("black.ppe", 233, false)
	
	dsh.timeout( 1000, function()
		db.actor:set_actor_position(patrol("t_way"):point(0))
		local dir = patrol("t_look"):point(0):sub(patrol("t_way"):point(0))
		db.actor:set_actor_direction(-dir:getH())
		enable_ui()
	end )

	ogse.transfer_items_to_box(story_ids.bar_arena_inventory_box_2, false, items_no_transfer, nil)

	local spawn_items = {}	

	if	has_alife_info("bar_arena_fight_1") then 
		table.insert(spawn_items, "wpn_pm")
		table.insert(spawn_items, "ammo_9x18_fmj")
		table.insert(spawn_items, "ammo_9x18_pmm")
		table.insert(spawn_items, "novice_outfit")
		table.insert(spawn_items, "wpn_knife")
	elseif	has_alife_info("bar_arena_fight_2") then
		table.insert(spawn_items, "wpn_mp5")
		table.insert(spawn_items, "ammo_9x19_fmj")
		table.insert(spawn_items, "ammo_9x19_pbp")
		table.insert(spawn_items, "killer_outfit")	
		table.insert(spawn_items, "wpn_knife")		
	elseif	has_alife_info("bar_arena_fight_3") then
		table.insert(spawn_items, "wpn_toz34")
		table.insert(spawn_items, "ammo_12x70_buck")
		table.insert(spawn_items, "ammo_12x76_zhekan")
		table.insert(spawn_items, "bandit_outfit")
		table.insert(spawn_items, "wpn_knife")
	elseif	has_alife_info("bar_arena_fight_4") then			
		table.insert(spawn_items, "wpn_ak74u")
		table.insert(spawn_items, "ammo_5.45x39_fmj")
		table.insert(spawn_items, "ammo_5.45x39_ap")
		table.insert(spawn_items, "soldier_outfit")
		table.insert(spawn_items, "wpn_knife")
	elseif	has_alife_info("bar_arena_fight_5") then	
		table.insert(spawn_items, "wpn_l85")
		table.insert(spawn_items, "ammo_5.56x45_ss190")
		table.insert(spawn_items, "ammo_5.56x45_ap")
		table.insert(spawn_items, "bandage")
		table.insert(spawn_items, "bandage")
		table.insert(spawn_items, "medkit")
		table.insert(spawn_items, "svoboda_light_outfit")
		table.insert(spawn_items, "wpn_knife")
	elseif	has_alife_info("bar_arena_fight_6") then
		table.insert(spawn_items, "wpn_abakan")
		table.insert(spawn_items, "ammo_5.45x39_fmj")
		table.insert(spawn_items, "ammo_5.45x39_ap")
		table.insert(spawn_items, "dolg_outfit")
		table.insert(spawn_items, "wpn_knife")
	elseif	has_alife_info("bar_arena_fight_7") then
		table.insert(spawn_items, "grenade_f1")
		table.insert(spawn_items, "grenade_rgd5")
		table.insert(spawn_items, "grenade_rgd5")
		table.insert(spawn_items, "grenade_rgd5")
		table.insert(spawn_items, "bandage")
		table.insert(spawn_items, "bandage")
		table.insert(spawn_items, "bandage")
		table.insert(spawn_items, "medkit")
		table.insert(spawn_items, "medkit")
		table.insert(spawn_items, "wpn_knife")
	elseif	has_alife_info("bar_arena_fight_8") then
		table.insert(spawn_items, "wpn_g36")
		table.insert(spawn_items, "ammo_5.56x45_ss190")
		table.insert(spawn_items, "ammo_5.56x45_ap")
		table.insert(spawn_items, "exo_outfit")
		table.insert(spawn_items, "wpn_knife")
	end
	
	local k,v = 0,0
	
	for k,v in pairs(spawn_items) do
		alife():create(v,	
						db.actor:position(),
						db.actor:level_vertex_id(),	
						db.actor:game_vertex_id(), 
						db.actor:id())
	end	
	
end

function bar_arena_weapon_slot ()
	if	has_alife_info("bar_arena_fight_1") then  
		db.actor:activate_slot(1)
	else 
		db.actor:activate_slot(2)
	end
end

function bar_arena_teleport_2 ( actor, npc)		
	disable_ui()	
	level.add_pp_effector ("black.ppe", 234, false)
	
	dsh.timeout( 1000, function()
		db.actor:set_actor_position(patrol("t_walk_2"):point(0))
		local dir = patrol("t_look_2"):point(0):sub(patrol("t_walk_2"):point(0))
		db.actor:set_actor_direction(-dir:getH())
		enable_ui()
	end )
	
	-- удаляем то, что у актора есть
	db.actor:inventory_for_each(function(item, npc)
		if not item then return end
		if not items_no_transfer[item:section()] then ogse.remove_item_from_inventory(item, npc) end
	end)
	-- переносим к нему его барахло
	ogse.transfer_items_from_box(story_ids.bar_arena_inventory_box_2)
end

function barman_give_extra_task (actor, npc)
	if has_alife_info ("agroprom_military_case_done") and not has_alife_info ("bar_darklab_document_start") then
		db.actor:give_info_portion("barman_job_1")
		return
	elseif has_alife_info ("bar_darklab_document_done") and not has_alife_info ("bar_x16_documents_start") then
		db.actor:give_info_portion("barman_job_2")
		return
	elseif has_alife_info ("bar_x16_documents_done") and not has_alife_info ("bar_deactivate_radar_start") then
		db.actor:give_info_portion("barman_job_3")
		return
	end
	return	
end

function trader_extra_task (actor, npc)
	if has_alife_info ("esc_serious_talk") and not has_alife_info ("agroprom_military_case") then
		db.actor:give_info_portion("trader_job")
		return
	end
	return
end

function scientist_extra_task (actor, npc)
	if has_alife_info ("yan_find_scientist_done") and not has_alife_info ("yan_find_vasilyev_start") then
		db.actor:give_info_portion("scientist_job")
		return
	end
	return
end

function military_max_dead (actor, npc)
end

function military_lukash_dead (actor, npc)
end

function mil_courier_death (actor, npc)
    actor:give_info_portion ("mil_courier_dead")
    if has_alife_info("mil_leader_quest2_start") then
       if not has_alife_info("mil_courier_visited") then
          level_tasks.set_task_state (task.fail, "mil_courier_job", 1)
       end   
       level_tasks.set_task_state (task.completed, "mil_courier_job", 2)
       level_tasks.set_task_state (task.completed, "mil_courier_job", 0)
    end   
end

function mil_courier_quest_fail (actor, npc)
    if has_alife_info("mil_courier_quest") == false then return end
    level_tasks.set_task_state (task.fail, "mil_courier_job", 0)
    actor:give_info_portion ("mil_courier_quest_failed")
end

function mil_scull_news (actor, npc)
end

function mil_sniper_dead (actor, npc)
    if has_alife_info("mil_dolg_final_task") then
       level_tasks.remove_location_by_sid(npc:story_id (), "mil_sniper_location")
    end       
end

function mil_actor_enemy_set (actor, npc)   
end

function mil_actor_enemy_reset (actor, npc)     
end

function mil_bomb_explode (actor, npc)
    local source = nil
    local sim = alife ()
    if sim then
       local se_obj = sim:story_object (story_ids.Mil_Bomb)  
       if se_obj then
          source = level.object_by_id(se_obj.id)
       end
    end

    if source then
        local h = hit ()
	    h.power = 1000000
	    h.direction = vector():set( 1, 0, 0 )
	    h.impulse = 1
	    h.draftsman = source
	    h.type = hit.chemical_burn
	    source:hit (h)
	    source:explode(0)
    end
end

function mil_set_alarm (actor, npc)
    actor:give_info_portion ("mil_freedom_under_attack")
    
    local skull = level_object_by_sid (708)
    if skull == nil then 
       return 
    end

    this.set_stalker_enemy (702, skull)     -- hit to Lukash
    this.set_stalker_enemy (707, skull)     -- hit to Max
    this.set_stalker_enemy (730, skull)     -- hit to Sniper1
    this.set_stalker_enemy (731, skull)     -- hit to Sniper2
    this.set_stalker_enemy (732, skull)     -- hit to Sniper3
end

function sar2_monolith_explode (actor, npc)
    local monolith = level_object_by_sid (1305)
    if monolith == nil then
       abort ("Object MONOLITH with SID 1305 not found")
    end    
    local h = hit ()
    h.power = 1000
    h.direction = vector():set( 1, 0, 0 )
    h.impulse = 1
    h.draftsman = actor
    h.type = hit.chemical_burn
    monolith:hit (h)
end

function set_stalker_enemy (sid, draftsman)
    local npc = level_object_by_sid (sid)
    if npc == nil or npc:alive () == false then
       return 
    end    
    local h = hit ()
    h.power = 0
    h.direction = vector():set( 1, 0, 0 )
    h.impulse = 0
    h.draftsman = draftsman
    h.type = hit.strike
    npc:hit (h)
end



function mil_remove_cook_map_spot (actor, npc)
    level_tasks.remove_location_by_sid(story_ids.Mil_Cook, "mil_cook_location")
end

function mil_transfer_docs_to_ara (actor, npc)
    --local ara = level_object_by_sid (719)
    --local pavlik = level_object_by_sid (710)
    --if ara == nil or pavlik == nil or pavlik:object ("mil_courier_doc") == nil then
       --return
    --end   
    --ara:transfer_item (pavlik:object ("mil_courier_doc"), pavlik)
end

function mil_emeny_nearest (actor, npc)
    if actor == nil or actor:alive () == false then
       return
    end    

    if xr_gulag.isGulagEnemy( "mil_freedom", actor ) then
       actor:give_info_portion ("mil_enemy_nearest")
    end
end


function mil_cap_mapspot (actor, npc)
    local cap = level_object_by_sid (724)
    if cap == nil or cap:alive () == false then
       return 
    end    
    
    if not has_alife_info("mil_fblockpost_spot_set") then
       actor:give_info_portion ("mil_fblockpost_spot") 
       actor:give_info_portion ("mil_fblockpost_spot_set")
       level_tasks.add_location_by_sid (story_ids.Mil_Kap, "mil_fblockpost_location")
    end
end

function mil_cap_mapspot_remove (stalker1, stalker2)
    if has_alife_info("mil_fblockpost_spot") then
       level_tasks.remove_location_by_sid (story_ids.Mil_Kap, "mil_fblockpost_location", true)
       db.actor:disable_info_portion ("mil_fblockpost_spot_remove")
    end      
end

function set_actor_enemy_for_freedom (actor, npc)
    xr_gulag.setGulagEnemy ("mil_freedom", actor)
end


-- GARBAGE

function gar_send_dolg_warning()
	if db.actor then
		if xr_gulag.getGulagPopulation("gar_dolg") > 0 then
			news_manager.send_tip(db.actor, "gar_dolg_warning", 0, "dolg")
		end
	end
end


-------------------------------------------------------------------------------------
-- Функции для DarkValley
-------------------------------------------------------------------------------------
function val_escort_guard_death(actor, npc)
    local idx = string.sub(npc:name(), -1)
	local t = db.storage[npc:id()].death

    actor:disable_info_portion("val_escort_guard" .. idx .. "_combat")
    actor:give_info_portion("val_escort_guard" .. idx .. "_dead")
    
	-- nv140501 if killer unknown, give credit to player
	if t ~= nil and (t.killer == actor:id() or t.killer == -1) then
        actor:give_info_portion("val_escort_actor_helped")
	end
    --"on_info     = %-val_escort_guard1_combat +val_escort_guard1_dead%\n" ..
    --"on_info2    = {=killed_by_actor} %+val_escort_actor_helped%\n" ..
end

function val_escort_guard_hit(actor, npc)
    local idx = string.sub(npc:name(), -1)
	local t = db.storage[npc:id()].hit

	if t ~= nil then
	    if t.who == actor:id() then
            actor:give_info_portion("val_escort_combat")
            actor:give_info_portion("val_escort_actor_helped")
            if not has_alife_info("val_escort_nap1_start_combat") then
                actor:give_info_portion("val_escort_captive_enemy")
            end
	    else
	        local npc1 = level_object_by_sid(406)
	        if npc1 ~= nil and t.who == npc1:id() then
                actor:give_info_portion("val_escort_combat")
                actor:give_info_portion("val_escort_nap1_start_combat")
	        --else
            --    actor:give_info_portion("val_escort_guard" .. idx .. "_combat")
	        end
	    end
	end
    --"on_info     = {=hit_by_actor} %+val_escort_combat +val_escort_actor_helped%, %+val_escort_guard1_combat%\n" ..
    --"on_info2    = {+val_escort_combat -val_escort_nap1_start_combat} %+val_escort_captive_enemy%\n" ..
    --"on_info3    = {=hitted_by(406) -val_escort_captive_enemy} %+val_escort_nap1_start_combat%\n" ..
end

function val_escort_guard_combat(actor, npc)
    local idx = string.sub(npc:name(), -1)

    actor:give_info_portion("val_escort_guard" .. idx .. "_combat")
    
    if npc:see(actor) then
        if not has_alife_info("val_escort_nap1_start_combat") then
            actor:give_info_portion("val_escort_captive_enemy")
        end
        actor:give_info_portion("val_escort_combat")
    end
    --"on_info     = %+val_escort_guard1_combat%\n" ..
    --"on_info2    = {=see_actor -val_escort_nap1_start_combat -val_escort_captive_enemy} %+val_escort_captive_enemy%\n" ..
    --"on_info3    = {=see_actor -val_escort_combat} %+val_escort_combat% ;remark@val_escort_guard1_fight\n" ..
end

function val_escort_guard_free(actor, npc)
    --local idx = string.sub(npc:name(), -1)

    actor:give_info_portion("val_escort_guards_free")
    actor:disable_info_portion("val_escort_guard" .. string.sub(npc:name(), -1) .. "_combat")
    --"on_info             = %+val_escort_guards_free -val_escort_guard1_combat%\n"
end

-------------------------------------------------------------------------------------
-- kill
-------------------------------------------------------------------------------------
function killactor (actor, npc)
    npc:set_relation(game_object.enemy, db.actor)
	npc:set_goodwill( -5000, db.actor )
end

function kill(actor, npc)
	npc:kill( npc )
end


-------------------------------------------------------------------------------------
-- Функции для Агропрома
-------------------------------------------------------------------------------------

function agr_krot_sos( actor, npc )
	news_manager.send_tip( actor, "tips_agr_krot_sos", 0, "krot", 10000 )
end

function agr_krot_sos_1_2( actor, npc )
	if not has_alife_info( "agr_help_krot_start" ) and
	   not has_alife_info( "agr_help_krot_done" ) and
	   not has_alife_info( "agr_krot_skirmish_start" ) and
	   not has_alife_info( "agr_krot_dead" )
	then
		actor:give_info_portion( "agr_help_krot_start" )
		news_manager.send_tip( actor, "tips_agr_krot_sos1", 0, "krot", 10000 )

		if has_alife_info( "agr_help_stalkers_defence_dead" ) then
			news_manager.send_tip( actor, "tips_agr_krot_sos2", 0, "krot", 10000 )
		end
	end
end

function agr_knockdown ()
	local snd_obj = xr_sound.get_safe_sound_object([[affects\tinnitus3a]])
	if snd_obj then
		snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
	level.add_cam_effector("camera_effects\\earthquake.anm", 1974, false, "")
	level.add_pp_effector("blink.ppe", 1522, false)
end

function agr_contuz (actor, npc)
	local sound_obj_l		= xr_sound.get_safe_sound_object( [[affects\psy_blackout_l]] )
    local sound_obj_r		= xr_sound.get_safe_sound_object( [[affects\psy_blackout_r]] )
    
    if sound_obj_l then
		sound_obj_l:play_no_feedback(actor, sound_object.s2d, 0, vector():set(-1, 0, 1), 1.0)
	end
	if sound_obj_r then
		sound_obj_r:play_no_feedback(actor, sound_object.s2d, 0, vector():set( 1, 0, 1), 1.0)
	end
	level.add_pp_effector("sleep.ppe", 1523, true)
    level.set_pp_effector_factor(1523, 1.0)
    swm_legs.hidden_legs()
end

function agr_contuz_after (actor, npc)
	level.remove_pp_effector(1523)
	swm_legs.show_legs()
end

function agr_cam_effect ()
	level.add_cam_effector2("camera_effects\\agroprom_doctor_cam.anm", 123, false, "")
end

function agr_weapon(actor, npc)
	local actor = db.actor	
	if 	actor ~= nil then 
		actor:activate_slot(2)
	end
end

function agr_hold_enemy(actor, npc)
	local gulag = xr_gulag.get_gulag_by_name("agr_factory_hold")
	
	local h  = hit()
	h.power     = 0.01
	h.direction = vector():set( 1, 0, 0 )
	h.draftsman = actor
	h.impulse   = 1
	h.type      = hit.wound
	
	for k, v in pairs(gulag.Object) do
		if v ~= true and level.object_by_id( k ) ~= nil then
			v:hit( h )
		end
	end	
end
--------------------------------------------------------- 
-- PRIPYAT
--------------------------------------------------------- 
function pri_zombied_in_combat_inc(actor, npc)
    gulag_pripyat.zombied_in_combat[npc:name()] = true
end

function pri_zombied_in_combat_dec(actor, npc)
    gulag_pripyat.zombied_in_combat[npc:name()] = nil
end

function pri_drop_rpg_ammo(actor, npc)
    local item = npc:object("ammo_og-7b")
    if item then
        npc:drop_item(item)
    end
end

function pri_give_ammo_og7b(actor, npc)
    alife():create("ammo_og-7b", npc:position(), npc:level_vertex_id(), npc:game_vertex_id(), npc:id())
    alife():create("ammo_og-7b", npc:position(), npc:level_vertex_id(), npc:game_vertex_id(), npc:id())
end


-------------------------------------------------------------------------------------
-- Функции для работы с вертолётами
-------------------------------------------------------------------------------------

function heli_set_enemy_actor(actor, npc)
	local st = db.storage[npc:id()]
	if not st.combat.enemy_id and actor:alive() then
		st.combat.enemy_id = actor:id()

		heli_snd.play_snd( st, "see_enemy", 1 )
	end 
end

function heli_set_enemy(actor, npc, p)
	local st  = db.storage[npc:id()]
	local obj = level_object_by_sid( p[1] )

	if not st.combat.enemy_id and obj:alive() then
		st.combat.enemy_id = obj:id()

		heli_snd.play_snd( st, "see_enemy", 1 )
	end
end

function heli_clear_enemy(actor, npc)
    db.storage[npc:id()].combat:forget_enemy()
end

function heli_start_flame(actor, npc)
	bind_heli.heli_start_flame( npc )
end

function heli_die(actor, npc)
	bind_heli.heli_die( npc )
end

-------------------------------------------------------------------------------------
-- Функции для работы с погодными эффектами
-------------------------------------------------------------------------------------
function blowout_hours()
    local hours = level.get_time_hours()
    if hours > 5 and hours < 21 then
        return "day"
    end
    return "night"
end

function start_small_reject (actor, npc)
	this.aes_earthshake()
end

function start_prepare_reject (actor, npc)
	log3("start_prepare_reject")
    local hours_type = blowout_hours()
    level.set_weather_fx("fx_blowout_" .. hours_type)
	this.aes_earthshake()
end

function start_full_reject (actor, npc)
end

function start_aes_blowout (actor, npc)
    level.add_pp_effector ("surge_fade.ppe", 2011, false)
    this.aes_earthshake()
end

function start_aes_deathzone (actor, npc)
    level.add_pp_effector ("blink.ppe", 1975, false)
end

function aes_grenade_explode (actor, npc)
    local obj = level_object_by_sid (1101)
    if obj == nil then return end
    local h = hit ()
    h.power = 1000
    h.direction = vector():set (1, 0, 0)
    h.impulse = 1
    h.draftsman = obj
    h.type = hit.chemical_burn
    obj:hit (h)
end

function aes_kill_actor (actor, npc)
    if actor ~= nil and actor.health > 0 then 
       actor:kill (actor)
    end   
end

function set_sidorovich_animation (npc)
    local sidor = level_object_by_sid (1118)
    if sidor == nil then
       abort ("SIDOROVICH NOT FOUND !!!")
    end
    --sidor:clear_animations ()
    sidor:play_cycle ("wonder", true)
    --sidor:add_animation ("idle_looped")
end

function aes_zombie_hit1 (npc)
end

function aes_zombie_hit2 (npc)
end

-- постпроцесс Выброса
function aes_earthshake()
	if not has_alife_info("freeplay") then
		local snd_obj = xr_sound.get_safe_sound_object([[ambient\earthquake]])

		if snd_obj then
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
			level.add_cam_effector("camera_effects\\earthquake.anm", 1974, false, "")
		end

		level.add_pp_effector("wink.ppe", 1973, false)
		level.add_pp_effector("vibros_p.ppe", 1974, false)
		level.add_pp_effector("total_recall.ppe", 1986, false)
	end
end

function vovan_camera_test (npc)
	level.add_cam_effector("camera_effects\\test.anm", "")	                  
end

-------------------------------------------------------------------------------------
-- Функции для Янтаря
----------------------------------------------------------------------------------
function yan_actor_sleep (actor, npc)
	db.actor:set_actor_position(patrol("yan_actor_sleep"):point(0))
	local dir = patrol("yan_actor_sleep"):point(1):sub(patrol("yan_actor_sleep"):point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function yan_actor_sleep_1 (actor, npc)
	db.actor:set_actor_position(patrol("yan_actor_sleep_1"):point(0))
	local dir = patrol("yan_actor_sleep_1"):point(1):sub(patrol("yan_actor_sleep_1"):point(0))
	db.actor:set_actor_direction(-dir:getH())
end

function yan_dream_voices (actor, npc)
        local sound_obj_l		= xr_sound.get_safe_sound_object( [[characters_voice\scenario\yantar\dream_talk_l]] )
        local sound_obj_r		= xr_sound.get_safe_sound_object( [[characters_voice\scenario\yantar\dream_talk_r]] )
        
        if sound_obj_l then
			sound_obj_l:play_no_feedback(actor, sound_object.s2d, 0, vector():set(-1, 0, 1), 1.0)
		end
		if sound_obj_r then
			sound_obj_r:play_no_feedback(actor, sound_object.s2d, 0, vector():set( 1, 0, 1), 1.0)
		end
end

function yan_gluk (actor, npc)
		local sound_obj_l		= xr_sound.get_safe_sound_object( [[affects\psy_blackout_l]] )
        local sound_obj_r		= xr_sound.get_safe_sound_object( [[affects\psy_blackout_r]] )
        
		if sound_obj_l then
			sound_obj_l:play_no_feedback(actor, sound_object.s2d, 0, vector():set(-1, 0, 1), 1.0)
		end
		if sound_obj_r then
			sound_obj_r:play_no_feedback(actor, sound_object.s2d, 0, vector():set( 1, 0, 1), 1.0)
		end

		level.add_cam_effector("camera_effects\\earthquake.anm", 1974, false, "")
end

function x18_gluk (actor, npc)
		level.add_pp_effector ("blink.ppe", 234, false)
		local sound_obj_l		= xr_sound.get_safe_sound_object( [[affects\psy_blackout_l]] )
        local sound_obj_r		= xr_sound.get_safe_sound_object( [[affects\psy_blackout_r]] )
        local snd_obj			= xr_sound.get_safe_sound_object( [[affects\tinnitus3a]] )
		
		if snd_obj then
			snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
		end
		if sound_obj_l then
			sound_obj_l:play_no_feedback(actor, sound_object.s2d, 0, vector():set(-1, 0, 1), 1.0)
		end
		if sound_obj_r then
			sound_obj_r:play_no_feedback(actor, sound_object.s2d, 0, vector():set( 1, 0, 1), 1.0)
		end
		
		level.add_cam_effector("camera_effects\\earthquake.anm", 1974, false, "")
end

function yan_sleep_not_relocate (actor, npc)
		db.actor:actor_sleep(0, 180)
end

function yantar_kruglov_talk(actor,npc)
	xr_sound.set_sound_play(npc, "rostok_kruglov_help_6")
end

function yantar_professor_spam_1 (actor, npc)
    news_manager.send_tip(db.actor, "general_ecolog_tip_1", nil, "saharov", nil, 902)
end

function yantar_professor_spam_2 (actor, npc)
    news_manager.send_tip(db.actor, "general_ecolog_tip_2", nil, "saharov", nil, 902)
end

function yantar_vasilyev_spam (actor, npc)
    news_manager.send_tip(db.actor, "storyline_vasilyev_tip", nil, "ecolog", nil, 903)
end

function yan_saharov_message (actor, npc)
    news_manager.send_tip(db.actor, "yan_saharov_message", nil, "saharov", nil, 902)
    db.actor:give_info_portion("labx16_find")
end

function yan_saharov_message_2 (actor, npc)
    news_manager.send_tip(db.actor, "yan_saharov_message_2", nil, "saharov", nil, 902)
end

function yan_saharov_message_3 (actor, npc)
    news_manager.send_tip(db.actor, "yan_saharov_message_3", nil, "saharov", nil, 902)
end

function yan_ghost_pda (actor, npc)
    if has_alife_info("agr_gunslinger_flash_have") then 
        db.actor:give_info_portion("yan_provodnik_spawn")
    end
    news_manager.send_tip(db.actor, "storyline_ghost_tip", nil, "prizrak")
end

function start_yantar_dream(actor, npc)
	game.start_tutorial("yantar_dream")
end

function end_yantar_dream(actor, npc)
	db.actor:give_info_portion("yantar_find_ghost_task_start")
end

-----------------------------radar
function rad_sos_spam(actor, npc)
	news_manager.send_tip(actor, "tips_rad_sos_suicide", nil, "stalker", nil, 1004)
end

function monolith_generator_hit (actor, npc)
end

function start_x18_dream(actor, npc)
	game.start_tutorial("x18_dream")
end

function end_x18_dream(actor, npc)
	db.actor:give_info_portion("dar_x18_dream")
end

function aes_final_movie(actor, npc)
	db.actor:give_info_portion("game_end")
	game.start_tutorial("mov_refuse_osoznanie")
end
------------------------------------------------------------------------------------
-- Функции для Радара
------------------------------------------------------------------------------------
function rad_psi_hit (actor, npc)
	level.add_pp_effector ("radar_psi.ppe", 2006, false)
end

function start_radar_dream(actor, npc)
	game.start_tutorial("radar_dream")
end

function end_radar_dream(actor, npc)
	db.actor:give_info_portion("bun_patrol_start")
end

------------------------------------------------------------------------------------
-- Функции для Саркофага
------------------------------------------------------------------------------------
function destroy_monolith_generator(actor, npc)
    local source = nil
    local sim = alife()
    if sim then
       local se_obj = sim:story_object(story_ids.sar2_destroyable_monolith)  
       if se_obj then
          source = level.object_by_id(se_obj.id)
       end
    end

    if source == nil then
       abort ("MONOLITH GENERATOR story id 1305 not found")
       return
    end

    local h = hit ()
    h.power = 1000000
    h.direction = vector():set( 1, 0, 0 )
    h.impulse = 1
    h.draftsman = source
    h.type = hit.chemical_burn
    source:hit (h)       
end

function sar_monolith_miracle(actor, npc)
	--' Убил лидеров группировок
	if has_alife_info("mil_lukash_dead") and
	   has_alife_info("bar_voronin_dead")
	then
		game.start_tutorial("mov_desire_3")
		return
	end

	--' Много денег
	if db.actor:money() >= 100000 then
		game.start_tutorial("mov_desire_2")	
		return
	end

	--' Хорошая репутация
	if db.actor:character_reputation() >= 1000 then
		game.start_tutorial("mov_desire_1")	
		return
	end

	--' плохая репутация
	if db.actor:character_reputation() <= -1000 then
		game.start_tutorial("mov_desire_4")	
		return
	end

	game.start_tutorial("mov_desire_5")	
end

function game_credits(actor, npc)
	db.gameover_credits_started = true
	game.start_tutorial("credits_seq")
end

function game_over(actor, npc)
	if db.gameover_credits_started ~= true then
		return
	end
	cmd("main_menu on")
end

function after_credits(actor, npc)
	if db.gameover_credits_started ~= true then
		return
	end
	cmd("disconnect")
end


function pri_game_over(actor, npc)
	cmd("main_menu on")
end

function esc_init_dialod ()
	local trader = level_object_by_sid(003)
	db.actor:run_talk_dialog(trader)
end

function oso_init_dialod ()
	-- local oso = level_object_by_sid(1307)
	-- db.actor:run_talk_dialog(oso)
end

function presentation_task ()	
end

function change_leader(actor, npc)	
	if xr_gulag.getGulagPopulation(823) < 2 or
		xr_gulag.isGulagEnemy( 823, actor ) or
		has_alife_info("pri_followers_actor_enemy") 
	then
		db.actor:give_info_portion("pri_followers_all_dead")
	end
end

function on_tutor_gameover_stop()
	cmd("main_menu on")
end

function actor_stop_sleeping()
end

function is_actor_enemy(story_id)
	if story_id then
		local npc = level_object_by_sid (story_id)
		local actor = db.actor
		
		if npc and actor then
			local t = db.storage[npc:id()].death
			return npc:relation(actor) == game_object.enemy or (t ~= nil and t.killer == actor:id())
		end
	end
    return false
end

------------------------------------------------------- ARENA_EXTENSION_MOD--------------------------------------------------------

function aem_draw()
	aem_lights.draw()
end

function aem_win()
	aem_lights.win()
end

function aem_foul()
	aem_lights.foul()
end

function aem_death(actor, npc, p)
	aem_manager.get_aem():on_death(npc, p[1])
end

function aem_finish()
	aem_manager.get_aem():finish()
end

function switch(actor, npc)
	if db.actor:has_info("aem_go_bar") then
		npc:add_restrictions("bar_restrictor", "")
	else
		npc:remove_all_restrictions()
	end
end

function send_switch_signal(actor, lamp, p)
	local signal_name = p[1]
	ASSERT(signal_name, "xr_effects.send_switch_on_signal: signal name is not defined for the object '%s'", lamp:name())
	local state = p[2]
	ASSERT(state == 'on' or state == 'off', "xr_effects.send_switch_signal: unknown state for the switch signal '%s' sended from the object '%s'", signal_name, lamp:name())
	ogse_signals.get_mgr():call(signal_name, state == 'on')
end
function send_switch_signal_auto(actor, lamp, p)
	local st = db.storage[lamp:id()]
	ASSERT(st, "xr_effects.send_switch_signal_auto: storage is not initialized for the object '%s'", lamp:name())
	local light_config = st.light_config
	ASSERT(light_config, "xr_effects.send_switch_signal_auto: light_config is not initialized for the object '%s'", lamp:name())
	local signal_name = light_config.signal_name
	ASSERT(signal_name, "xr_effects.send_switch_signal_auto: signal name is not defined for the object '%s'", lamp:name())
	local state = p[1]
	ASSERT(state == 'on' or state == 'off', "xr_effects.send_switch_signal_auto: unknown state for the switch signal '%s' sended from the object '%s'", signal_name, lamp:name())
	ogse_signals.get_mgr():call(signal_name, state == 'on')
end
function esc_wolf_thanks()
end

--Объект удалит сам себя, если в логике сделать например on_signal = sound_end | nil %=release%
function release(actor, npc)
	local sobj = alife():object(npc:id())
	if sobj then
		alife():release(sobj)
	end
end

------------------------------------------------------- ARENA_EXTENSION_MOD--------------------------------------------------------
local function find_sidor_door()
	local sobj = alife():object("trader_door")
	if sobj then
		local obj = level.object_by_id(sobj.id)
		if obj then
			return obj
		end
	end
end

local trader_door_storage = nil

function trader_door_closed2()
	if not trader_door_storage then
		local trader_door = find_sidor_door()
		ASSERT(trader_door, "[trader_door_closed2] object 'trader_door' not found!")
		trader_door_storage = db.storage[trader_door:id()]
		ASSERT(trader_door_storage, "[trader_door_closed2] no logic initialized for the object 'trader_door'!")
	end
	return trader_door_storage.ph_door and trader_door_storage.ph_door.closed
end

local sound_zone
local max_sidor_radio_dist = 11.0
local min_sidor_radio_dist = 4.0
local sidor_radio_range = max_sidor_radio_dist - min_sidor_radio_dist
function sidor_radio_volume_control(obj_pos, actor_pos)
	local dist = actor_pos:distance_to(obj_pos)
	if dist > max_sidor_radio_dist then
		--log1("out of range")
		return 0.0
	end
	if not sound_zone then
		local sobj = alife():object("sidor_radio_sound_zone")
		ASSERT(sobj, "[sidor_radio_volume_control] no 'sidor_radio_sound_zone' object found!")
		sound_zone = level.object_by_id(sobj.id)
	end
	-- если есть рестриктор-зона звучания, и мы в него не попадаем, то громкость нулевая
	if sound_zone and not sound_zone:inside(actor_pos) then
		--log1("out of zone")
		return 0.0
	end
	--log3("dist=%f", dist)
	local v = 1 - (dist - min_sidor_radio_dist) / sidor_radio_range
	local res = math.clamp(v, 0, 1)
	local door_closed = trader_door_closed2()
	--log3("door_closed: %s", door_closed)
	if dist > 4 then
		if door_closed then
			res = res * 0.2
		end
	end
	return res
end
------------------------------------------------------------------------------------------------------------------------------------------------------------------------